In [24]:
import pandas as pd
import json

In [25]:
import os
print(os.getcwd())

c:\Users\Admin\Downloads\mle_code_assessment\mle_code_assessment\scripts

In [26]:
from pathlib import Path

base_path = Path.cwd()

In [27]:
# file_path_cal = r"..\data\calendar_events.json"
# file_path_crm = r"..\data\crm_events.json"
# print(file_path_cal)

In [28]:
df_crm = pd.read_json(r"..\data\crm_events.json")
df_crm

,crm_id,subject,client_name,client_company,relationship_owner,meeting_date,meeting_time,meeting_type,location,notes,status,created_at
0,CRM-1001,Q1 Portfolio Review,David Park,Meridian Capital,Sarah Chen,2025-03-10,2026-05-26 14:00:00,In-Person,HQ - Conference Room B,Review Q1 allocation strategy. David requested...,Completed,2025-02-28 09:15:00+00:00
1,CRM-1002,Portfolio Walkthrough,Mark Johnson,Summit Advisors,Sarah Chen,2025-03-12,2026-05-26 10:00:00,In-Person,NYC Office - 30th Floor,Walk through current portfolio positioning and...,Confirmed,2025-03-01 11:30:00+00:00
2,CRM-1003,Introductory Call,Rachel Torres,Lakeshore Partners,James Wu,2025-03-14,2026-05-26 15:00:00,Virtual,NaN,First touch. Referred by Tom Nakamura at Bridg...,Scheduled,2025-03-10 14:00:00+00:00
3,CRM-1004,Due Diligence Review,Patricia Langley,Crestview Holdings,Sarah Chen,2025-03-13,2026-05-26 14:00:00,In-Person,DC Office - Main Conference Room,DD deep-dive on Fund VII. Legal team joining.,Confirmed,2025-03-05 08:45:00+00:00
4,CRM-1005,Investor Update,Kevin O'Brien,Pinnacle Group,James Wu,2025-03-17,2026-05-26 11:00:00,In-Person,Boston Office,Quarterly update. Kevin may bring CIO.,Confirmed,2025-03-03 16:20:00+00:00
5,CRM-1006,Pipeline Review,NaN,NaN,Sarah Chen,2025-03-14,2026-05-26 16:00:00,Internal,HQ - Room 4A,Weekly pipeline review with full team.,Confirmed,2025-01-15 10:00:00+00:00
6,CRM-1007,Follow-up Discussion,David Park,Meridian Capital,Sarah Chen,2025-03-18,NaT,Virtual,NaN,Follow up on fee schedule questions from Q1 re...,Scheduled,2025-03-11 09:30:00+00:00
7,CRM-1008,Lunch Meeting,Lisa Tran,Atlas Ventures,James Wu,03-15/2025,2026-05-26 12:00:00,In-Person,The Capital Grille - Georgetown,Relationship building. Lisa interested in infr...,Confirmed,2025-03-08 13:00:00+00:00
8,CRM-1009,Board Prep Session,NaN,NaN,Sarah Chen,2025-03-19,2026-05-26 09:00:00,Internal,HQ - Boardroom,Prep Q1 board materials. CANCELLED — reschedul...,Cancelled,2025-03-01 08:00:00+00:00
9,CRM-1010,Strategy Discussion,Alan Whitfield,Northwind Investments,James Wu,2025-03-20,2026-05-26 10:00:00,Virtual,Microsoft Teams,,Tentative,2025-03-14 17:30:00+00:00
10,CRM-1011,Annual Allocation Review,Elena Marcos,Horizon Wealth Partners,James Wu,2025-03-21,2026-05-26 09:00:00,In-Person,NYC Office,Full-year allocation review. Elena wants to di...,Confirmed,2025-03-07 10:15:00+00:00
11,CRM-1012,Co-Investment Opportunity,Thomas Grant,Granite Point Capital,Sarah Chen,2025-03-21,2026-05-26 14:00:00,Virtual,Zoom,Present co-invest opportunity in Fund VII deal...,Confirmed,2025-03-12 11:00:00+00:00
12,CRM-1013,LP Advisory Committee Prep,NaN,NaN,Sarah Chen,2025-03-24,2026-05-26 10:00:00,Internal,HQ - Boardroom,Prepare materials and talking points for upcom...,Confirmed,2025-03-15 09:00:00+00:00
13,CRM-1014,Quick Check-in,Michael Reeves,Evergreen Capital,James Wu,2025-03-25,2026-05-26 08:30:00,Virtual,NaN,Brief call re: capital call timing for Fund VI...,Confirmed,2025-03-20 14:00:00+00:00
14,CRM-1015,Infrastructure Fund Pitch,Lisa Tran,Atlas Ventures,James Wu,2025-03-26,2026-05-26 10:00:00,In-Person,HQ - Conference Room A,Formal pitch for Infra V. Follow-up from March...,Confirmed,2025-03-16 08:30:00+00:00
15,CRM-1016,ESG Compliance Discussion,Karen White,Redwood Institutional,Sarah Chen,2025-03-27,2026-05-26 13:00:00,Virtual,Microsoft Teams,Karen has ESG reporting requirements for their...,Confirmed,2025-03-18 09:45:00+00:00
16,CRM-1017,Closing Dinner,Multiple,Fund VII Investors,James Wu,2025-03-28,2026-05-26 19:00:00,In-Person,The Palm - DC,Celebratory dinner for Fund VII final close. 1...,Confirmed,2025-03-10 16:00:00+00:00
17,CRM-1018,Follow-up Call,Patricia Langley,Crestview Holdings,Sarah Chen,2025-03-25,2026-05-26 16:30:00,Virtual,NaN,Follow up on DD questions from 3/13 meeting. P...,Confirmed,2025-03-17 10:20:00+00:00
18,CRM-1019,Quarterly Business Review,NaN,NaN,Sarah Chen,2025-04-01,2026-05-26 14:00:00,Internal,HQ - Large Conference Room,"Q1 wrap. Review pipeline, AUM growth, client r...",Confirmed,2025-03-05 12:00:00+00:00
19,CRM-1020,Northwind - Fund VII Interest,Alan Whitfield,Northwind Investments,James Wu,2025-04-02,2026-05-26 11:00:00,In-Person,NYC Office - 30th Floor,Deep dive on Fund VII. Alan indicated potentia...,Tentative,2025-03-21 15:00:00+00:00

In [29]:
df_cal = pd.read_json(r"..\data\calendar_events.json")
df_cal

,event_id,title,organizer,attendees,start_time,end_time,location,description,is_recurring,status,created_at
0,CAL-A1,Q1 Portfolio Review - Meridian Capital,sarah.chen@firma.com,"[sarah.chen@firma.com, david.park@meridiancap....",2025-03-10T14:00:00,2025-03-10T15:30:00,Conference Room B,Quarterly review of portfolio allocation and p...,False,confirmed,2025-02-27 10:00:00+00:00
1,CAL-A2,Summit Advisors - Portfolio Discussion,sarah.chen@firma.com,"[sarah.chen@firma.com, mark.johnson@summitadv....",2025-03-12T10:00:00,2025-03-12T11:00:00,Zoom - https://zoom.us/j/98765432100,Portfolio walkthrough with Summit team.,False,confirmed,2025-02-28 15:45:00+00:00
2,CAL-A3,Weekly Team Sync,sarah.chen@firma.com,"[sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-11T09:00:00,2025-03-11T09:30:00,Virtual - Microsoft Teams,Standing weekly sync.,True,confirmed,2025-01-06 08:00:00+00:00
3,CAL-A4,Crestview Holdings - DD Meeting,sarah.chen@firma.com,"[sarah.chen@firma.com, patricia.langley@crestv...",2025-03-13T19:00:00Z,2025-03-13T20:30:00Z,DC Office - Main Conference Room,Due diligence deep-dive. Fund VII materials pr...,False,confirmed,2025-03-04 12:00:00+00:00
4,CAL-A5,Investor Update - Pinnacle,james.wu@firma.com,"[james.wu@firma.com, kevin.obrien@pinnaclegp.com]",2025-03-17T11:00:00,2025-03-17T12:00:00,Boston Office - Room 301,Quarterly investor update for Pinnacle Group.,False,confirmed,2025-03-02 14:30:00+00:00
5,CAL-A6,Pinnacle Group - Q1 Update,james.wu@firma.com,"[james.wu@firma.com, kevin.obrien@pinnaclegp.c...",2025-03-17T11:30:00,2025-03-17T12:30:00,Boston Office,Q1 update with Pinnacle Group. Sandra Mills (C...,False,confirmed,2025-03-10 09:15:00+00:00
6,CAL-A7,Internal Pipeline Review,sarah.chen@firma.com,"[sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-14T16:00:00,2025-03-14T17:00:00,HQ - Room 4A,Review active pipeline and upcoming client mee...,True,confirmed,2025-01-15 10:05:00+00:00
7,CAL-A8,Meridian Capital - Follow-up,sarah.chen@firma.com,"[sarah.chen@firma.com, david.park@meridiancap....",2025-03-18T15:00:00,2025-03-18T15:30:00,Zoom,Follow-up re: fee schedule and allocation chan...,False,confirmed,2025-03-11 09:45:00+00:00
8,CAL-A9,Atlas Ventures Lunch,james.wu@firma.com,"[james.wu@firma.com, lisa.tran@atlasvc.com]",2025-03-15T12:00:00,2025-03-15T13:30:00,The Capital Grille - Georgetown,Lunch with Lisa Tran. Exploring infrastructure...,False,confirmed,2025-03-07 16:00:00+00:00
9,CAL-A10,Board Prep - Q1 Materials Review,sarah.chen@firma.com,"[sarah.chen@firma.com, james.wu@firma.com, mic...",2025-03-19T09:00:00,2025-03-19T10:30:00,HQ - Boardroom,Review and finalize Q1 board presentation mate...,False,confirmed,2025-02-28 11:00:00+00:00
10,CAL-A11,Client Reception,priya.sharma@firma.com,[],2025-03-14T18:00:00,2025-03-14T20:00,NaN,NaN,False,tentative,2025-03-13 22:10:00+00:00
11,CAL-A12,Horizon Wealth - Year-End Review,james.wu@firma.com,"[james.wu@firma.com, elena.marcos@horizonwp.com]",2025-03-21T09:00:00,2025-03-21T10:30:00,NYC Office - 12th Floor,Annual review of allocation strategy and alter...,False,confirmed,2025-03-06 14:20:00+00:00
12,CAL-A13,Granite Point - Co-Invest Discussion,sarah.chen@firma.com,"[sarah.chen@firma.com, thomas.grant@granitepoi...",2025-03-21T14:00:00,2025-03-21T15:00:00,Zoom - https://zoom.us/j/11223344,Co-investment opportunity walkthrough for Fund...,False,confirmed,2025-03-11 16:30:00+00:00
13,CAL-A14,LPAC Prep Working Session,priya.sharma@firma.com,"[sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-24T10:00:00,2025-03-24T12:00:00,HQ - Boardroom,Prep session for LP Advisory Committee meeting...,False,confirmed,2025-03-14 11:00:00+00:00
14,CAL-A15,Michael Reeves - Quick Sync,james.wu@firma.com,"[james.wu@firma.com, michael.reeves@evergreenc...",2025-03-25T08:30:00,2025-03-25T08:45:00,NaN,Capital call timing discussion.,False,confirmed,2025-03-19 17:00:00+00:00
15,CAL-A16,Atlas Ventures - Infrastructure Deep Dive,james.wu@firma.com,"[james.wu@firma.com, lisa.tran@atlasvc.com, ra...",2025-03-26T10:00:00,2025-03-26T11:30:00,Conference Room A,Formal infrastructure fund presentation. Raj P...,False,confirmed,2025-03-15 10:00:00+00:00
16,CAL-A17,ESG + Compliance Review,sarah.chen@firma.com,"[sarah.chen@firma.com, karen.white@redwoodinst...",2025-03-27T15:00:00,2025-03-27T16:00:00,Microsoft Teams,Walk through ESG reporting framework and compl...,False,confirmed,2025-03-20 08:30:00+00:00
17,CAL-A18,Weekly Team Sync,sarah.chen@firma.com,"[sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-18T09:00:00,2025-03-18T09:30:00,Virtual - Microsoft Teams,Standing weekly sync.,True,confirmed,2025-01-06 08:00:00+00:00
18,CAL-A19,Fund VII Roadshow Prep,sarah.chen@firma.com,"[sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-28T14:00:00,2025-03-28T16:00:00,HQ - Room 4A,Finalize roadshow materials and talking points...,False,confirmed,2025-03-20 12:00:00+00:00
19,CAL-A20,Fund VII Closing Dinner,james.wu@firma.com,"[james.wu@firma.com, sarah.chen@firma.com, kev...",2025-03-28T19:00:00,2025-03-28T21:30:00,The Palm Restaurant,Celebratory dinner for Fund VII final close.,False,confirmed,2025-03-09 11:00:00+00:00
20,CAL-A21,Crestview Follow-up Call,sarah.chen@firma.com,"[sarah.chen@firma.com, patricia.langley@crestv...",2025-03-25T16:30:00,2025-03-25T17:00:00,Zoom,Follow-up on due diligence questions. Side let...,False,confirmed,2025-03-16 14:45:00+00:00
21,CAL-A22,QBR - Q1 Wrap,sarah.chen@firma.com,"[sarah.chen@firma.com, james.wu@firma.com, pri...",2025-04-01T14:00:00,2025-04-01T16:00:00,HQ - Large Conference Room,"Q1 quarterly business review. Pipeline, AUM, r...",False,confirmed,2025-03-04 09:30:00+00:00

In [30]:
df_crm

,crm_id,subject,client_name,client_company,relationship_owner,meeting_date,meeting_time,meeting_type,location,notes,status,created_at
0,CRM-1001,Q1 Portfolio Review,David Park,Meridian Capital,Sarah Chen,2025-03-10,2026-05-26 14:00:00,In-Person,HQ - Conference Room B,Review Q1 allocation strategy. David requested...,Completed,2025-02-28 09:15:00+00:00
1,CRM-1002,Portfolio Walkthrough,Mark Johnson,Summit Advisors,Sarah Chen,2025-03-12,2026-05-26 10:00:00,In-Person,NYC Office - 30th Floor,Walk through current portfolio positioning and...,Confirmed,2025-03-01 11:30:00+00:00
2,CRM-1003,Introductory Call,Rachel Torres,Lakeshore Partners,James Wu,2025-03-14,2026-05-26 15:00:00,Virtual,NaN,First touch. Referred by Tom Nakamura at Bridg...,Scheduled,2025-03-10 14:00:00+00:00
3,CRM-1004,Due Diligence Review,Patricia Langley,Crestview Holdings,Sarah Chen,2025-03-13,2026-05-26 14:00:00,In-Person,DC Office - Main Conference Room,DD deep-dive on Fund VII. Legal team joining.,Confirmed,2025-03-05 08:45:00+00:00
4,CRM-1005,Investor Update,Kevin O'Brien,Pinnacle Group,James Wu,2025-03-17,2026-05-26 11:00:00,In-Person,Boston Office,Quarterly update. Kevin may bring CIO.,Confirmed,2025-03-03 16:20:00+00:00
5,CRM-1006,Pipeline Review,NaN,NaN,Sarah Chen,2025-03-14,2026-05-26 16:00:00,Internal,HQ - Room 4A,Weekly pipeline review with full team.,Confirmed,2025-01-15 10:00:00+00:00
6,CRM-1007,Follow-up Discussion,David Park,Meridian Capital,Sarah Chen,2025-03-18,NaT,Virtual,NaN,Follow up on fee schedule questions from Q1 re...,Scheduled,2025-03-11 09:30:00+00:00
7,CRM-1008,Lunch Meeting,Lisa Tran,Atlas Ventures,James Wu,03-15/2025,2026-05-26 12:00:00,In-Person,The Capital Grille - Georgetown,Relationship building. Lisa interested in infr...,Confirmed,2025-03-08 13:00:00+00:00
8,CRM-1009,Board Prep Session,NaN,NaN,Sarah Chen,2025-03-19,2026-05-26 09:00:00,Internal,HQ - Boardroom,Prep Q1 board materials. CANCELLED — reschedul...,Cancelled,2025-03-01 08:00:00+00:00
9,CRM-1010,Strategy Discussion,Alan Whitfield,Northwind Investments,James Wu,2025-03-20,2026-05-26 10:00:00,Virtual,Microsoft Teams,,Tentative,2025-03-14 17:30:00+00:00
10,CRM-1011,Annual Allocation Review,Elena Marcos,Horizon Wealth Partners,James Wu,2025-03-21,2026-05-26 09:00:00,In-Person,NYC Office,Full-year allocation review. Elena wants to di...,Confirmed,2025-03-07 10:15:00+00:00
11,CRM-1012,Co-Investment Opportunity,Thomas Grant,Granite Point Capital,Sarah Chen,2025-03-21,2026-05-26 14:00:00,Virtual,Zoom,Present co-invest opportunity in Fund VII deal...,Confirmed,2025-03-12 11:00:00+00:00
12,CRM-1013,LP Advisory Committee Prep,NaN,NaN,Sarah Chen,2025-03-24,2026-05-26 10:00:00,Internal,HQ - Boardroom,Prepare materials and talking points for upcom...,Confirmed,2025-03-15 09:00:00+00:00
13,CRM-1014,Quick Check-in,Michael Reeves,Evergreen Capital,James Wu,2025-03-25,2026-05-26 08:30:00,Virtual,NaN,Brief call re: capital call timing for Fund VI...,Confirmed,2025-03-20 14:00:00+00:00
14,CRM-1015,Infrastructure Fund Pitch,Lisa Tran,Atlas Ventures,James Wu,2025-03-26,2026-05-26 10:00:00,In-Person,HQ - Conference Room A,Formal pitch for Infra V. Follow-up from March...,Confirmed,2025-03-16 08:30:00+00:00
15,CRM-1016,ESG Compliance Discussion,Karen White,Redwood Institutional,Sarah Chen,2025-03-27,2026-05-26 13:00:00,Virtual,Microsoft Teams,Karen has ESG reporting requirements for their...,Confirmed,2025-03-18 09:45:00+00:00
16,CRM-1017,Closing Dinner,Multiple,Fund VII Investors,James Wu,2025-03-28,2026-05-26 19:00:00,In-Person,The Palm - DC,Celebratory dinner for Fund VII final close. 1...,Confirmed,2025-03-10 16:00:00+00:00
17,CRM-1018,Follow-up Call,Patricia Langley,Crestview Holdings,Sarah Chen,2025-03-25,2026-05-26 16:30:00,Virtual,NaN,Follow up on DD questions from 3/13 meeting. P...,Confirmed,2025-03-17 10:20:00+00:00
18,CRM-1019,Quarterly Business Review,NaN,NaN,Sarah Chen,2025-04-01,2026-05-26 14:00:00,Internal,HQ - Large Conference Room,"Q1 wrap. Review pipeline, AUM growth, client r...",Confirmed,2025-03-05 12:00:00+00:00
19,CRM-1020,Northwind - Fund VII Interest,Alan Whitfield,Northwind Investments,James Wu,2025-04-02,2026-05-26 11:00:00,In-Person,NYC Office - 30th Floor,Deep dive on Fund VII. Alan indicated potentia...,Tentative,2025-03-21 15:00:00+00:00

In [31]:
df_crm.isna().sum()

crm_id                0
subject               0
client_name           4
client_company        4
relationship_owner    0
meeting_date          0
meeting_time          1
meeting_type          0
location              4
notes                 0
status                0
created_at            0
dtype: int64

In [32]:
df_crm['client_name']=df_crm['client_name'].fillna(df_crm['client_name'].mode()[0])
df_crm

,crm_id,subject,client_name,client_company,relationship_owner,meeting_date,meeting_time,meeting_type,location,notes,status,created_at
0,CRM-1001,Q1 Portfolio Review,David Park,Meridian Capital,Sarah Chen,2025-03-10,2026-05-26 14:00:00,In-Person,HQ - Conference Room B,Review Q1 allocation strategy. David requested...,Completed,2025-02-28 09:15:00+00:00
1,CRM-1002,Portfolio Walkthrough,Mark Johnson,Summit Advisors,Sarah Chen,2025-03-12,2026-05-26 10:00:00,In-Person,NYC Office - 30th Floor,Walk through current portfolio positioning and...,Confirmed,2025-03-01 11:30:00+00:00
2,CRM-1003,Introductory Call,Rachel Torres,Lakeshore Partners,James Wu,2025-03-14,2026-05-26 15:00:00,Virtual,NaN,First touch. Referred by Tom Nakamura at Bridg...,Scheduled,2025-03-10 14:00:00+00:00
3,CRM-1004,Due Diligence Review,Patricia Langley,Crestview Holdings,Sarah Chen,2025-03-13,2026-05-26 14:00:00,In-Person,DC Office - Main Conference Room,DD deep-dive on Fund VII. Legal team joining.,Confirmed,2025-03-05 08:45:00+00:00
4,CRM-1005,Investor Update,Kevin O'Brien,Pinnacle Group,James Wu,2025-03-17,2026-05-26 11:00:00,In-Person,Boston Office,Quarterly update. Kevin may bring CIO.,Confirmed,2025-03-03 16:20:00+00:00
5,CRM-1006,Pipeline Review,Alan Whitfield,NaN,Sarah Chen,2025-03-14,2026-05-26 16:00:00,Internal,HQ - Room 4A,Weekly pipeline review with full team.,Confirmed,2025-01-15 10:00:00+00:00
6,CRM-1007,Follow-up Discussion,David Park,Meridian Capital,Sarah Chen,2025-03-18,NaT,Virtual,NaN,Follow up on fee schedule questions from Q1 re...,Scheduled,2025-03-11 09:30:00+00:00
7,CRM-1008,Lunch Meeting,Lisa Tran,Atlas Ventures,James Wu,03-15/2025,2026-05-26 12:00:00,In-Person,The Capital Grille - Georgetown,Relationship building. Lisa interested in infr...,Confirmed,2025-03-08 13:00:00+00:00
8,CRM-1009,Board Prep Session,Alan Whitfield,NaN,Sarah Chen,2025-03-19,2026-05-26 09:00:00,Internal,HQ - Boardroom,Prep Q1 board materials. CANCELLED — reschedul...,Cancelled,2025-03-01 08:00:00+00:00
9,CRM-1010,Strategy Discussion,Alan Whitfield,Northwind Investments,James Wu,2025-03-20,2026-05-26 10:00:00,Virtual,Microsoft Teams,,Tentative,2025-03-14 17:30:00+00:00
10,CRM-1011,Annual Allocation Review,Elena Marcos,Horizon Wealth Partners,James Wu,2025-03-21,2026-05-26 09:00:00,In-Person,NYC Office,Full-year allocation review. Elena wants to di...,Confirmed,2025-03-07 10:15:00+00:00
11,CRM-1012,Co-Investment Opportunity,Thomas Grant,Granite Point Capital,Sarah Chen,2025-03-21,2026-05-26 14:00:00,Virtual,Zoom,Present co-invest opportunity in Fund VII deal...,Confirmed,2025-03-12 11:00:00+00:00
12,CRM-1013,LP Advisory Committee Prep,Alan Whitfield,NaN,Sarah Chen,2025-03-24,2026-05-26 10:00:00,Internal,HQ - Boardroom,Prepare materials and talking points for upcom...,Confirmed,2025-03-15 09:00:00+00:00
13,CRM-1014,Quick Check-in,Michael Reeves,Evergreen Capital,James Wu,2025-03-25,2026-05-26 08:30:00,Virtual,NaN,Brief call re: capital call timing for Fund VI...,Confirmed,2025-03-20 14:00:00+00:00
14,CRM-1015,Infrastructure Fund Pitch,Lisa Tran,Atlas Ventures,James Wu,2025-03-26,2026-05-26 10:00:00,In-Person,HQ - Conference Room A,Formal pitch for Infra V. Follow-up from March...,Confirmed,2025-03-16 08:30:00+00:00
15,CRM-1016,ESG Compliance Discussion,Karen White,Redwood Institutional,Sarah Chen,2025-03-27,2026-05-26 13:00:00,Virtual,Microsoft Teams,Karen has ESG reporting requirements for their...,Confirmed,2025-03-18 09:45:00+00:00
16,CRM-1017,Closing Dinner,Multiple,Fund VII Investors,James Wu,2025-03-28,2026-05-26 19:00:00,In-Person,The Palm - DC,Celebratory dinner for Fund VII final close. 1...,Confirmed,2025-03-10 16:00:00+00:00
17,CRM-1018,Follow-up Call,Patricia Langley,Crestview Holdings,Sarah Chen,2025-03-25,2026-05-26 16:30:00,Virtual,NaN,Follow up on DD questions from 3/13 meeting. P...,Confirmed,2025-03-17 10:20:00+00:00
18,CRM-1019,Quarterly Business Review,Alan Whitfield,NaN,Sarah Chen,2025-04-01,2026-05-26 14:00:00,Internal,HQ - Large Conference Room,"Q1 wrap. Review pipeline, AUM growth, client r...",Confirmed,2025-03-05 12:00:00+00:00
19,CRM-1020,Northwind - Fund VII Interest,Alan Whitfield,Northwind Investments,James Wu,2025-04-02,2026-05-26 11:00:00,In-Person,NYC Office - 30th Floor,Deep dive on Fund VII. Alan indicated potentia...,Tentative,2025-03-21 15:00:00+00:00

In [33]:
mapping = (
    df_crm.dropna(subset=["client_company"])
      .drop_duplicates(subset=["client_name"])
      .set_index("client_name")["client_company"]
)
mapping

client_name
David Park                 Meridian Capital
Mark Johnson                Summit Advisors
Rachel Torres            Lakeshore Partners
Patricia Langley         Crestview Holdings
Kevin O'Brien                Pinnacle Group
Lisa Tran                    Atlas Ventures
Alan Whitfield        Northwind Investments
Elena Marcos        Horizon Wealth Partners
Thomas Grant          Granite Point Capital
Michael Reeves            Evergreen Capital
Karen White           Redwood Institutional
Multiple                 Fund VII Investors
Name: client_company, dtype: str

In [34]:
df_crm["client_company"] = df_crm["client_company"].fillna(
    df_crm["client_name"].map(mapping)
)
df_crm

,crm_id,subject,client_name,client_company,relationship_owner,meeting_date,meeting_time,meeting_type,location,notes,status,created_at
0,CRM-1001,Q1 Portfolio Review,David Park,Meridian Capital,Sarah Chen,2025-03-10,2026-05-26 14:00:00,In-Person,HQ - Conference Room B,Review Q1 allocation strategy. David requested...,Completed,2025-02-28 09:15:00+00:00
1,CRM-1002,Portfolio Walkthrough,Mark Johnson,Summit Advisors,Sarah Chen,2025-03-12,2026-05-26 10:00:00,In-Person,NYC Office - 30th Floor,Walk through current portfolio positioning and...,Confirmed,2025-03-01 11:30:00+00:00
2,CRM-1003,Introductory Call,Rachel Torres,Lakeshore Partners,James Wu,2025-03-14,2026-05-26 15:00:00,Virtual,NaN,First touch. Referred by Tom Nakamura at Bridg...,Scheduled,2025-03-10 14:00:00+00:00
3,CRM-1004,Due Diligence Review,Patricia Langley,Crestview Holdings,Sarah Chen,2025-03-13,2026-05-26 14:00:00,In-Person,DC Office - Main Conference Room,DD deep-dive on Fund VII. Legal team joining.,Confirmed,2025-03-05 08:45:00+00:00
4,CRM-1005,Investor Update,Kevin O'Brien,Pinnacle Group,James Wu,2025-03-17,2026-05-26 11:00:00,In-Person,Boston Office,Quarterly update. Kevin may bring CIO.,Confirmed,2025-03-03 16:20:00+00:00
5,CRM-1006,Pipeline Review,Alan Whitfield,Northwind Investments,Sarah Chen,2025-03-14,2026-05-26 16:00:00,Internal,HQ - Room 4A,Weekly pipeline review with full team.,Confirmed,2025-01-15 10:00:00+00:00
6,CRM-1007,Follow-up Discussion,David Park,Meridian Capital,Sarah Chen,2025-03-18,NaT,Virtual,NaN,Follow up on fee schedule questions from Q1 re...,Scheduled,2025-03-11 09:30:00+00:00
7,CRM-1008,Lunch Meeting,Lisa Tran,Atlas Ventures,James Wu,03-15/2025,2026-05-26 12:00:00,In-Person,The Capital Grille - Georgetown,Relationship building. Lisa interested in infr...,Confirmed,2025-03-08 13:00:00+00:00
8,CRM-1009,Board Prep Session,Alan Whitfield,Northwind Investments,Sarah Chen,2025-03-19,2026-05-26 09:00:00,Internal,HQ - Boardroom,Prep Q1 board materials. CANCELLED — reschedul...,Cancelled,2025-03-01 08:00:00+00:00
9,CRM-1010,Strategy Discussion,Alan Whitfield,Northwind Investments,James Wu,2025-03-20,2026-05-26 10:00:00,Virtual,Microsoft Teams,,Tentative,2025-03-14 17:30:00+00:00
10,CRM-1011,Annual Allocation Review,Elena Marcos,Horizon Wealth Partners,James Wu,2025-03-21,2026-05-26 09:00:00,In-Person,NYC Office,Full-year allocation review. Elena wants to di...,Confirmed,2025-03-07 10:15:00+00:00
11,CRM-1012,Co-Investment Opportunity,Thomas Grant,Granite Point Capital,Sarah Chen,2025-03-21,2026-05-26 14:00:00,Virtual,Zoom,Present co-invest opportunity in Fund VII deal...,Confirmed,2025-03-12 11:00:00+00:00
12,CRM-1013,LP Advisory Committee Prep,Alan Whitfield,Northwind Investments,Sarah Chen,2025-03-24,2026-05-26 10:00:00,Internal,HQ - Boardroom,Prepare materials and talking points for upcom...,Confirmed,2025-03-15 09:00:00+00:00
13,CRM-1014,Quick Check-in,Michael Reeves,Evergreen Capital,James Wu,2025-03-25,2026-05-26 08:30:00,Virtual,NaN,Brief call re: capital call timing for Fund VI...,Confirmed,2025-03-20 14:00:00+00:00
14,CRM-1015,Infrastructure Fund Pitch,Lisa Tran,Atlas Ventures,James Wu,2025-03-26,2026-05-26 10:00:00,In-Person,HQ - Conference Room A,Formal pitch for Infra V. Follow-up from March...,Confirmed,2025-03-16 08:30:00+00:00
15,CRM-1016,ESG Compliance Discussion,Karen White,Redwood Institutional,Sarah Chen,2025-03-27,2026-05-26 13:00:00,Virtual,Microsoft Teams,Karen has ESG reporting requirements for their...,Confirmed,2025-03-18 09:45:00+00:00
16,CRM-1017,Closing Dinner,Multiple,Fund VII Investors,James Wu,2025-03-28,2026-05-26 19:00:00,In-Person,The Palm - DC,Celebratory dinner for Fund VII final close. 1...,Confirmed,2025-03-10 16:00:00+00:00
17,CRM-1018,Follow-up Call,Patricia Langley,Crestview Holdings,Sarah Chen,2025-03-25,2026-05-26 16:30:00,Virtual,NaN,Follow up on DD questions from 3/13 meeting. P...,Confirmed,2025-03-17 10:20:00+00:00
18,CRM-1019,Quarterly Business Review,Alan Whitfield,Northwind Investments,Sarah Chen,2025-04-01,2026-05-26 14:00:00,Internal,HQ - Large Conference Room,"Q1 wrap. Review pipeline, AUM growth, client r...",Confirmed,2025-03-05 12:00:00+00:00
19,CRM-1020,Northwind - Fund VII Interest,Alan Whitfield,Northwind Investments,James Wu,2025-04-02,2026-05-26 11:00:00,In-Person,NYC Office - 30th Floor,Deep dive on Fund VII. Alan indicated potentia...,Tentative,2025-03-21 15:00:00+00:00

In [35]:
df_crm.isna().sum()

crm_id                0
subject               0
client_name           0
client_company        0
relationship_owner    0
meeting_date          0
meeting_time          1
meeting_type          0
location              4
notes                 0
status                0
created_at            0
dtype: int64

In [36]:
mapping = (
    df_crm.dropna(subset=["location"])
      .drop_duplicates(subset=["meeting_type"])
      .set_index("meeting_type")["location"]
)
mapping

meeting_type
In-Person    HQ - Conference Room B
Internal               HQ - Room 4A
Virtual             Microsoft Teams
Name: location, dtype: str

In [37]:
df_crm["location"] = df_crm["location"].fillna(
    df_crm["meeting_type"].map(mapping)
)
df_crm

,crm_id,subject,client_name,client_company,relationship_owner,meeting_date,meeting_time,meeting_type,location,notes,status,created_at
0,CRM-1001,Q1 Portfolio Review,David Park,Meridian Capital,Sarah Chen,2025-03-10,2026-05-26 14:00:00,In-Person,HQ - Conference Room B,Review Q1 allocation strategy. David requested...,Completed,2025-02-28 09:15:00+00:00
1,CRM-1002,Portfolio Walkthrough,Mark Johnson,Summit Advisors,Sarah Chen,2025-03-12,2026-05-26 10:00:00,In-Person,NYC Office - 30th Floor,Walk through current portfolio positioning and...,Confirmed,2025-03-01 11:30:00+00:00
2,CRM-1003,Introductory Call,Rachel Torres,Lakeshore Partners,James Wu,2025-03-14,2026-05-26 15:00:00,Virtual,Microsoft Teams,First touch. Referred by Tom Nakamura at Bridg...,Scheduled,2025-03-10 14:00:00+00:00
3,CRM-1004,Due Diligence Review,Patricia Langley,Crestview Holdings,Sarah Chen,2025-03-13,2026-05-26 14:00:00,In-Person,DC Office - Main Conference Room,DD deep-dive on Fund VII. Legal team joining.,Confirmed,2025-03-05 08:45:00+00:00
4,CRM-1005,Investor Update,Kevin O'Brien,Pinnacle Group,James Wu,2025-03-17,2026-05-26 11:00:00,In-Person,Boston Office,Quarterly update. Kevin may bring CIO.,Confirmed,2025-03-03 16:20:00+00:00
5,CRM-1006,Pipeline Review,Alan Whitfield,Northwind Investments,Sarah Chen,2025-03-14,2026-05-26 16:00:00,Internal,HQ - Room 4A,Weekly pipeline review with full team.,Confirmed,2025-01-15 10:00:00+00:00
6,CRM-1007,Follow-up Discussion,David Park,Meridian Capital,Sarah Chen,2025-03-18,NaT,Virtual,Microsoft Teams,Follow up on fee schedule questions from Q1 re...,Scheduled,2025-03-11 09:30:00+00:00
7,CRM-1008,Lunch Meeting,Lisa Tran,Atlas Ventures,James Wu,03-15/2025,2026-05-26 12:00:00,In-Person,The Capital Grille - Georgetown,Relationship building. Lisa interested in infr...,Confirmed,2025-03-08 13:00:00+00:00
8,CRM-1009,Board Prep Session,Alan Whitfield,Northwind Investments,Sarah Chen,2025-03-19,2026-05-26 09:00:00,Internal,HQ - Boardroom,Prep Q1 board materials. CANCELLED — reschedul...,Cancelled,2025-03-01 08:00:00+00:00
9,CRM-1010,Strategy Discussion,Alan Whitfield,Northwind Investments,James Wu,2025-03-20,2026-05-26 10:00:00,Virtual,Microsoft Teams,,Tentative,2025-03-14 17:30:00+00:00
10,CRM-1011,Annual Allocation Review,Elena Marcos,Horizon Wealth Partners,James Wu,2025-03-21,2026-05-26 09:00:00,In-Person,NYC Office,Full-year allocation review. Elena wants to di...,Confirmed,2025-03-07 10:15:00+00:00
11,CRM-1012,Co-Investment Opportunity,Thomas Grant,Granite Point Capital,Sarah Chen,2025-03-21,2026-05-26 14:00:00,Virtual,Zoom,Present co-invest opportunity in Fund VII deal...,Confirmed,2025-03-12 11:00:00+00:00
12,CRM-1013,LP Advisory Committee Prep,Alan Whitfield,Northwind Investments,Sarah Chen,2025-03-24,2026-05-26 10:00:00,Internal,HQ - Boardroom,Prepare materials and talking points for upcom...,Confirmed,2025-03-15 09:00:00+00:00
13,CRM-1014,Quick Check-in,Michael Reeves,Evergreen Capital,James Wu,2025-03-25,2026-05-26 08:30:00,Virtual,Microsoft Teams,Brief call re: capital call timing for Fund VI...,Confirmed,2025-03-20 14:00:00+00:00
14,CRM-1015,Infrastructure Fund Pitch,Lisa Tran,Atlas Ventures,James Wu,2025-03-26,2026-05-26 10:00:00,In-Person,HQ - Conference Room A,Formal pitch for Infra V. Follow-up from March...,Confirmed,2025-03-16 08:30:00+00:00
15,CRM-1016,ESG Compliance Discussion,Karen White,Redwood Institutional,Sarah Chen,2025-03-27,2026-05-26 13:00:00,Virtual,Microsoft Teams,Karen has ESG reporting requirements for their...,Confirmed,2025-03-18 09:45:00+00:00
16,CRM-1017,Closing Dinner,Multiple,Fund VII Investors,James Wu,2025-03-28,2026-05-26 19:00:00,In-Person,The Palm - DC,Celebratory dinner for Fund VII final close. 1...,Confirmed,2025-03-10 16:00:00+00:00
17,CRM-1018,Follow-up Call,Patricia Langley,Crestview Holdings,Sarah Chen,2025-03-25,2026-05-26 16:30:00,Virtual,Microsoft Teams,Follow up on DD questions from 3/13 meeting. P...,Confirmed,2025-03-17 10:20:00+00:00
18,CRM-1019,Quarterly Business Review,Alan Whitfield,Northwind Investments,Sarah Chen,2025-04-01,2026-05-26 14:00:00,Internal,HQ - Large Conference Room,"Q1 wrap. Review pipeline, AUM growth, client r...",Confirmed,2025-03-05 12:00:00+00:00
19,CRM-1020,Northwind - Fund VII Interest,Alan Whitfield,Northwind Investments,James Wu,2025-04-02,2026-05-26 11:00:00,In-Person,NYC Office - 30th Floor,Deep dive on Fund VII. Alan indicated potentia...,Tentative,2025-03-21 15:00:00+00:00

In [38]:
df_crm.isna().sum()

crm_id                0
subject               0
client_name           0
client_company        0
relationship_owner    0
meeting_date          0
meeting_time          1
meeting_type          0
location              0
notes                 0
status                0
created_at            0
dtype: int64

In [39]:
df_cal.isna().sum()

event_id        0
title           0
organizer       0
attendees       0
start_time      0
end_time        0
location        2
description     1
is_recurring    0
status          0
created_at      0
dtype: int64

In [40]:
df_cal.describe()

,event_id,title,organizer,attendees,start_time,end_time,location,description,is_recurring,status,created_at
count,22,22,22,22,22,22,20,21,22,22,22
unique,22,21,3,18,22,22,16,20,2,2,NaN
top,CAL-A1,Weekly Team Sync,sarah.chen@firma.com,"[sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-10T14:00:00,2025-03-10T15:30:00,Virtual - Microsoft Teams,Standing weekly sync.,False,confirmed,NaN
freq,1,2,13,3,1,1,2,2,19,21,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-03-01 21:02:57.272727+00:00
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-01-06 08:00:00+00:00
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-03-01 03:26:15+00:00
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-03-08 13:30:00+00:00
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-03-14 07:47:30+00:00
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-03-20 12:00:00+00:00

In [41]:
df_cal[df_cal.isna().any(axis=1)]

,event_id,title,organizer,attendees,start_time,end_time,location,description,is_recurring,status,created_at
10,CAL-A11,Client Reception,priya.sharma@firma.com,[],2025-03-14T18:00:00,2025-03-14T20:00,NaN,NaN,False,tentative,2025-03-13 22:10:00+00:00
14,CAL-A15,Michael Reeves - Quick Sync,james.wu@firma.com,"[james.wu@firma.com, michael.reeves@evergreenc...",2025-03-25T08:30:00,2025-03-25T08:45:00,NaN,Capital call timing discussion.,False,confirmed,2025-03-19 17:00:00+00:00

In [42]:
df_cal['location']=df_cal['location'].fillna(df_cal['location'].mode()[0])
df_cal

,event_id,title,organizer,attendees,start_time,end_time,location,description,is_recurring,status,created_at
0,CAL-A1,Q1 Portfolio Review - Meridian Capital,sarah.chen@firma.com,"[sarah.chen@firma.com, david.park@meridiancap....",2025-03-10T14:00:00,2025-03-10T15:30:00,Conference Room B,Quarterly review of portfolio allocation and p...,False,confirmed,2025-02-27 10:00:00+00:00
1,CAL-A2,Summit Advisors - Portfolio Discussion,sarah.chen@firma.com,"[sarah.chen@firma.com, mark.johnson@summitadv....",2025-03-12T10:00:00,2025-03-12T11:00:00,Zoom - https://zoom.us/j/98765432100,Portfolio walkthrough with Summit team.,False,confirmed,2025-02-28 15:45:00+00:00
2,CAL-A3,Weekly Team Sync,sarah.chen@firma.com,"[sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-11T09:00:00,2025-03-11T09:30:00,Virtual - Microsoft Teams,Standing weekly sync.,True,confirmed,2025-01-06 08:00:00+00:00
3,CAL-A4,Crestview Holdings - DD Meeting,sarah.chen@firma.com,"[sarah.chen@firma.com, patricia.langley@crestv...",2025-03-13T19:00:00Z,2025-03-13T20:30:00Z,DC Office - Main Conference Room,Due diligence deep-dive. Fund VII materials pr...,False,confirmed,2025-03-04 12:00:00+00:00
4,CAL-A5,Investor Update - Pinnacle,james.wu@firma.com,"[james.wu@firma.com, kevin.obrien@pinnaclegp.com]",2025-03-17T11:00:00,2025-03-17T12:00:00,Boston Office - Room 301,Quarterly investor update for Pinnacle Group.,False,confirmed,2025-03-02 14:30:00+00:00
5,CAL-A6,Pinnacle Group - Q1 Update,james.wu@firma.com,"[james.wu@firma.com, kevin.obrien@pinnaclegp.c...",2025-03-17T11:30:00,2025-03-17T12:30:00,Boston Office,Q1 update with Pinnacle Group. Sandra Mills (C...,False,confirmed,2025-03-10 09:15:00+00:00
6,CAL-A7,Internal Pipeline Review,sarah.chen@firma.com,"[sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-14T16:00:00,2025-03-14T17:00:00,HQ - Room 4A,Review active pipeline and upcoming client mee...,True,confirmed,2025-01-15 10:05:00+00:00
7,CAL-A8,Meridian Capital - Follow-up,sarah.chen@firma.com,"[sarah.chen@firma.com, david.park@meridiancap....",2025-03-18T15:00:00,2025-03-18T15:30:00,Zoom,Follow-up re: fee schedule and allocation chan...,False,confirmed,2025-03-11 09:45:00+00:00
8,CAL-A9,Atlas Ventures Lunch,james.wu@firma.com,"[james.wu@firma.com, lisa.tran@atlasvc.com]",2025-03-15T12:00:00,2025-03-15T13:30:00,The Capital Grille - Georgetown,Lunch with Lisa Tran. Exploring infrastructure...,False,confirmed,2025-03-07 16:00:00+00:00
9,CAL-A10,Board Prep - Q1 Materials Review,sarah.chen@firma.com,"[sarah.chen@firma.com, james.wu@firma.com, mic...",2025-03-19T09:00:00,2025-03-19T10:30:00,HQ - Boardroom,Review and finalize Q1 board presentation mate...,False,confirmed,2025-02-28 11:00:00+00:00
10,CAL-A11,Client Reception,priya.sharma@firma.com,[],2025-03-14T18:00:00,2025-03-14T20:00,HQ - Boardroom,NaN,False,tentative,2025-03-13 22:10:00+00:00
11,CAL-A12,Horizon Wealth - Year-End Review,james.wu@firma.com,"[james.wu@firma.com, elena.marcos@horizonwp.com]",2025-03-21T09:00:00,2025-03-21T10:30:00,NYC Office - 12th Floor,Annual review of allocation strategy and alter...,False,confirmed,2025-03-06 14:20:00+00:00
12,CAL-A13,Granite Point - Co-Invest Discussion,sarah.chen@firma.com,"[sarah.chen@firma.com, thomas.grant@granitepoi...",2025-03-21T14:00:00,2025-03-21T15:00:00,Zoom - https://zoom.us/j/11223344,Co-investment opportunity walkthrough for Fund...,False,confirmed,2025-03-11 16:30:00+00:00
13,CAL-A14,LPAC Prep Working Session,priya.sharma@firma.com,"[sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-24T10:00:00,2025-03-24T12:00:00,HQ - Boardroom,Prep session for LP Advisory Committee meeting...,False,confirmed,2025-03-14 11:00:00+00:00
14,CAL-A15,Michael Reeves - Quick Sync,james.wu@firma.com,"[james.wu@firma.com, michael.reeves@evergreenc...",2025-03-25T08:30:00,2025-03-25T08:45:00,HQ - Boardroom,Capital call timing discussion.,False,confirmed,2025-03-19 17:00:00+00:00
15,CAL-A16,Atlas Ventures - Infrastructure Deep Dive,james.wu@firma.com,"[james.wu@firma.com, lisa.tran@atlasvc.com, ra...",2025-03-26T10:00:00,2025-03-26T11:30:00,Conference Room A,Formal infrastructure fund presentation. Raj P...,False,confirmed,2025-03-15 10:00:00+00:00
16,CAL-A17,ESG + Compliance Review,sarah.chen@firma.com,"[sarah.chen@firma.com, karen.white@redwoodinst...",2025-03-27T15:00:00,2025-03-27T16:00:00,Microsoft Teams,Walk through ESG reporting framework and compl...,False,confirmed,2025-03-20 08:30:00+00:00
17,CAL-A18,Weekly Team Sync,sarah.chen@firma.com,"[sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-18T09:00:00,2025-03-18T09:30:00,Virtual - Microsoft Teams,Standing weekly sync.,True,confirmed,2025-01-06 08:00:00+00:00
18,CAL-A19,Fund VII Roadshow Prep,sarah.chen@firma.com,"[sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-28T14:00:00,2025-03-28T16:00:00,HQ - Room 4A,Finalize roadshow materials and talking points...,False,confirmed,2025-03-20 12:00:00+00:00
19,CAL-A20,Fund VII Closing Dinner,james.wu@firma.com,"[james.wu@firma.com, sarah.chen@firma.com, kev...",2025-03-28T19:00:00,2025-03-28T21:30:00,The Palm Restaurant,Celebratory dinner for Fund VII final close.,False,confirmed,2025-03-09 11:00:00+00:00
20,CAL-A21,Crestview Follow-up Call,sarah.chen@firma.com,"[sarah.chen@firma.com, patricia.langley@crestv...",2025-03-25T16:30:00,2025-03-25T17:00:00,Zoom,Follow-up on due diligence questions. Side let...,False,confirmed,2025-03-16 14:45:00+00:00
21,CAL-A22,QBR - Q1 Wrap,sarah.chen@firma.com,"[sarah.chen@firma.com, james.wu@firma.com, pri...",2025-04-01T14:00:00,2025-04-01T16:00:00,HQ - Large Conference Room,"Q1 quarterly business review. Pipeline, AUM, r...",False,confirmed,2025-03-04 09:30:00+00:00

In [43]:
df_cal.isna().sum()

event_id        0
title           0
organizer       0
attendees       0
start_time      0
end_time        0
location        0
description     1
is_recurring    0
status          0
created_at      0
dtype: int64

In [44]:
df_cal = df_cal[~df_cal["title"].str.contains("Client Reception", case=False, na=False)]
df_cal

,event_id,title,organizer,attendees,start_time,end_time,location,description,is_recurring,status,created_at
0,CAL-A1,Q1 Portfolio Review - Meridian Capital,sarah.chen@firma.com,"[sarah.chen@firma.com, david.park@meridiancap....",2025-03-10T14:00:00,2025-03-10T15:30:00,Conference Room B,Quarterly review of portfolio allocation and p...,False,confirmed,2025-02-27 10:00:00+00:00
1,CAL-A2,Summit Advisors - Portfolio Discussion,sarah.chen@firma.com,"[sarah.chen@firma.com, mark.johnson@summitadv....",2025-03-12T10:00:00,2025-03-12T11:00:00,Zoom - https://zoom.us/j/98765432100,Portfolio walkthrough with Summit team.,False,confirmed,2025-02-28 15:45:00+00:00
2,CAL-A3,Weekly Team Sync,sarah.chen@firma.com,"[sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-11T09:00:00,2025-03-11T09:30:00,Virtual - Microsoft Teams,Standing weekly sync.,True,confirmed,2025-01-06 08:00:00+00:00
3,CAL-A4,Crestview Holdings - DD Meeting,sarah.chen@firma.com,"[sarah.chen@firma.com, patricia.langley@crestv...",2025-03-13T19:00:00Z,2025-03-13T20:30:00Z,DC Office - Main Conference Room,Due diligence deep-dive. Fund VII materials pr...,False,confirmed,2025-03-04 12:00:00+00:00
4,CAL-A5,Investor Update - Pinnacle,james.wu@firma.com,"[james.wu@firma.com, kevin.obrien@pinnaclegp.com]",2025-03-17T11:00:00,2025-03-17T12:00:00,Boston Office - Room 301,Quarterly investor update for Pinnacle Group.,False,confirmed,2025-03-02 14:30:00+00:00
5,CAL-A6,Pinnacle Group - Q1 Update,james.wu@firma.com,"[james.wu@firma.com, kevin.obrien@pinnaclegp.c...",2025-03-17T11:30:00,2025-03-17T12:30:00,Boston Office,Q1 update with Pinnacle Group. Sandra Mills (C...,False,confirmed,2025-03-10 09:15:00+00:00
6,CAL-A7,Internal Pipeline Review,sarah.chen@firma.com,"[sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-14T16:00:00,2025-03-14T17:00:00,HQ - Room 4A,Review active pipeline and upcoming client mee...,True,confirmed,2025-01-15 10:05:00+00:00
7,CAL-A8,Meridian Capital - Follow-up,sarah.chen@firma.com,"[sarah.chen@firma.com, david.park@meridiancap....",2025-03-18T15:00:00,2025-03-18T15:30:00,Zoom,Follow-up re: fee schedule and allocation chan...,False,confirmed,2025-03-11 09:45:00+00:00
8,CAL-A9,Atlas Ventures Lunch,james.wu@firma.com,"[james.wu@firma.com, lisa.tran@atlasvc.com]",2025-03-15T12:00:00,2025-03-15T13:30:00,The Capital Grille - Georgetown,Lunch with Lisa Tran. Exploring infrastructure...,False,confirmed,2025-03-07 16:00:00+00:00
9,CAL-A10,Board Prep - Q1 Materials Review,sarah.chen@firma.com,"[sarah.chen@firma.com, james.wu@firma.com, mic...",2025-03-19T09:00:00,2025-03-19T10:30:00,HQ - Boardroom,Review and finalize Q1 board presentation mate...,False,confirmed,2025-02-28 11:00:00+00:00
11,CAL-A12,Horizon Wealth - Year-End Review,james.wu@firma.com,"[james.wu@firma.com, elena.marcos@horizonwp.com]",2025-03-21T09:00:00,2025-03-21T10:30:00,NYC Office - 12th Floor,Annual review of allocation strategy and alter...,False,confirmed,2025-03-06 14:20:00+00:00
12,CAL-A13,Granite Point - Co-Invest Discussion,sarah.chen@firma.com,"[sarah.chen@firma.com, thomas.grant@granitepoi...",2025-03-21T14:00:00,2025-03-21T15:00:00,Zoom - https://zoom.us/j/11223344,Co-investment opportunity walkthrough for Fund...,False,confirmed,2025-03-11 16:30:00+00:00
13,CAL-A14,LPAC Prep Working Session,priya.sharma@firma.com,"[sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-24T10:00:00,2025-03-24T12:00:00,HQ - Boardroom,Prep session for LP Advisory Committee meeting...,False,confirmed,2025-03-14 11:00:00+00:00
14,CAL-A15,Michael Reeves - Quick Sync,james.wu@firma.com,"[james.wu@firma.com, michael.reeves@evergreenc...",2025-03-25T08:30:00,2025-03-25T08:45:00,HQ - Boardroom,Capital call timing discussion.,False,confirmed,2025-03-19 17:00:00+00:00
15,CAL-A16,Atlas Ventures - Infrastructure Deep Dive,james.wu@firma.com,"[james.wu@firma.com, lisa.tran@atlasvc.com, ra...",2025-03-26T10:00:00,2025-03-26T11:30:00,Conference Room A,Formal infrastructure fund presentation. Raj P...,False,confirmed,2025-03-15 10:00:00+00:00
16,CAL-A17,ESG + Compliance Review,sarah.chen@firma.com,"[sarah.chen@firma.com, karen.white@redwoodinst...",2025-03-27T15:00:00,2025-03-27T16:00:00,Microsoft Teams,Walk through ESG reporting framework and compl...,False,confirmed,2025-03-20 08:30:00+00:00
17,CAL-A18,Weekly Team Sync,sarah.chen@firma.com,"[sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-18T09:00:00,2025-03-18T09:30:00,Virtual - Microsoft Teams,Standing weekly sync.,True,confirmed,2025-01-06 08:00:00+00:00
18,CAL-A19,Fund VII Roadshow Prep,sarah.chen@firma.com,"[sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-28T14:00:00,2025-03-28T16:00:00,HQ - Room 4A,Finalize roadshow materials and talking points...,False,confirmed,2025-03-20 12:00:00+00:00
19,CAL-A20,Fund VII Closing Dinner,james.wu@firma.com,"[james.wu@firma.com, sarah.chen@firma.com, kev...",2025-03-28T19:00:00,2025-03-28T21:30:00,The Palm Restaurant,Celebratory dinner for Fund VII final close.,False,confirmed,2025-03-09 11:00:00+00:00
20,CAL-A21,Crestview Follow-up Call,sarah.chen@firma.com,"[sarah.chen@firma.com, patricia.langley@crestv...",2025-03-25T16:30:00,2025-03-25T17:00:00,Zoom,Follow-up on due diligence questions. Side let...,False,confirmed,2025-03-16 14:45:00+00:00
21,CAL-A22,QBR - Q1 Wrap,sarah.chen@firma.com,"[sarah.chen@firma.com, james.wu@firma.com, pri...",2025-04-01T14:00:00,2025-04-01T16:00:00,HQ - Large Conference Room,"Q1 quarterly business review. Pipeline, AUM, r...",False,confirmed,2025-03-04 09:30:00+00:00

In [45]:
df_cal.isna().sum()

event_id        0
title           0
organizer       0
attendees       0
start_time      0
end_time        0
location        0
description     0
is_recurring    0
status          0
created_at      0
dtype: int64

In [46]:
df_crm.columns

Index(['crm_id', 'subject', 'client_name', 'client_company',
       'relationship_owner', 'meeting_date', 'meeting_time', 'meeting_type',
       'location', 'notes', 'status', 'created_at'],
      dtype='str')

In [47]:
duplicates = df_crm[df_crm.duplicated(subset=['subject', 'client_name', 'client_company',
       'relationship_owner', 'meeting_date', 'meeting_time', 'meeting_type',
       'location', 'notes', 'status', 'created_at'])]
duplicates

Empty DataFrame
Columns: [crm_id, subject, client_name, client_company, relationship_owner, meeting_date, meeting_time, meeting_type, location, notes, status, created_at]
Index: []

In [48]:
df_cal.columns

Index(['event_id', 'title', 'organizer', 'attendees', 'start_time', 'end_time',
       'location', 'description', 'is_recurring', 'status', 'created_at'],
      dtype='str')

In [49]:
df_cal['attendees']=df_cal['attendees'].apply(tuple)

In [50]:
df_cal

,event_id,title,organizer,attendees,start_time,end_time,location,description,is_recurring,status,created_at
0,CAL-A1,Q1 Portfolio Review - Meridian Capital,sarah.chen@firma.com,"(sarah.chen@firma.com, david.park@meridiancap....",2025-03-10T14:00:00,2025-03-10T15:30:00,Conference Room B,Quarterly review of portfolio allocation and p...,False,confirmed,2025-02-27 10:00:00+00:00
1,CAL-A2,Summit Advisors - Portfolio Discussion,sarah.chen@firma.com,"(sarah.chen@firma.com, mark.johnson@summitadv....",2025-03-12T10:00:00,2025-03-12T11:00:00,Zoom - https://zoom.us/j/98765432100,Portfolio walkthrough with Summit team.,False,confirmed,2025-02-28 15:45:00+00:00
2,CAL-A3,Weekly Team Sync,sarah.chen@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-11T09:00:00,2025-03-11T09:30:00,Virtual - Microsoft Teams,Standing weekly sync.,True,confirmed,2025-01-06 08:00:00+00:00
3,CAL-A4,Crestview Holdings - DD Meeting,sarah.chen@firma.com,"(sarah.chen@firma.com, patricia.langley@crestv...",2025-03-13T19:00:00Z,2025-03-13T20:30:00Z,DC Office - Main Conference Room,Due diligence deep-dive. Fund VII materials pr...,False,confirmed,2025-03-04 12:00:00+00:00
4,CAL-A5,Investor Update - Pinnacle,james.wu@firma.com,"(james.wu@firma.com, kevin.obrien@pinnaclegp.com)",2025-03-17T11:00:00,2025-03-17T12:00:00,Boston Office - Room 301,Quarterly investor update for Pinnacle Group.,False,confirmed,2025-03-02 14:30:00+00:00
5,CAL-A6,Pinnacle Group - Q1 Update,james.wu@firma.com,"(james.wu@firma.com, kevin.obrien@pinnaclegp.c...",2025-03-17T11:30:00,2025-03-17T12:30:00,Boston Office,Q1 update with Pinnacle Group. Sandra Mills (C...,False,confirmed,2025-03-10 09:15:00+00:00
6,CAL-A7,Internal Pipeline Review,sarah.chen@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-14T16:00:00,2025-03-14T17:00:00,HQ - Room 4A,Review active pipeline and upcoming client mee...,True,confirmed,2025-01-15 10:05:00+00:00
7,CAL-A8,Meridian Capital - Follow-up,sarah.chen@firma.com,"(sarah.chen@firma.com, david.park@meridiancap....",2025-03-18T15:00:00,2025-03-18T15:30:00,Zoom,Follow-up re: fee schedule and allocation chan...,False,confirmed,2025-03-11 09:45:00+00:00
8,CAL-A9,Atlas Ventures Lunch,james.wu@firma.com,"(james.wu@firma.com, lisa.tran@atlasvc.com)",2025-03-15T12:00:00,2025-03-15T13:30:00,The Capital Grille - Georgetown,Lunch with Lisa Tran. Exploring infrastructure...,False,confirmed,2025-03-07 16:00:00+00:00
9,CAL-A10,Board Prep - Q1 Materials Review,sarah.chen@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, mic...",2025-03-19T09:00:00,2025-03-19T10:30:00,HQ - Boardroom,Review and finalize Q1 board presentation mate...,False,confirmed,2025-02-28 11:00:00+00:00
11,CAL-A12,Horizon Wealth - Year-End Review,james.wu@firma.com,"(james.wu@firma.com, elena.marcos@horizonwp.com)",2025-03-21T09:00:00,2025-03-21T10:30:00,NYC Office - 12th Floor,Annual review of allocation strategy and alter...,False,confirmed,2025-03-06 14:20:00+00:00
12,CAL-A13,Granite Point - Co-Invest Discussion,sarah.chen@firma.com,"(sarah.chen@firma.com, thomas.grant@granitepoi...",2025-03-21T14:00:00,2025-03-21T15:00:00,Zoom - https://zoom.us/j/11223344,Co-investment opportunity walkthrough for Fund...,False,confirmed,2025-03-11 16:30:00+00:00
13,CAL-A14,LPAC Prep Working Session,priya.sharma@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-24T10:00:00,2025-03-24T12:00:00,HQ - Boardroom,Prep session for LP Advisory Committee meeting...,False,confirmed,2025-03-14 11:00:00+00:00
14,CAL-A15,Michael Reeves - Quick Sync,james.wu@firma.com,"(james.wu@firma.com, michael.reeves@evergreenc...",2025-03-25T08:30:00,2025-03-25T08:45:00,HQ - Boardroom,Capital call timing discussion.,False,confirmed,2025-03-19 17:00:00+00:00
15,CAL-A16,Atlas Ventures - Infrastructure Deep Dive,james.wu@firma.com,"(james.wu@firma.com, lisa.tran@atlasvc.com, ra...",2025-03-26T10:00:00,2025-03-26T11:30:00,Conference Room A,Formal infrastructure fund presentation. Raj P...,False,confirmed,2025-03-15 10:00:00+00:00
16,CAL-A17,ESG + Compliance Review,sarah.chen@firma.com,"(sarah.chen@firma.com, karen.white@redwoodinst...",2025-03-27T15:00:00,2025-03-27T16:00:00,Microsoft Teams,Walk through ESG reporting framework and compl...,False,confirmed,2025-03-20 08:30:00+00:00
17,CAL-A18,Weekly Team Sync,sarah.chen@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-18T09:00:00,2025-03-18T09:30:00,Virtual - Microsoft Teams,Standing weekly sync.,True,confirmed,2025-01-06 08:00:00+00:00
18,CAL-A19,Fund VII Roadshow Prep,sarah.chen@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-28T14:00:00,2025-03-28T16:00:00,HQ - Room 4A,Finalize roadshow materials and talking points...,False,confirmed,2025-03-20 12:00:00+00:00
19,CAL-A20,Fund VII Closing Dinner,james.wu@firma.com,"(james.wu@firma.com, sarah.chen@firma.com, kev...",2025-03-28T19:00:00,2025-03-28T21:30:00,The Palm Restaurant,Celebratory dinner for Fund VII final close.,False,confirmed,2025-03-09 11:00:00+00:00
20,CAL-A21,Crestview Follow-up Call,sarah.chen@firma.com,"(sarah.chen@firma.com, patricia.langley@crestv...",2025-03-25T16:30:00,2025-03-25T17:00:00,Zoom,Follow-up on due diligence questions. Side let...,False,confirmed,2025-03-16 14:45:00+00:00
21,CAL-A22,QBR - Q1 Wrap,sarah.chen@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, pri...",2025-04-01T14:00:00,2025-04-01T16:00:00,HQ - Large Conference Room,"Q1 quarterly business review. Pipeline, AUM, r...",False,confirmed,2025-03-04 09:30:00+00:00

In [51]:
duplicates = df_cal[df_cal.duplicated(subset=['title', 'organizer', 'attendees', 'start_time', 'end_time',
       'location', 'description', 'is_recurring', 'status', 'created_at'])]
duplicates

Empty DataFrame
Columns: [event_id, title, organizer, attendees, start_time, end_time, location, description, is_recurring, status, created_at]
Index: []

In [52]:
df_crm['meeting_date'] = df_crm['meeting_date'].apply(
    lambda x: x.replace('//', '-') if '//' in x else x
)

In [53]:
df_crm['subject_new']=df_crm['subject']+'-'+df_crm['client_company']

df_crm

,crm_id,subject,client_name,client_company,relationship_owner,meeting_date,meeting_time,meeting_type,location,notes,status,created_at,subject_new
0,CRM-1001,Q1 Portfolio Review,David Park,Meridian Capital,Sarah Chen,2025-03-10,2026-05-26 14:00:00,In-Person,HQ - Conference Room B,Review Q1 allocation strategy. David requested...,Completed,2025-02-28 09:15:00+00:00,Q1 Portfolio Review-Meridian Capital
1,CRM-1002,Portfolio Walkthrough,Mark Johnson,Summit Advisors,Sarah Chen,2025-03-12,2026-05-26 10:00:00,In-Person,NYC Office - 30th Floor,Walk through current portfolio positioning and...,Confirmed,2025-03-01 11:30:00+00:00,Portfolio Walkthrough-Summit Advisors
2,CRM-1003,Introductory Call,Rachel Torres,Lakeshore Partners,James Wu,2025-03-14,2026-05-26 15:00:00,Virtual,Microsoft Teams,First touch. Referred by Tom Nakamura at Bridg...,Scheduled,2025-03-10 14:00:00+00:00,Introductory Call-Lakeshore Partners
3,CRM-1004,Due Diligence Review,Patricia Langley,Crestview Holdings,Sarah Chen,2025-03-13,2026-05-26 14:00:00,In-Person,DC Office - Main Conference Room,DD deep-dive on Fund VII. Legal team joining.,Confirmed,2025-03-05 08:45:00+00:00,Due Diligence Review-Crestview Holdings
4,CRM-1005,Investor Update,Kevin O'Brien,Pinnacle Group,James Wu,2025-03-17,2026-05-26 11:00:00,In-Person,Boston Office,Quarterly update. Kevin may bring CIO.,Confirmed,2025-03-03 16:20:00+00:00,Investor Update-Pinnacle Group
5,CRM-1006,Pipeline Review,Alan Whitfield,Northwind Investments,Sarah Chen,2025-03-14,2026-05-26 16:00:00,Internal,HQ - Room 4A,Weekly pipeline review with full team.,Confirmed,2025-01-15 10:00:00+00:00,Pipeline Review-Northwind Investments
6,CRM-1007,Follow-up Discussion,David Park,Meridian Capital,Sarah Chen,2025-03-18,NaT,Virtual,Microsoft Teams,Follow up on fee schedule questions from Q1 re...,Scheduled,2025-03-11 09:30:00+00:00,Follow-up Discussion-Meridian Capital
7,CRM-1008,Lunch Meeting,Lisa Tran,Atlas Ventures,James Wu,03-15/2025,2026-05-26 12:00:00,In-Person,The Capital Grille - Georgetown,Relationship building. Lisa interested in infr...,Confirmed,2025-03-08 13:00:00+00:00,Lunch Meeting-Atlas Ventures
8,CRM-1009,Board Prep Session,Alan Whitfield,Northwind Investments,Sarah Chen,2025-03-19,2026-05-26 09:00:00,Internal,HQ - Boardroom,Prep Q1 board materials. CANCELLED — reschedul...,Cancelled,2025-03-01 08:00:00+00:00,Board Prep Session-Northwind Investments
9,CRM-1010,Strategy Discussion,Alan Whitfield,Northwind Investments,James Wu,2025-03-20,2026-05-26 10:00:00,Virtual,Microsoft Teams,,Tentative,2025-03-14 17:30:00+00:00,Strategy Discussion-Northwind Investments
10,CRM-1011,Annual Allocation Review,Elena Marcos,Horizon Wealth Partners,James Wu,2025-03-21,2026-05-26 09:00:00,In-Person,NYC Office,Full-year allocation review. Elena wants to di...,Confirmed,2025-03-07 10:15:00+00:00,Annual Allocation Review-Horizon Wealth Partners
11,CRM-1012,Co-Investment Opportunity,Thomas Grant,Granite Point Capital,Sarah Chen,2025-03-21,2026-05-26 14:00:00,Virtual,Zoom,Present co-invest opportunity in Fund VII deal...,Confirmed,2025-03-12 11:00:00+00:00,Co-Investment Opportunity-Granite Point Capital
12,CRM-1013,LP Advisory Committee Prep,Alan Whitfield,Northwind Investments,Sarah Chen,2025-03-24,2026-05-26 10:00:00,Internal,HQ - Boardroom,Prepare materials and talking points for upcom...,Confirmed,2025-03-15 09:00:00+00:00,LP Advisory Committee Prep-Northwind Investments
13,CRM-1014,Quick Check-in,Michael Reeves,Evergreen Capital,James Wu,2025-03-25,2026-05-26 08:30:00,Virtual,Microsoft Teams,Brief call re: capital call timing for Fund VI...,Confirmed,2025-03-20 14:00:00+00:00,Quick Check-in-Evergreen Capital
14,CRM-1015,Infrastructure Fund Pitch,Lisa Tran,Atlas Ventures,James Wu,2025-03-26,2026-05-26 10:00:00,In-Person,HQ - Conference Room A,Formal pitch for Infra V. Follow-up from March...,Confirmed,2025-03-16 08:30:00+00:00,Infrastructure Fund Pitch-Atlas Ventures
15,CRM-1016,ESG Compliance Discussion,Karen White,Redwood Institutional,Sarah Chen,2025-03-27,2026-05-26 13:00:00,Virtual,Microsoft Teams,Karen has ESG reporting requirements for their...,Confirmed,2025-03-18 09:45:00+00:00,ESG Compliance Discussion-Redwood Institutional
16,CRM-1017,Closing Dinner,Multiple,Fund VII Investors,James Wu,2025-03-28,2026-05-26 19:00:00,In-Person,The Palm - DC,Celebratory dinner for Fund VII final close. 1...,Confirmed,2025-03-10 16:00:00+00:00,Closing Dinner-Fund VII Investors
17,CRM-1018,Follow-up Call,Patricia Langley,Crestview Holdings,Sarah Chen,2025-03-25,2026-05-26 16:30:00,Virtual,Microsoft Teams,Follow up on DD questions from 3/13 meeting. P...,Confirmed,2025-03-17 10:20:00+00:00,Follow-up Call-Crestview Holdings
18,CRM-1019,Quarterly Business Review,Alan Whitfield,Northwind Investments,Sarah Chen,2025-04-01,2026-05-26 14:00:00,Internal,HQ - Large Conference Room,"Q1 wrap. Review pipeline, AUM growth, client r...",Confirmed,2025-03-05 12:00:00+00:00,Quarterly Business Review-Northwind Investments
19,CRM-1020,Northwind - Fund VII Interest,Alan Whitfield,Northwind Investments,James Wu,2025-04-02,2026-05-26 11:00:00,In-Person,NYC Office - 30th Floor,Deep dive on Fund VII. Alan indicated potentia...,Tentative,2025-03-21 15:00:00+00:00,Northwind - Fund VII Interest-Northwind Invest...

In [54]:
df_cal_=df_cal.copy()

In [55]:
df_cal_['organizer'] = df_cal_["organizer"].apply(lambda x : x.split("@")[0])
df_cal_['organizer'] = df_cal_['organizer'] .apply(lambda x: x.replace(".", " "))

In [56]:
df_cal_['attendees'] = df_cal_["attendees"].apply(lambda x : x[1].split("@")[0])
df_cal_['attendees'] = df_cal_['attendees'] .apply(lambda x: x.replace(".", " "))

In [57]:
df_cal_

,event_id,title,organizer,attendees,start_time,end_time,location,description,is_recurring,status,created_at
0,CAL-A1,Q1 Portfolio Review - Meridian Capital,sarah chen,david park,2025-03-10T14:00:00,2025-03-10T15:30:00,Conference Room B,Quarterly review of portfolio allocation and p...,False,confirmed,2025-02-27 10:00:00+00:00
1,CAL-A2,Summit Advisors - Portfolio Discussion,sarah chen,mark johnson,2025-03-12T10:00:00,2025-03-12T11:00:00,Zoom - https://zoom.us/j/98765432100,Portfolio walkthrough with Summit team.,False,confirmed,2025-02-28 15:45:00+00:00
2,CAL-A3,Weekly Team Sync,sarah chen,james wu,2025-03-11T09:00:00,2025-03-11T09:30:00,Virtual - Microsoft Teams,Standing weekly sync.,True,confirmed,2025-01-06 08:00:00+00:00
3,CAL-A4,Crestview Holdings - DD Meeting,sarah chen,patricia langley,2025-03-13T19:00:00Z,2025-03-13T20:30:00Z,DC Office - Main Conference Room,Due diligence deep-dive. Fund VII materials pr...,False,confirmed,2025-03-04 12:00:00+00:00
4,CAL-A5,Investor Update - Pinnacle,james wu,kevin obrien,2025-03-17T11:00:00,2025-03-17T12:00:00,Boston Office - Room 301,Quarterly investor update for Pinnacle Group.,False,confirmed,2025-03-02 14:30:00+00:00
5,CAL-A6,Pinnacle Group - Q1 Update,james wu,kevin obrien,2025-03-17T11:30:00,2025-03-17T12:30:00,Boston Office,Q1 update with Pinnacle Group. Sandra Mills (C...,False,confirmed,2025-03-10 09:15:00+00:00
6,CAL-A7,Internal Pipeline Review,sarah chen,james wu,2025-03-14T16:00:00,2025-03-14T17:00:00,HQ - Room 4A,Review active pipeline and upcoming client mee...,True,confirmed,2025-01-15 10:05:00+00:00
7,CAL-A8,Meridian Capital - Follow-up,sarah chen,david park,2025-03-18T15:00:00,2025-03-18T15:30:00,Zoom,Follow-up re: fee schedule and allocation chan...,False,confirmed,2025-03-11 09:45:00+00:00
8,CAL-A9,Atlas Ventures Lunch,james wu,lisa tran,2025-03-15T12:00:00,2025-03-15T13:30:00,The Capital Grille - Georgetown,Lunch with Lisa Tran. Exploring infrastructure...,False,confirmed,2025-03-07 16:00:00+00:00
9,CAL-A10,Board Prep - Q1 Materials Review,sarah chen,james wu,2025-03-19T09:00:00,2025-03-19T10:30:00,HQ - Boardroom,Review and finalize Q1 board presentation mate...,False,confirmed,2025-02-28 11:00:00+00:00
11,CAL-A12,Horizon Wealth - Year-End Review,james wu,elena marcos,2025-03-21T09:00:00,2025-03-21T10:30:00,NYC Office - 12th Floor,Annual review of allocation strategy and alter...,False,confirmed,2025-03-06 14:20:00+00:00
12,CAL-A13,Granite Point - Co-Invest Discussion,sarah chen,thomas grant,2025-03-21T14:00:00,2025-03-21T15:00:00,Zoom - https://zoom.us/j/11223344,Co-investment opportunity walkthrough for Fund...,False,confirmed,2025-03-11 16:30:00+00:00
13,CAL-A14,LPAC Prep Working Session,priya sharma,james wu,2025-03-24T10:00:00,2025-03-24T12:00:00,HQ - Boardroom,Prep session for LP Advisory Committee meeting...,False,confirmed,2025-03-14 11:00:00+00:00
14,CAL-A15,Michael Reeves - Quick Sync,james wu,michael reeves,2025-03-25T08:30:00,2025-03-25T08:45:00,HQ - Boardroom,Capital call timing discussion.,False,confirmed,2025-03-19 17:00:00+00:00
15,CAL-A16,Atlas Ventures - Infrastructure Deep Dive,james wu,lisa tran,2025-03-26T10:00:00,2025-03-26T11:30:00,Conference Room A,Formal infrastructure fund presentation. Raj P...,False,confirmed,2025-03-15 10:00:00+00:00
16,CAL-A17,ESG + Compliance Review,sarah chen,karen white,2025-03-27T15:00:00,2025-03-27T16:00:00,Microsoft Teams,Walk through ESG reporting framework and compl...,False,confirmed,2025-03-20 08:30:00+00:00
17,CAL-A18,Weekly Team Sync,sarah chen,james wu,2025-03-18T09:00:00,2025-03-18T09:30:00,Virtual - Microsoft Teams,Standing weekly sync.,True,confirmed,2025-01-06 08:00:00+00:00
18,CAL-A19,Fund VII Roadshow Prep,sarah chen,james wu,2025-03-28T14:00:00,2025-03-28T16:00:00,HQ - Room 4A,Finalize roadshow materials and talking points...,False,confirmed,2025-03-20 12:00:00+00:00
19,CAL-A20,Fund VII Closing Dinner,james wu,sarah chen,2025-03-28T19:00:00,2025-03-28T21:30:00,The Palm Restaurant,Celebratory dinner for Fund VII final close.,False,confirmed,2025-03-09 11:00:00+00:00
20,CAL-A21,Crestview Follow-up Call,sarah chen,patricia langley,2025-03-25T16:30:00,2025-03-25T17:00:00,Zoom,Follow-up on due diligence questions. Side let...,False,confirmed,2025-03-16 14:45:00+00:00
21,CAL-A22,QBR - Q1 Wrap,sarah chen,james wu,2025-04-01T14:00:00,2025-04-01T16:00:00,HQ - Large Conference Room,"Q1 quarterly business review. Pipeline, AUM, r...",False,confirmed,2025-03-04 09:30:00+00:00

In [58]:
df_cal_['date']=pd.to_datetime(df_cal_['start_time'],utc=True,format='ISO8601').dt.date
df_cal_['date']

0     2025-03-10
1     2025-03-12
2     2025-03-11
3     2025-03-13
4     2025-03-17
5     2025-03-17
6     2025-03-14
7     2025-03-18
8     2025-03-15
9     2025-03-19
11    2025-03-21
12    2025-03-21
13    2025-03-24
14    2025-03-25
15    2025-03-26
16    2025-03-27
17    2025-03-18
18    2025-03-28
19    2025-03-28
20    2025-03-25
21    2025-04-01
Name: date, dtype: object

In [59]:
df_cal_

,event_id,title,organizer,attendees,start_time,end_time,location,description,is_recurring,status,created_at,date
0,CAL-A1,Q1 Portfolio Review - Meridian Capital,sarah chen,david park,2025-03-10T14:00:00,2025-03-10T15:30:00,Conference Room B,Quarterly review of portfolio allocation and p...,False,confirmed,2025-02-27 10:00:00+00:00,2025-03-10
1,CAL-A2,Summit Advisors - Portfolio Discussion,sarah chen,mark johnson,2025-03-12T10:00:00,2025-03-12T11:00:00,Zoom - https://zoom.us/j/98765432100,Portfolio walkthrough with Summit team.,False,confirmed,2025-02-28 15:45:00+00:00,2025-03-12
2,CAL-A3,Weekly Team Sync,sarah chen,james wu,2025-03-11T09:00:00,2025-03-11T09:30:00,Virtual - Microsoft Teams,Standing weekly sync.,True,confirmed,2025-01-06 08:00:00+00:00,2025-03-11
3,CAL-A4,Crestview Holdings - DD Meeting,sarah chen,patricia langley,2025-03-13T19:00:00Z,2025-03-13T20:30:00Z,DC Office - Main Conference Room,Due diligence deep-dive. Fund VII materials pr...,False,confirmed,2025-03-04 12:00:00+00:00,2025-03-13
4,CAL-A5,Investor Update - Pinnacle,james wu,kevin obrien,2025-03-17T11:00:00,2025-03-17T12:00:00,Boston Office - Room 301,Quarterly investor update for Pinnacle Group.,False,confirmed,2025-03-02 14:30:00+00:00,2025-03-17
5,CAL-A6,Pinnacle Group - Q1 Update,james wu,kevin obrien,2025-03-17T11:30:00,2025-03-17T12:30:00,Boston Office,Q1 update with Pinnacle Group. Sandra Mills (C...,False,confirmed,2025-03-10 09:15:00+00:00,2025-03-17
6,CAL-A7,Internal Pipeline Review,sarah chen,james wu,2025-03-14T16:00:00,2025-03-14T17:00:00,HQ - Room 4A,Review active pipeline and upcoming client mee...,True,confirmed,2025-01-15 10:05:00+00:00,2025-03-14
7,CAL-A8,Meridian Capital - Follow-up,sarah chen,david park,2025-03-18T15:00:00,2025-03-18T15:30:00,Zoom,Follow-up re: fee schedule and allocation chan...,False,confirmed,2025-03-11 09:45:00+00:00,2025-03-18
8,CAL-A9,Atlas Ventures Lunch,james wu,lisa tran,2025-03-15T12:00:00,2025-03-15T13:30:00,The Capital Grille - Georgetown,Lunch with Lisa Tran. Exploring infrastructure...,False,confirmed,2025-03-07 16:00:00+00:00,2025-03-15
9,CAL-A10,Board Prep - Q1 Materials Review,sarah chen,james wu,2025-03-19T09:00:00,2025-03-19T10:30:00,HQ - Boardroom,Review and finalize Q1 board presentation mate...,False,confirmed,2025-02-28 11:00:00+00:00,2025-03-19
11,CAL-A12,Horizon Wealth - Year-End Review,james wu,elena marcos,2025-03-21T09:00:00,2025-03-21T10:30:00,NYC Office - 12th Floor,Annual review of allocation strategy and alter...,False,confirmed,2025-03-06 14:20:00+00:00,2025-03-21
12,CAL-A13,Granite Point - Co-Invest Discussion,sarah chen,thomas grant,2025-03-21T14:00:00,2025-03-21T15:00:00,Zoom - https://zoom.us/j/11223344,Co-investment opportunity walkthrough for Fund...,False,confirmed,2025-03-11 16:30:00+00:00,2025-03-21
13,CAL-A14,LPAC Prep Working Session,priya sharma,james wu,2025-03-24T10:00:00,2025-03-24T12:00:00,HQ - Boardroom,Prep session for LP Advisory Committee meeting...,False,confirmed,2025-03-14 11:00:00+00:00,2025-03-24
14,CAL-A15,Michael Reeves - Quick Sync,james wu,michael reeves,2025-03-25T08:30:00,2025-03-25T08:45:00,HQ - Boardroom,Capital call timing discussion.,False,confirmed,2025-03-19 17:00:00+00:00,2025-03-25
15,CAL-A16,Atlas Ventures - Infrastructure Deep Dive,james wu,lisa tran,2025-03-26T10:00:00,2025-03-26T11:30:00,Conference Room A,Formal infrastructure fund presentation. Raj P...,False,confirmed,2025-03-15 10:00:00+00:00,2025-03-26
16,CAL-A17,ESG + Compliance Review,sarah chen,karen white,2025-03-27T15:00:00,2025-03-27T16:00:00,Microsoft Teams,Walk through ESG reporting framework and compl...,False,confirmed,2025-03-20 08:30:00+00:00,2025-03-27
17,CAL-A18,Weekly Team Sync,sarah chen,james wu,2025-03-18T09:00:00,2025-03-18T09:30:00,Virtual - Microsoft Teams,Standing weekly sync.,True,confirmed,2025-01-06 08:00:00+00:00,2025-03-18
18,CAL-A19,Fund VII Roadshow Prep,sarah chen,james wu,2025-03-28T14:00:00,2025-03-28T16:00:00,HQ - Room 4A,Finalize roadshow materials and talking points...,False,confirmed,2025-03-20 12:00:00+00:00,2025-03-28
19,CAL-A20,Fund VII Closing Dinner,james wu,sarah chen,2025-03-28T19:00:00,2025-03-28T21:30:00,The Palm Restaurant,Celebratory dinner for Fund VII final close.,False,confirmed,2025-03-09 11:00:00+00:00,2025-03-28
20,CAL-A21,Crestview Follow-up Call,sarah chen,patricia langley,2025-03-25T16:30:00,2025-03-25T17:00:00,Zoom,Follow-up on due diligence questions. Side let...,False,confirmed,2025-03-16 14:45:00+00:00,2025-03-25
21,CAL-A22,QBR - Q1 Wrap,sarah chen,james wu,2025-04-01T14:00:00,2025-04-01T16:00:00,HQ - Large Conference Room,"Q1 quarterly business review. Pipeline, AUM, r...",False,confirmed,2025-03-04 09:30:00+00:00,2025-04-01

In [60]:
df_crm.columns

Index(['crm_id', 'subject', 'client_name', 'client_company',
       'relationship_owner', 'meeting_date', 'meeting_time', 'meeting_type',
       'location', 'notes', 'status', 'created_at', 'subject_new'],
      dtype='str')

In [61]:
df_crm.head()

,crm_id,subject,client_name,client_company,relationship_owner,meeting_date,meeting_time,meeting_type,location,notes,status,created_at,subject_new
0,CRM-1001,Q1 Portfolio Review,David Park,Meridian Capital,Sarah Chen,2025-03-10,2026-05-26 14:00:00,In-Person,HQ - Conference Room B,Review Q1 allocation strategy. David requested...,Completed,2025-02-28 09:15:00+00:00,Q1 Portfolio Review-Meridian Capital
1,CRM-1002,Portfolio Walkthrough,Mark Johnson,Summit Advisors,Sarah Chen,2025-03-12,2026-05-26 10:00:00,In-Person,NYC Office - 30th Floor,Walk through current portfolio positioning and...,Confirmed,2025-03-01 11:30:00+00:00,Portfolio Walkthrough-Summit Advisors
2,CRM-1003,Introductory Call,Rachel Torres,Lakeshore Partners,James Wu,2025-03-14,2026-05-26 15:00:00,Virtual,Microsoft Teams,First touch. Referred by Tom Nakamura at Bridg...,Scheduled,2025-03-10 14:00:00+00:00,Introductory Call-Lakeshore Partners
3,CRM-1004,Due Diligence Review,Patricia Langley,Crestview Holdings,Sarah Chen,2025-03-13,2026-05-26 14:00:00,In-Person,DC Office - Main Conference Room,DD deep-dive on Fund VII. Legal team joining.,Confirmed,2025-03-05 08:45:00+00:00,Due Diligence Review-Crestview Holdings
4,CRM-1005,Investor Update,Kevin O'Brien,Pinnacle Group,James Wu,2025-03-17,2026-05-26 11:00:00,In-Person,Boston Office,Quarterly update. Kevin may bring CIO.,Confirmed,2025-03-03 16:20:00+00:00,Investor Update-Pinnacle Group

In [62]:
df_crm_sub=df_crm[['subject_new','notes','relationship_owner','meeting_date','client_name','meeting_date','location','status']]
df_crm_sub

,subject_new,notes,relationship_owner,meeting_date,client_name,meeting_date,location,status
0,Q1 Portfolio Review-Meridian Capital,Review Q1 allocation strategy. David requested...,Sarah Chen,2025-03-10,David Park,2025-03-10,HQ - Conference Room B,Completed
1,Portfolio Walkthrough-Summit Advisors,Walk through current portfolio positioning and...,Sarah Chen,2025-03-12,Mark Johnson,2025-03-12,NYC Office - 30th Floor,Confirmed
2,Introductory Call-Lakeshore Partners,First touch. Referred by Tom Nakamura at Bridg...,James Wu,2025-03-14,Rachel Torres,2025-03-14,Microsoft Teams,Scheduled
3,Due Diligence Review-Crestview Holdings,DD deep-dive on Fund VII. Legal team joining.,Sarah Chen,2025-03-13,Patricia Langley,2025-03-13,DC Office - Main Conference Room,Confirmed
4,Investor Update-Pinnacle Group,Quarterly update. Kevin may bring CIO.,James Wu,2025-03-17,Kevin O'Brien,2025-03-17,Boston Office,Confirmed
5,Pipeline Review-Northwind Investments,Weekly pipeline review with full team.,Sarah Chen,2025-03-14,Alan Whitfield,2025-03-14,HQ - Room 4A,Confirmed
6,Follow-up Discussion-Meridian Capital,Follow up on fee schedule questions from Q1 re...,Sarah Chen,2025-03-18,David Park,2025-03-18,Microsoft Teams,Scheduled
7,Lunch Meeting-Atlas Ventures,Relationship building. Lisa interested in infr...,James Wu,03-15/2025,Lisa Tran,03-15/2025,The Capital Grille - Georgetown,Confirmed
8,Board Prep Session-Northwind Investments,Prep Q1 board materials. CANCELLED — reschedul...,Sarah Chen,2025-03-19,Alan Whitfield,2025-03-19,HQ - Boardroom,Cancelled
9,Strategy Discussion-Northwind Investments,,James Wu,2025-03-20,Alan Whitfield,2025-03-20,Microsoft Teams,Tentative
10,Annual Allocation Review-Horizon Wealth Partners,Full-year allocation review. Elena wants to di...,James Wu,2025-03-21,Elena Marcos,2025-03-21,NYC Office,Confirmed
11,Co-Investment Opportunity-Granite Point Capital,Present co-invest opportunity in Fund VII deal...,Sarah Chen,2025-03-21,Thomas Grant,2025-03-21,Zoom,Confirmed
12,LP Advisory Committee Prep-Northwind Investments,Prepare materials and talking points for upcom...,Sarah Chen,2025-03-24,Alan Whitfield,2025-03-24,HQ - Boardroom,Confirmed
13,Quick Check-in-Evergreen Capital,Brief call re: capital call timing for Fund VI...,James Wu,2025-03-25,Michael Reeves,2025-03-25,Microsoft Teams,Confirmed
14,Infrastructure Fund Pitch-Atlas Ventures,Formal pitch for Infra V. Follow-up from March...,James Wu,2025-03-26,Lisa Tran,2025-03-26,HQ - Conference Room A,Confirmed
15,ESG Compliance Discussion-Redwood Institutional,Karen has ESG reporting requirements for their...,Sarah Chen,2025-03-27,Karen White,2025-03-27,Microsoft Teams,Confirmed
16,Closing Dinner-Fund VII Investors,Celebratory dinner for Fund VII final close. 1...,James Wu,2025-03-28,Multiple,2025-03-28,The Palm - DC,Confirmed
17,Follow-up Call-Crestview Holdings,Follow up on DD questions from 3/13 meeting. P...,Sarah Chen,2025-03-25,Patricia Langley,2025-03-25,Microsoft Teams,Confirmed
18,Quarterly Business Review-Northwind Investments,"Q1 wrap. Review pipeline, AUM growth, client r...",Sarah Chen,2025-04-01,Alan Whitfield,2025-04-01,HQ - Large Conference Room,Confirmed
19,Northwind - Fund VII Interest-Northwind Invest...,Deep dive on Fund VII. Alan indicated potentia...,James Wu,2025-04-02,Alan Whitfield,2025-04-02,NYC Office - 30th Floor,Tentative

In [63]:
df_cal.head()

,event_id,title,organizer,attendees,start_time,end_time,location,description,is_recurring,status,created_at
0,CAL-A1,Q1 Portfolio Review - Meridian Capital,sarah.chen@firma.com,"(sarah.chen@firma.com, david.park@meridiancap....",2025-03-10T14:00:00,2025-03-10T15:30:00,Conference Room B,Quarterly review of portfolio allocation and p...,False,confirmed,2025-02-27 10:00:00+00:00
1,CAL-A2,Summit Advisors - Portfolio Discussion,sarah.chen@firma.com,"(sarah.chen@firma.com, mark.johnson@summitadv....",2025-03-12T10:00:00,2025-03-12T11:00:00,Zoom - https://zoom.us/j/98765432100,Portfolio walkthrough with Summit team.,False,confirmed,2025-02-28 15:45:00+00:00
2,CAL-A3,Weekly Team Sync,sarah.chen@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-11T09:00:00,2025-03-11T09:30:00,Virtual - Microsoft Teams,Standing weekly sync.,True,confirmed,2025-01-06 08:00:00+00:00
3,CAL-A4,Crestview Holdings - DD Meeting,sarah.chen@firma.com,"(sarah.chen@firma.com, patricia.langley@crestv...",2025-03-13T19:00:00Z,2025-03-13T20:30:00Z,DC Office - Main Conference Room,Due diligence deep-dive. Fund VII materials pr...,False,confirmed,2025-03-04 12:00:00+00:00
4,CAL-A5,Investor Update - Pinnacle,james.wu@firma.com,"(james.wu@firma.com, kevin.obrien@pinnaclegp.com)",2025-03-17T11:00:00,2025-03-17T12:00:00,Boston Office - Room 301,Quarterly investor update for Pinnacle Group.,False,confirmed,2025-03-02 14:30:00+00:00

In [64]:
df_cal_.columns

Index(['event_id', 'title', 'organizer', 'attendees', 'start_time', 'end_time',
       'location', 'description', 'is_recurring', 'status', 'created_at',
       'date'],
      dtype='str')

In [65]:
df_cal_sub=df_cal_[['event_id','title','organizer','attendees','date','location','description','status']]
df_cal_sub

,event_id,title,organizer,attendees,date,location,description,status
0,CAL-A1,Q1 Portfolio Review - Meridian Capital,sarah chen,david park,2025-03-10,Conference Room B,Quarterly review of portfolio allocation and p...,confirmed
1,CAL-A2,Summit Advisors - Portfolio Discussion,sarah chen,mark johnson,2025-03-12,Zoom - https://zoom.us/j/98765432100,Portfolio walkthrough with Summit team.,confirmed
2,CAL-A3,Weekly Team Sync,sarah chen,james wu,2025-03-11,Virtual - Microsoft Teams,Standing weekly sync.,confirmed
3,CAL-A4,Crestview Holdings - DD Meeting,sarah chen,patricia langley,2025-03-13,DC Office - Main Conference Room,Due diligence deep-dive. Fund VII materials pr...,confirmed
4,CAL-A5,Investor Update - Pinnacle,james wu,kevin obrien,2025-03-17,Boston Office - Room 301,Quarterly investor update for Pinnacle Group.,confirmed
5,CAL-A6,Pinnacle Group - Q1 Update,james wu,kevin obrien,2025-03-17,Boston Office,Q1 update with Pinnacle Group. Sandra Mills (C...,confirmed
6,CAL-A7,Internal Pipeline Review,sarah chen,james wu,2025-03-14,HQ - Room 4A,Review active pipeline and upcoming client mee...,confirmed
7,CAL-A8,Meridian Capital - Follow-up,sarah chen,david park,2025-03-18,Zoom,Follow-up re: fee schedule and allocation chan...,confirmed
8,CAL-A9,Atlas Ventures Lunch,james wu,lisa tran,2025-03-15,The Capital Grille - Georgetown,Lunch with Lisa Tran. Exploring infrastructure...,confirmed
9,CAL-A10,Board Prep - Q1 Materials Review,sarah chen,james wu,2025-03-19,HQ - Boardroom,Review and finalize Q1 board presentation mate...,confirmed
11,CAL-A12,Horizon Wealth - Year-End Review,james wu,elena marcos,2025-03-21,NYC Office - 12th Floor,Annual review of allocation strategy and alter...,confirmed
12,CAL-A13,Granite Point - Co-Invest Discussion,sarah chen,thomas grant,2025-03-21,Zoom - https://zoom.us/j/11223344,Co-investment opportunity walkthrough for Fund...,confirmed
13,CAL-A14,LPAC Prep Working Session,priya sharma,james wu,2025-03-24,HQ - Boardroom,Prep session for LP Advisory Committee meeting...,confirmed
14,CAL-A15,Michael Reeves - Quick Sync,james wu,michael reeves,2025-03-25,HQ - Boardroom,Capital call timing discussion.,confirmed
15,CAL-A16,Atlas Ventures - Infrastructure Deep Dive,james wu,lisa tran,2025-03-26,Conference Room A,Formal infrastructure fund presentation. Raj P...,confirmed
16,CAL-A17,ESG + Compliance Review,sarah chen,karen white,2025-03-27,Microsoft Teams,Walk through ESG reporting framework and compl...,confirmed
17,CAL-A18,Weekly Team Sync,sarah chen,james wu,2025-03-18,Virtual - Microsoft Teams,Standing weekly sync.,confirmed
18,CAL-A19,Fund VII Roadshow Prep,sarah chen,james wu,2025-03-28,HQ - Room 4A,Finalize roadshow materials and talking points...,confirmed
19,CAL-A20,Fund VII Closing Dinner,james wu,sarah chen,2025-03-28,The Palm Restaurant,Celebratory dinner for Fund VII final close.,confirmed
20,CAL-A21,Crestview Follow-up Call,sarah chen,patricia langley,2025-03-25,Zoom,Follow-up on due diligence questions. Side let...,confirmed
21,CAL-A22,QBR - Q1 Wrap,sarah chen,james wu,2025-04-01,HQ - Large Conference Room,"Q1 quarterly business review. Pipeline, AUM, r...",confirmed

In [66]:
df_crm_sub.head()

,subject_new,notes,relationship_owner,meeting_date,client_name,meeting_date,location,status
0,Q1 Portfolio Review-Meridian Capital,Review Q1 allocation strategy. David requested...,Sarah Chen,2025-03-10,David Park,2025-03-10,HQ - Conference Room B,Completed
1,Portfolio Walkthrough-Summit Advisors,Walk through current portfolio positioning and...,Sarah Chen,2025-03-12,Mark Johnson,2025-03-12,NYC Office - 30th Floor,Confirmed
2,Introductory Call-Lakeshore Partners,First touch. Referred by Tom Nakamura at Bridg...,James Wu,2025-03-14,Rachel Torres,2025-03-14,Microsoft Teams,Scheduled
3,Due Diligence Review-Crestview Holdings,DD deep-dive on Fund VII. Legal team joining.,Sarah Chen,2025-03-13,Patricia Langley,2025-03-13,DC Office - Main Conference Room,Confirmed
4,Investor Update-Pinnacle Group,Quarterly update. Kevin may bring CIO.,James Wu,2025-03-17,Kevin O'Brien,2025-03-17,Boston Office,Confirmed

In [67]:
df_cal_sub.head()

,event_id,title,organizer,attendees,date,location,description,status
0,CAL-A1,Q1 Portfolio Review - Meridian Capital,sarah chen,david park,2025-03-10,Conference Room B,Quarterly review of portfolio allocation and p...,confirmed
1,CAL-A2,Summit Advisors - Portfolio Discussion,sarah chen,mark johnson,2025-03-12,Zoom - https://zoom.us/j/98765432100,Portfolio walkthrough with Summit team.,confirmed
2,CAL-A3,Weekly Team Sync,sarah chen,james wu,2025-03-11,Virtual - Microsoft Teams,Standing weekly sync.,confirmed
3,CAL-A4,Crestview Holdings - DD Meeting,sarah chen,patricia langley,2025-03-13,DC Office - Main Conference Room,Due diligence deep-dive. Fund VII materials pr...,confirmed
4,CAL-A5,Investor Update - Pinnacle,james wu,kevin obrien,2025-03-17,Boston Office - Room 301,Quarterly investor update for Pinnacle Group.,confirmed

In [68]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (2.4.6)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn) (3.6.0)

In [69]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

vectorizer = TfidfVectorizer()

all_text = (
    df_crm_sub["subject_new"].tolist() +
    df_cal_sub["title"].tolist()
)

X = vectorizer.fit_transform(all_text)

similarity_matrix = cosine_similarity(X)
similarity_matrix

array([[1.        , 0.20934491, 0.        , ..., 0.        , 0.        ,
        0.20933683],
       [0.20934491, 1.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.        , 0.23311906,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.23311906, ..., 0.        , 1.        ,
        0.        ],
       [0.20933683, 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]], shape=(41, 41))

In [70]:
from rapidfuzz import fuzz

In [71]:
pip install rapidfuzz

Requirement already satisfied: rapidfuzz in c:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.14.5)
Note: you may need to restart the kernel to use updated packages.

In [72]:
title_score = fuzz.ratio(
            df_crm_sub.loc[0,"subject_new"],
            df_cal_sub.loc[0,"title"]
        )

In [73]:
title_score

97.2972972972973

In [74]:
df_cal_sub.columns

Index(['event_id', 'title', 'organizer', 'attendees', 'date', 'location',
       'description', 'status'],
      dtype='str')

In [75]:
df_cal_sub1=df_cal_sub[['title', 'organizer', 'attendees', 'date', 'location',
       'description', 'status']]
df_cal_sub1

,title,organizer,attendees,date,location,description,status
0,Q1 Portfolio Review - Meridian Capital,sarah chen,david park,2025-03-10,Conference Room B,Quarterly review of portfolio allocation and p...,confirmed
1,Summit Advisors - Portfolio Discussion,sarah chen,mark johnson,2025-03-12,Zoom - https://zoom.us/j/98765432100,Portfolio walkthrough with Summit team.,confirmed
2,Weekly Team Sync,sarah chen,james wu,2025-03-11,Virtual - Microsoft Teams,Standing weekly sync.,confirmed
3,Crestview Holdings - DD Meeting,sarah chen,patricia langley,2025-03-13,DC Office - Main Conference Room,Due diligence deep-dive. Fund VII materials pr...,confirmed
4,Investor Update - Pinnacle,james wu,kevin obrien,2025-03-17,Boston Office - Room 301,Quarterly investor update for Pinnacle Group.,confirmed
5,Pinnacle Group - Q1 Update,james wu,kevin obrien,2025-03-17,Boston Office,Q1 update with Pinnacle Group. Sandra Mills (C...,confirmed
6,Internal Pipeline Review,sarah chen,james wu,2025-03-14,HQ - Room 4A,Review active pipeline and upcoming client mee...,confirmed
7,Meridian Capital - Follow-up,sarah chen,david park,2025-03-18,Zoom,Follow-up re: fee schedule and allocation chan...,confirmed
8,Atlas Ventures Lunch,james wu,lisa tran,2025-03-15,The Capital Grille - Georgetown,Lunch with Lisa Tran. Exploring infrastructure...,confirmed
9,Board Prep - Q1 Materials Review,sarah chen,james wu,2025-03-19,HQ - Boardroom,Review and finalize Q1 board presentation mate...,confirmed
11,Horizon Wealth - Year-End Review,james wu,elena marcos,2025-03-21,NYC Office - 12th Floor,Annual review of allocation strategy and alter...,confirmed
12,Granite Point - Co-Invest Discussion,sarah chen,thomas grant,2025-03-21,Zoom - https://zoom.us/j/11223344,Co-investment opportunity walkthrough for Fund...,confirmed
13,LPAC Prep Working Session,priya sharma,james wu,2025-03-24,HQ - Boardroom,Prep session for LP Advisory Committee meeting...,confirmed
14,Michael Reeves - Quick Sync,james wu,michael reeves,2025-03-25,HQ - Boardroom,Capital call timing discussion.,confirmed
15,Atlas Ventures - Infrastructure Deep Dive,james wu,lisa tran,2025-03-26,Conference Room A,Formal infrastructure fund presentation. Raj P...,confirmed
16,ESG + Compliance Review,sarah chen,karen white,2025-03-27,Microsoft Teams,Walk through ESG reporting framework and compl...,confirmed
17,Weekly Team Sync,sarah chen,james wu,2025-03-18,Virtual - Microsoft Teams,Standing weekly sync.,confirmed
18,Fund VII Roadshow Prep,sarah chen,james wu,2025-03-28,HQ - Room 4A,Finalize roadshow materials and talking points...,confirmed
19,Fund VII Closing Dinner,james wu,sarah chen,2025-03-28,The Palm Restaurant,Celebratory dinner for Fund VII final close.,confirmed
20,Crestview Follow-up Call,sarah chen,patricia langley,2025-03-25,Zoom,Follow-up on due diligence questions. Side let...,confirmed
21,QBR - Q1 Wrap,sarah chen,james wu,2025-04-01,HQ - Large Conference Room,"Q1 quarterly business review. Pipeline, AUM, r...",confirmed

In [76]:
df_cal_sub2=pd.DataFrame()

In [77]:
df_cal_sub2['combine_cal']=df_cal_sub1.astype(str).agg(" ".join,axis=1)
df_cal_sub2

                                          combine_cal
0   Q1 Portfolio Review - Meridian Capital sarah c...
1   Summit Advisors - Portfolio Discussion sarah c...
2   Weekly Team Sync sarah chen james wu 2025-03-1...
3   Crestview Holdings - DD Meeting sarah chen pat...
4   Investor Update - Pinnacle james wu kevin obri...
5   Pinnacle Group - Q1 Update james wu kevin obri...
6   Internal Pipeline Review sarah chen james wu 2...
7   Meridian Capital - Follow-up sarah chen david ...
8   Atlas Ventures Lunch james wu lisa tran 2025-0...
9   Board Prep - Q1 Materials Review sarah chen ja...
11  Horizon Wealth - Year-End Review james wu elen...
12  Granite Point - Co-Invest Discussion sarah che...
13  LPAC Prep Working Session priya sharma james w...
14  Michael Reeves - Quick Sync james wu michael r...
15  Atlas Ventures - Infrastructure Deep Dive jame...
16  ESG + Compliance Review sarah chen karen white...
17  Weekly Team Sync sarah chen james wu 2025-03-1...
18  Fund VII Roadshow Prep sarah chen james wu 202...
19  Fund VII Closing Dinner james wu sarah chen 20...
20  Crestview Follow-up Call sarah chen patricia l...
21  QBR - Q1 Wrap sarah chen james wu 2025-04-01 H...

In [78]:
df_cal_sub2['cal_id']=df_cal_sub['event_id']
df_cal_sub2

                                          combine_cal   cal_id
0   Q1 Portfolio Review - Meridian Capital sarah c...   CAL-A1
1   Summit Advisors - Portfolio Discussion sarah c...   CAL-A2
2   Weekly Team Sync sarah chen james wu 2025-03-1...   CAL-A3
3   Crestview Holdings - DD Meeting sarah chen pat...   CAL-A4
4   Investor Update - Pinnacle james wu kevin obri...   CAL-A5
5   Pinnacle Group - Q1 Update james wu kevin obri...   CAL-A6
6   Internal Pipeline Review sarah chen james wu 2...   CAL-A7
7   Meridian Capital - Follow-up sarah chen david ...   CAL-A8
8   Atlas Ventures Lunch james wu lisa tran 2025-0...   CAL-A9
9   Board Prep - Q1 Materials Review sarah chen ja...  CAL-A10
11  Horizon Wealth - Year-End Review james wu elen...  CAL-A12
12  Granite Point - Co-Invest Discussion sarah che...  CAL-A13
13  LPAC Prep Working Session priya sharma james w...  CAL-A14
14  Michael Reeves - Quick Sync james wu michael r...  CAL-A15
15  Atlas Ventures - Infrastructure Deep Dive jame...  CAL-A16
16  ESG + Compliance Review sarah chen karen white...  CAL-A17
17  Weekly Team Sync sarah chen james wu 2025-03-1...  CAL-A18
18  Fund VII Roadshow Prep sarah chen james wu 202...  CAL-A19
19  Fund VII Closing Dinner james wu sarah chen 20...  CAL-A20
20  Crestview Follow-up Call sarah chen patricia l...  CAL-A21
21  QBR - Q1 Wrap sarah chen james wu 2025-04-01 H...  CAL-A22

In [79]:
df_crm_sub_1=pd.DataFrame()

In [80]:
df_crm.columns

Index(['crm_id', 'subject', 'client_name', 'client_company',
       'relationship_owner', 'meeting_date', 'meeting_time', 'meeting_type',
       'location', 'notes', 'status', 'created_at', 'subject_new'],
      dtype='str')

In [81]:
df_crm_sub.columns

Index(['subject_new', 'notes', 'relationship_owner', 'meeting_date',
       'client_name', 'meeting_date', 'location', 'status'],
      dtype='str')

In [82]:
df_crm_sub_1['combinedcol_crm']=df_crm_sub.astype(str).agg(" ".join,axis=1)
df_crm_sub_1

                                      combinedcol_crm
0   Q1 Portfolio Review-Meridian Capital Review Q1...
1   Portfolio Walkthrough-Summit Advisors Walk thr...
2   Introductory Call-Lakeshore Partners First tou...
3   Due Diligence Review-Crestview Holdings DD dee...
4   Investor Update-Pinnacle Group Quarterly updat...
5   Pipeline Review-Northwind Investments Weekly p...
6   Follow-up Discussion-Meridian Capital Follow u...
7   Lunch Meeting-Atlas Ventures Relationship buil...
8   Board Prep Session-Northwind Investments Prep ...
9   Strategy Discussion-Northwind Investments  Jam...
10  Annual Allocation Review-Horizon Wealth Partne...
11  Co-Investment Opportunity-Granite Point Capita...
12  LP Advisory Committee Prep-Northwind Investmen...
13  Quick Check-in-Evergreen Capital Brief call re...
14  Infrastructure Fund Pitch-Atlas Ventures Forma...
15  ESG Compliance Discussion-Redwood Institutiona...
16  Closing Dinner-Fund VII Investors Celebratory ...
17  Follow-up Call-Crestview Holdings Follow up on...
18  Quarterly Business Review-Northwind Investment...
19  Northwind - Fund VII Interest-Northwind Invest...

In [83]:
df_crm_sub_1['crm_id']=df_crm['crm_id']
df_crm_sub_1

                                      combinedcol_crm    crm_id
0   Q1 Portfolio Review-Meridian Capital Review Q1...  CRM-1001
1   Portfolio Walkthrough-Summit Advisors Walk thr...  CRM-1002
2   Introductory Call-Lakeshore Partners First tou...  CRM-1003
3   Due Diligence Review-Crestview Holdings DD dee...  CRM-1004
4   Investor Update-Pinnacle Group Quarterly updat...  CRM-1005
5   Pipeline Review-Northwind Investments Weekly p...  CRM-1006
6   Follow-up Discussion-Meridian Capital Follow u...  CRM-1007
7   Lunch Meeting-Atlas Ventures Relationship buil...  CRM-1008
8   Board Prep Session-Northwind Investments Prep ...  CRM-1009
9   Strategy Discussion-Northwind Investments  Jam...  CRM-1010
10  Annual Allocation Review-Horizon Wealth Partne...  CRM-1011
11  Co-Investment Opportunity-Granite Point Capita...  CRM-1012
12  LP Advisory Committee Prep-Northwind Investmen...  CRM-1013
13  Quick Check-in-Evergreen Capital Brief call re...  CRM-1014
14  Infrastructure Fund Pitch-Atlas Ventures Forma...  CRM-1015
15  ESG Compliance Discussion-Redwood Institutiona...  CRM-1016
16  Closing Dinner-Fund VII Investors Celebratory ...  CRM-1017
17  Follow-up Call-Crestview Holdings Follow up on...  CRM-1018
18  Quarterly Business Review-Northwind Investment...  CRM-1019
19  Northwind - Fund VII Interest-Northwind Invest...  CRM-1020

In [84]:
df_cal_sub2['combine_cal']=df_cal_sub2['combine_cal'].str.lower()
df_cal_sub2

                                          combine_cal   cal_id
0   q1 portfolio review - meridian capital sarah c...   CAL-A1
1   summit advisors - portfolio discussion sarah c...   CAL-A2
2   weekly team sync sarah chen james wu 2025-03-1...   CAL-A3
3   crestview holdings - dd meeting sarah chen pat...   CAL-A4
4   investor update - pinnacle james wu kevin obri...   CAL-A5
5   pinnacle group - q1 update james wu kevin obri...   CAL-A6
6   internal pipeline review sarah chen james wu 2...   CAL-A7
7   meridian capital - follow-up sarah chen david ...   CAL-A8
8   atlas ventures lunch james wu lisa tran 2025-0...   CAL-A9
9   board prep - q1 materials review sarah chen ja...  CAL-A10
11  horizon wealth - year-end review james wu elen...  CAL-A12
12  granite point - co-invest discussion sarah che...  CAL-A13
13  lpac prep working session priya sharma james w...  CAL-A14
14  michael reeves - quick sync james wu michael r...  CAL-A15
15  atlas ventures - infrastructure deep dive jame...  CAL-A16
16  esg + compliance review sarah chen karen white...  CAL-A17
17  weekly team sync sarah chen james wu 2025-03-1...  CAL-A18
18  fund vii roadshow prep sarah chen james wu 202...  CAL-A19
19  fund vii closing dinner james wu sarah chen 20...  CAL-A20
20  crestview follow-up call sarah chen patricia l...  CAL-A21
21  qbr - q1 wrap sarah chen james wu 2025-04-01 h...  CAL-A22

In [85]:
df_crm_sub_1['combinedcol_crm']=df_crm_sub_1['combinedcol_crm'].str.lower()
df_crm_sub_1

                                      combinedcol_crm    crm_id
0   q1 portfolio review-meridian capital review q1...  CRM-1001
1   portfolio walkthrough-summit advisors walk thr...  CRM-1002
2   introductory call-lakeshore partners first tou...  CRM-1003
3   due diligence review-crestview holdings dd dee...  CRM-1004
4   investor update-pinnacle group quarterly updat...  CRM-1005
5   pipeline review-northwind investments weekly p...  CRM-1006
6   follow-up discussion-meridian capital follow u...  CRM-1007
7   lunch meeting-atlas ventures relationship buil...  CRM-1008
8   board prep session-northwind investments prep ...  CRM-1009
9   strategy discussion-northwind investments  jam...  CRM-1010
10  annual allocation review-horizon wealth partne...  CRM-1011
11  co-investment opportunity-granite point capita...  CRM-1012
12  lp advisory committee prep-northwind investmen...  CRM-1013
13  quick check-in-evergreen capital brief call re...  CRM-1014
14  infrastructure fund pitch-atlas ventures forma...  CRM-1015
15  esg compliance discussion-redwood institutiona...  CRM-1016
16  closing dinner-fund vii investors celebratory ...  CRM-1017
17  follow-up call-crestview holdings follow up on...  CRM-1018
18  quarterly business review-northwind investment...  CRM-1019
19  northwind - fund vii interest-northwind invest...  CRM-1020

In [86]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [87]:
def cal_cosin_Simi(df_crm_sub_1,df_cal_sub2):
    results = []
    all_text = (
        df_crm_sub_1["combinedcol_crm1"].tolist() +
        df_cal_sub2["combine_col"].tolist()
    )
    vectorizer = TfidfVectorizer()
    tfidf_matrix = vectorizer.fit_transform(all_text)
    crm_vectors = tfidf_matrix[:len(df_crm_sub_1)]
    cal_vectors = tfidf_matrix[len(df_crm_sub_1):]

    for i in range(len(df_crm_sub_1)):

        scores = cosine_similarity(
            crm_vectors[i],
            cal_vectors
        )

        best_idx = scores.argmax()

        best_score = scores[0][best_idx]
        if best_score > 0.70:
            results.append({
                "crm_id": df_crm_sub_1.iloc[i]["crm_id"],
                "matched_event": df_cal_sub2.iloc[best_idx]["cal_id"],
                "score": best_score
            })
    return results

In [88]:
vectorizer = TfidfVectorizer()

tfidf_matrix = vectorizer.fit_transform(all_text)

In [89]:
crm_vectors = tfidf_matrix[:len(df_crm_sub_1)]

cal_vectors = tfidf_matrix[len(df_crm_sub_1):]

In [90]:
results = []

for i in range(len(df_crm_sub_1)):

    scores = cosine_similarity(
        crm_vectors[i],
        cal_vectors
    )

    best_idx = scores.argmax()

    best_score = scores[0][best_idx]
    if best_score > 0.70:
        results.append({
            "crm_id": df_crm_sub_1.iloc[i]["crm_id"],
            "matched_event": df_cal_sub2.iloc[best_idx]["cal_id"],
            "score": best_score
        })

In [91]:
results

[{'crm_id': 'CRM-1001', 'matched_event': 'CAL-A1', 'score': np.float64(1.0)},
 {'crm_id': 'CRM-1002',
  'matched_event': 'CAL-A2',
  'score': np.float64(0.7457364201355863)},
 {'crm_id': 'CRM-1005',
  'matched_event': 'CAL-A5',
  'score': np.float64(0.8540831032235284)},
 {'crm_id': 'CRM-1007',
  'matched_event': 'CAL-A8',
  'score': np.float64(0.900354829850835)},
 {'crm_id': 'CRM-1008',
  'matched_event': 'CAL-A9',
  'score': np.float64(0.8440803098032216)},
 {'crm_id': 'CRM-1017',
  'matched_event': 'CAL-A20',
  'score': np.float64(0.8562593164661007)},
 {'crm_id': 'CRM-1018',
  'matched_event': 'CAL-A21',
  'score': np.float64(0.8850192604505728)}]

In [92]:
# -----remove the date and punctuations from the string -------

In [93]:
import re
import string

In [94]:
def clean_text(text):
    text = str(text)
    text = re.sub(r'\b\d{1,4}[-/]\d{1,4}[-/]\d{1,4}\b',' ',text)
    text.translate(str.maketrans('','',string.punctuation))
    text=text.lower()
    text=re.sub(r'\s+',' ',text).strip()
    return text

In [95]:
df_cal_sub2.columns

Index(['combine_cal', 'cal_id'], dtype='str')

In [96]:
df_cal_sub3=df_cal_sub2.copy()

In [97]:
df_cal_sub3['combine_col']=df_cal_sub3['combine_cal'].apply(lambda x:clean_text(x))

In [98]:
df_cal_sub3

,combine_cal,cal_id,combine_col
0,q1 portfolio review - meridian capital sarah c...,CAL-A1,q1 portfolio review - meridian capital sarah c...
1,summit advisors - portfolio discussion sarah c...,CAL-A2,summit advisors - portfolio discussion sarah c...
2,weekly team sync sarah chen james wu 2025-03-1...,CAL-A3,weekly team sync sarah chen james wu virtual -...
3,crestview holdings - dd meeting sarah chen pat...,CAL-A4,crestview holdings - dd meeting sarah chen pat...
4,investor update - pinnacle james wu kevin obri...,CAL-A5,investor update - pinnacle james wu kevin obri...
5,pinnacle group - q1 update james wu kevin obri...,CAL-A6,pinnacle group - q1 update james wu kevin obri...
6,internal pipeline review sarah chen james wu 2...,CAL-A7,internal pipeline review sarah chen james wu h...
7,meridian capital - follow-up sarah chen david ...,CAL-A8,meridian capital - follow-up sarah chen david ...
8,atlas ventures lunch james wu lisa tran 2025-0...,CAL-A9,atlas ventures lunch james wu lisa tran the ca...
9,board prep - q1 materials review sarah chen ja...,CAL-A10,board prep - q1 materials review sarah chen ja...
11,horizon wealth - year-end review james wu elen...,CAL-A12,horizon wealth - year-end review james wu elen...
12,granite point - co-invest discussion sarah che...,CAL-A13,granite point - co-invest discussion sarah che...
13,lpac prep working session priya sharma james w...,CAL-A14,lpac prep working session priya sharma james w...
14,michael reeves - quick sync james wu michael r...,CAL-A15,michael reeves - quick sync james wu michael r...
15,atlas ventures - infrastructure deep dive jame...,CAL-A16,atlas ventures - infrastructure deep dive jame...
16,esg + compliance review sarah chen karen white...,CAL-A17,esg + compliance review sarah chen karen white...
17,weekly team sync sarah chen james wu 2025-03-1...,CAL-A18,weekly team sync sarah chen james wu virtual -...
18,fund vii roadshow prep sarah chen james wu 202...,CAL-A19,fund vii roadshow prep sarah chen james wu hq ...
19,fund vii closing dinner james wu sarah chen 20...,CAL-A20,fund vii closing dinner james wu sarah chen th...
20,crestview follow-up call sarah chen patricia l...,CAL-A21,crestview follow-up call sarah chen patricia l...
21,qbr - q1 wrap sarah chen james wu 2025-04-01 h...,CAL-A22,qbr - q1 wrap sarah chen james wu hq - large c...

In [99]:
df_crm_sub_1.columns

Index(['combinedcol_crm', 'crm_id'], dtype='str')

In [100]:
df_crm_sub_1['combinedcol_crm1']=df_crm_sub_1['combinedcol_crm'].apply(lambda x:clean_text(x))

In [101]:
df_crm_sub_1

,combinedcol_crm,crm_id,combinedcol_crm1
0,q1 portfolio review-meridian capital review q1...,CRM-1001,q1 portfolio review-meridian capital review q1...
1,portfolio walkthrough-summit advisors walk thr...,CRM-1002,portfolio walkthrough-summit advisors walk thr...
2,introductory call-lakeshore partners first tou...,CRM-1003,introductory call-lakeshore partners first tou...
3,due diligence review-crestview holdings dd dee...,CRM-1004,due diligence review-crestview holdings dd dee...
4,investor update-pinnacle group quarterly updat...,CRM-1005,investor update-pinnacle group quarterly updat...
5,pipeline review-northwind investments weekly p...,CRM-1006,pipeline review-northwind investments weekly p...
6,follow-up discussion-meridian capital follow u...,CRM-1007,follow-up discussion-meridian capital follow u...
7,lunch meeting-atlas ventures relationship buil...,CRM-1008,lunch meeting-atlas ventures relationship buil...
8,board prep session-northwind investments prep ...,CRM-1009,board prep session-northwind investments prep ...
9,strategy discussion-northwind investments jam...,CRM-1010,strategy discussion-northwind investments jame...
10,annual allocation review-horizon wealth partne...,CRM-1011,annual allocation review-horizon wealth partne...
11,co-investment opportunity-granite point capita...,CRM-1012,co-investment opportunity-granite point capita...
12,lp advisory committee prep-northwind investmen...,CRM-1013,lp advisory committee prep-northwind investmen...
13,quick check-in-evergreen capital brief call re...,CRM-1014,quick check-in-evergreen capital brief call re...
14,infrastructure fund pitch-atlas ventures forma...,CRM-1015,infrastructure fund pitch-atlas ventures forma...
15,esg compliance discussion-redwood institutiona...,CRM-1016,esg compliance discussion-redwood institutiona...
16,closing dinner-fund vii investors celebratory ...,CRM-1017,closing dinner-fund vii investors celebratory ...
17,follow-up call-crestview holdings follow up on...,CRM-1018,follow-up call-crestview holdings follow up on...
18,quarterly business review-northwind investment...,CRM-1019,quarterly business review-northwind investment...
19,northwind - fund vii interest-northwind invest...,CRM-1020,northwind - fund vii interest-northwind invest...

In [102]:
result = cal_cosin_Simi(df_crm_sub_1,df_cal_sub3)
result

[{'crm_id': 'CRM-1004',
  'matched_event': 'CAL-A4',
  'score': np.float64(0.7457403004868427)},
 {'crm_id': 'CRM-1005',
  'matched_event': 'CAL-A5',
  'score': np.float64(0.704502976123972)},
 {'crm_id': 'CRM-1008',
  'matched_event': 'CAL-A9',
  'score': np.float64(0.7236768166814962)},
 {'crm_id': 'CRM-1016',
  'matched_event': 'CAL-A17',
  'score': np.float64(0.7191750188589454)},
 {'crm_id': 'CRM-1017',
  'matched_event': 'CAL-A20',
  'score': np.float64(0.7163737329597044)}]

In [103]:
from rapidfuzz import fuzz

In [104]:
def cal_rapid_Fuzz(df_crm1,df_cal2):
    result= [] 
    crmlist = df_crm1['combinedcol_crm1'].tolist()
    callist = df_cal2['combine_col'].tolist()
    for i in range(0,len(crmlist)):
        for j in range(0,len(callist)):
            score = fuzz.ratio(
                crmlist[i].lower(),
                callist[j].lower()
            )
            # print('score is {}'.format(score))
            if score > 70.00:
                print('score is {}'.format(score))
                result.append({
                    'crm_id': df_crm1.iloc[i]['crm_id'],
                    'cal_id':df_cal2.iloc[j]['cal_id'],
                    'score':score})
                
    return result

In [105]:
result = cal_rapid_Fuzz(df_crm_sub_1,df_cal_sub3)
result

[]

In [106]:
 !pip install sentence-transformers

Requirement already satisfied: sentence-transformers in C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (5.5.1)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sentence-transformers) (5.9.0)
Requirement already satisfied: huggingface-hub>=0.23.0 in C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sentence-transformers) (1.16.1)
Requirement already satisfied: torch>=1.11.0 in C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sentence-transformers) (2.12.0)
Requirement already satisfied: numpy>=1.20.0 in C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sentence-transformers) (2.4.6)
Requirement already satisfied: scikit-learn>=0.22.0 in C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sentence-transformers) (1.8.0)
Requirement already satisfied: scipy>=1.0.0 in C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sentence-transformers) (1.17.1)
Requirement already satisfied: typing_extensions>=4.5.0 in C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: packaging>=20.0 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2026.5.9)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer in C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: filelock>=3.10.0 in C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2026.4.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.5.0)
Requirement already satisfied: httpx<1,>=0.23.0 in C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: anyio in C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.13.0)
Requirement already satisfied: certifi in C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.5.20)
Requirement already satisfied: httpcore==1.* in C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.16)
Requirement already satisfied: h11>=0.16 in C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: joblib>=1.3.0 in C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools<82 in C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from torch>=1.11.0->sentence-transformers) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: colorama in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from tqdm>=4.0.0->sentence-transformers) (0.4.6)
Requirement already satisfied: click>=8.2.1 in C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (8.4.0)
Requirement already satisfied: shellingham>=1.3.0 in C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)

In [107]:
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

c:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [108]:
def sentence_embed(df_crm1,df_cal1):
    model = SentenceTransformer('all-MiniLM-L6-v2')
    crm_embeddings = model.encode(
    df_crm1["combinedcol_crm1"].tolist()
    )
    print('crm embeddingsi ',crm_embeddings)

    cal_embeddings = model.encode(
        df_cal1["combine_col"].tolist()
    )
    print('cal_embedding is ',cal_embeddings)
    results = []

    for i in range(len(df_crm1)):
        # for j in range(len(df_cal1)):
            scores = cosine_similarity(
                [crm_embeddings[i]],
                cal_embeddings
            )

            best_idx = scores.argmax()
            print('best_idx',best_idx)
            best_score = scores[0][best_idx]
            print('best score',best_score)
            if best_score > 0.80:
                results.append({
                    "crm_id": df_crm1.iloc[i]["crm_id"],
                    "matched_event": df_cal1.iloc[best_idx]["cal_id"],
                    "score": best_score,
                    "match":'true'
                })
            else:
                  results.append({
                    "crm_id": df_crm1.iloc[i]["crm_id"],
                    "matched_event": df_cal1.iloc[best_idx]["cal_id"],
                    "score": best_score,
                    "match":'false'
                })
                 
    return results

In [109]:
result = sentence_embed(df_crm_sub_1,df_cal_sub3)
result
len(result)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 330.47it/s]

crm embeddingsi  [[ 0.02643295  0.02476399 -0.01835969 ... -0.07876006 -0.11339824
  -0.01923878]
 [-0.06051822 -0.05989839 -0.02348952 ... -0.06988072 -0.11172547
   0.06556825]
 [-0.07679214 -0.0779122   0.03450471 ...  0.01485847 -0.04563528
   0.03736547]
 ...
 [-0.09429372 -0.07671553  0.02989641 ... -0.05412352 -0.01386296
   0.06601552]
 [ 0.01091177  0.01606909 -0.02772195 ... -0.12280275 -0.01766587
   0.12372516]
 [ 0.04853305  0.0054814  -0.04454004 ... -0.13440068 -0.0847174
   0.06483381]]
cal_embedding is  [[ 0.04079346 -0.01772048 -0.04731451 ... -0.11445934 -0.10323226
  -0.00059207]
 [-0.1266164  -0.0236257  -0.0257734  ... -0.0811489  -0.13875376
   0.0218557 ]
 [-0.11931954 -0.05435009 -0.02242507 ...  0.00953413 -0.04721766
   0.00742427]
 ...
 [-0.03140982  0.02260843 -0.00080126 ... -0.06995343 -0.07379625
   0.03260722]
 [-0.08221824 -0.03539788  0.03484094 ... -0.05316094 -0.02895772
   0.02583785]
 [-0.05905388 -0.00604458 -0.02216261 ... -0.06452207 -0.04354988
   0.03864064]]
best_idx 0
best score 0.897672
best_idx 1
best score 0.72644496
best_idx 13
best score 0.47768006
best_idx 3
best score 0.84688926
best_idx 4
best score 0.84543204
best_idx 6
best score 0.81194335
best_idx 7
best score 0.8377291
best_idx 8
best score 0.9206344
best_idx 9
best score 0.599349
best_idx 11
best score 0.4657525
best_idx 10
best score 0.84941983
best_idx 11
best score 0.8797484
best_idx 12
best score 0.6552551
best_idx 13
best score 0.61022556
best_idx 14
best score 0.80212224
best_idx 15
best score 0.8623046
best_idx 18
best score 0.85856795
best_idx 3
best score 0.7804055
best_idx 20
best score 0.64444506
best_idx 11
best score 0.5897621

20

In [110]:
result

[{'crm_id': 'CRM-1001',
  'matched_event': 'CAL-A1',
  'score': np.float32(0.897672),
  'match': 'true'},
 {'crm_id': 'CRM-1002',
  'matched_event': 'CAL-A2',
  'score': np.float32(0.72644496),
  'match': 'false'},
 {'crm_id': 'CRM-1003',
  'matched_event': 'CAL-A15',
  'score': np.float32(0.47768006),
  'match': 'false'},
 {'crm_id': 'CRM-1004',
  'matched_event': 'CAL-A4',
  'score': np.float32(0.84688926),
  'match': 'true'},
 {'crm_id': 'CRM-1005',
  'matched_event': 'CAL-A5',
  'score': np.float32(0.84543204),
  'match': 'true'},
 {'crm_id': 'CRM-1006',
  'matched_event': 'CAL-A7',
  'score': np.float32(0.81194335),
  'match': 'true'},
 {'crm_id': 'CRM-1007',
  'matched_event': 'CAL-A8',
  'score': np.float32(0.8377291),
  'match': 'true'},
 {'crm_id': 'CRM-1008',
  'matched_event': 'CAL-A9',
  'score': np.float32(0.9206344),
  'match': 'true'},
 {'crm_id': 'CRM-1009',
  'matched_event': 'CAL-A10',
  'score': np.float32(0.599349),
  'match': 'false'},
 {'crm_id': 'CRM-1010',
  'matched_event': 'CAL-A13',
  'score': np.float32(0.4657525),
  'match': 'false'},
 {'crm_id': 'CRM-1011',
  'matched_event': 'CAL-A12',
  'score': np.float32(0.84941983),
  'match': 'true'},
 {'crm_id': 'CRM-1012',
  'matched_event': 'CAL-A13',
  'score': np.float32(0.8797484),
  'match': 'true'},
 {'crm_id': 'CRM-1013',
  'matched_event': 'CAL-A14',
  'score': np.float32(0.6552551),
  'match': 'false'},
 {'crm_id': 'CRM-1014',
  'matched_event': 'CAL-A15',
  'score': np.float32(0.61022556),
  'match': 'false'},
 {'crm_id': 'CRM-1015',
  'matched_event': 'CAL-A16',
  'score': np.float32(0.80212224),
  'match': 'true'},
 {'crm_id': 'CRM-1016',
  'matched_event': 'CAL-A17',
  'score': np.float32(0.8623046),
  'match': 'true'},
 {'crm_id': 'CRM-1017',
  'matched_event': 'CAL-A20',
  'score': np.float32(0.85856795),
  'match': 'true'},
 {'crm_id': 'CRM-1018',
  'matched_event': 'CAL-A4',
  'score': np.float32(0.7804055),
  'match': 'false'},
 {'crm_id': 'CRM-1019',
  'matched_event': 'CAL-A22',
  'score': np.float32(0.64444506),
  'match': 'false'},
 {'crm_id': 'CRM-1020',
  'matched_event': 'CAL-A13',
  'score': np.float32(0.5897621),
  'match': 'false'}]

In [114]:
result_df = pd.DataFrame(result)

print(result_df)

      crm_id matched_event     score  match
0   CRM-1001        CAL-A1  0.897672   true
1   CRM-1002        CAL-A2  0.726445  false
2   CRM-1003       CAL-A15  0.477680  false
3   CRM-1004        CAL-A4  0.846889   true
4   CRM-1005        CAL-A5  0.845432   true
5   CRM-1006        CAL-A7  0.811943   true
6   CRM-1007        CAL-A8  0.837729   true
7   CRM-1008        CAL-A9  0.920634   true
8   CRM-1009       CAL-A10  0.599349  false
9   CRM-1010       CAL-A13  0.465753  false
10  CRM-1011       CAL-A12  0.849420   true
11  CRM-1012       CAL-A13  0.879748   true
12  CRM-1013       CAL-A14  0.655255  false
13  CRM-1014       CAL-A15  0.610226  false
14  CRM-1015       CAL-A16  0.802122   true
15  CRM-1016       CAL-A17  0.862305   true
16  CRM-1017       CAL-A20  0.858568   true
17  CRM-1018        CAL-A4  0.780406  false
18  CRM-1019       CAL-A22  0.644445  false
19  CRM-1020       CAL-A13  0.589762  false