In [4]:
import pandas as pd
import json

In [2]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.3-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting numpy>=2.3.3 (from pandas)
  Downloading numpy-2.4.6-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in C:\Users\Admin\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp314-cp314-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   --- ------------------------------------ 0.8/9.9 MB 6.5 MB/s eta 0:00:02
   -------- ------------------------------- 2.1/9.9 MB 5.7 MB/s eta 0:00:02
   ---------- ----------------------------- 2.6/9.9 MB 5.4 MB/s eta 0:00:02
   ---------- ----------------------------- 2.6/9.9 MB 5.4 MB/s eta 0:00:02
   --------------- ------------------------ 3.9/9.9 MB 3.8 MB/s eta 0:00:02
   --------------------- ------------------ 5.2/9.9 MB 4.3 MB/s eta 0:00:02
   -------------------------- ------------- 6.6/9.9 MB 4.7 MB/s eta 0:00:01
   ------------------------------ --------- 7.6/9.9 MB 4.7 MB/s eta 0:00:01
   ----------------------------------- ---- 8.7/9.9 MB 4.7 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 4.9 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 4.9 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 4.3 MB/s  0:00:02
Downloading numpy-2.4.6-cp314-cp314-win_amd64.whl (12.5 MB)
   ---------------------------------------- 0.0/12.5 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/12.5 MB 6.3 MB/s eta 0:00:02
   -------- ------------------------------- 2.6/12.5 MB 6.2 MB/s eta 0:00:02
   ----------- ---------------------------- 3.7/12.5 MB 6.3 MB/s eta 0:00:02
   --------------- ------------------------ 4.7/12.5 MB 5.8 MB/s eta 0:00:02
   ------------------ --------------------- 5.8/12.5 MB 5.7 MB/s eta 0:00:02
   ---------------------- ----------------- 7.1/12.5 MB 5.7 MB/s eta 0:00:01
   -------------------------- ------------- 8.1/12.5 MB 5.6 MB/s eta 0:00:01
   ------------------------------ --------- 9.4/12.5 MB 5.6 MB/s eta 0:00:01
   -------------------------------- ------- 10.2/12.5 MB 5.5 MB/s eta 0:00:01
   ------------------------------------ --- 11.3/12.5 MB 5.4 MB/s eta 0:00:01
   -------------------------------------- - 12.1/12.5 MB 5.3 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.5 MB 5.1 MB/s eta 0:00:01
   ---------------------------------------- 12.5/12.5 MB 4.6 MB/s  0:00:02
Downloading tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Installing collected packages: tzdata, numpy, pandas

   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   ---------------------------------------- 3/3 [pandas]

Successfully installed numpy-2.4.6 pandas-3.0.3 tzdata-2026.2
Note: you may need to restart the kernel to use updated packages.

  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'c:\Users\Admin\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

In [12]:
# with open('c:\\Users\\Admin\\Downloads\\mle_code_assessment\\mle_code_assessment\\data\\crm_events.json','r') as f:
df_crm = pd.read_json('c:\\Users\\Admin\\Downloads\\mle_code_assessment\\mle_code_assessment\\data\\crm_events.json')
# df_cal = json.load(r'mle_code_assessment\data\calendar_events.json')
df_crm

,crm_id,subject,client_name,client_company,relationship_owner,meeting_date,meeting_time,meeting_type,location,notes,status,created_at
0,CRM-1001,Q1 Portfolio Review,David Park,Meridian Capital,Sarah Chen,2025-03-10,2026-05-21 14:00:00,In-Person,HQ - Conference Room B,Review Q1 allocation strategy. David requested...,Completed,2025-02-28 09:15:00+00:00
1,CRM-1002,Portfolio Walkthrough,Mark Johnson,Summit Advisors,Sarah Chen,2025-03-12,2026-05-21 10:00:00,In-Person,NYC Office - 30th Floor,Walk through current portfolio positioning and...,Confirmed,2025-03-01 11:30:00+00:00
2,CRM-1003,Introductory Call,Rachel Torres,Lakeshore Partners,James Wu,2025-03-14,2026-05-21 15:00:00,Virtual,NaN,First touch. Referred by Tom Nakamura at Bridg...,Scheduled,2025-03-10 14:00:00+00:00
3,CRM-1004,Due Diligence Review,Patricia Langley,Crestview Holdings,Sarah Chen,2025-03-13,2026-05-21 14:00:00,In-Person,DC Office - Main Conference Room,DD deep-dive on Fund VII. Legal team joining.,Confirmed,2025-03-05 08:45:00+00:00
4,CRM-1005,Investor Update,Kevin O'Brien,Pinnacle Group,James Wu,2025-03-17,2026-05-21 11:00:00,In-Person,Boston Office,Quarterly update. Kevin may bring CIO.,Confirmed,2025-03-03 16:20:00+00:00
5,CRM-1006,Pipeline Review,NaN,NaN,Sarah Chen,2025-03-14,2026-05-21 16:00:00,Internal,HQ - Room 4A,Weekly pipeline review with full team.,Confirmed,2025-01-15 10:00:00+00:00
6,CRM-1007,Follow-up Discussion,David Park,Meridian Capital,Sarah Chen,2025-03-18,NaT,Virtual,NaN,Follow up on fee schedule questions from Q1 re...,Scheduled,2025-03-11 09:30:00+00:00
7,CRM-1008,Lunch Meeting,Lisa Tran,Atlas Ventures,James Wu,03-15/2025,2026-05-21 12:00:00,In-Person,The Capital Grille - Georgetown,Relationship building. Lisa interested in infr...,Confirmed,2025-03-08 13:00:00+00:00
8,CRM-1009,Board Prep Session,NaN,NaN,Sarah Chen,2025-03-19,2026-05-21 09:00:00,Internal,HQ - Boardroom,Prep Q1 board materials. CANCELLED — reschedul...,Cancelled,2025-03-01 08:00:00+00:00
9,CRM-1010,Strategy Discussion,Alan Whitfield,Northwind Investments,James Wu,2025-03-20,2026-05-21 10:00:00,Virtual,Microsoft Teams,,Tentative,2025-03-14 17:30:00+00:00
10,CRM-1011,Annual Allocation Review,Elena Marcos,Horizon Wealth Partners,James Wu,2025-03-21,2026-05-21 09:00:00,In-Person,NYC Office,Full-year allocation review. Elena wants to di...,Confirmed,2025-03-07 10:15:00+00:00
11,CRM-1012,Co-Investment Opportunity,Thomas Grant,Granite Point Capital,Sarah Chen,2025-03-21,2026-05-21 14:00:00,Virtual,Zoom,Present co-invest opportunity in Fund VII deal...,Confirmed,2025-03-12 11:00:00+00:00
12,CRM-1013,LP Advisory Committee Prep,NaN,NaN,Sarah Chen,2025-03-24,2026-05-21 10:00:00,Internal,HQ - Boardroom,Prepare materials and talking points for upcom...,Confirmed,2025-03-15 09:00:00+00:00
13,CRM-1014,Quick Check-in,Michael Reeves,Evergreen Capital,James Wu,2025-03-25,2026-05-21 08:30:00,Virtual,NaN,Brief call re: capital call timing for Fund VI...,Confirmed,2025-03-20 14:00:00+00:00
14,CRM-1015,Infrastructure Fund Pitch,Lisa Tran,Atlas Ventures,James Wu,2025-03-26,2026-05-21 10:00:00,In-Person,HQ - Conference Room A,Formal pitch for Infra V. Follow-up from March...,Confirmed,2025-03-16 08:30:00+00:00
15,CRM-1016,ESG Compliance Discussion,Karen White,Redwood Institutional,Sarah Chen,2025-03-27,2026-05-21 13:00:00,Virtual,Microsoft Teams,Karen has ESG reporting requirements for their...,Confirmed,2025-03-18 09:45:00+00:00
16,CRM-1017,Closing Dinner,Multiple,Fund VII Investors,James Wu,2025-03-28,2026-05-21 19:00:00,In-Person,The Palm - DC,Celebratory dinner for Fund VII final close. 1...,Confirmed,2025-03-10 16:00:00+00:00
17,CRM-1018,Follow-up Call,Patricia Langley,Crestview Holdings,Sarah Chen,2025-03-25,2026-05-21 16:30:00,Virtual,NaN,Follow up on DD questions from 3/13 meeting. P...,Confirmed,2025-03-17 10:20:00+00:00
18,CRM-1019,Quarterly Business Review,NaN,NaN,Sarah Chen,2025-04-01,2026-05-21 14:00:00,Internal,HQ - Large Conference Room,"Q1 wrap. Review pipeline, AUM growth, client r...",Confirmed,2025-03-05 12:00:00+00:00
19,CRM-1020,Northwind - Fund VII Interest,Alan Whitfield,Northwind Investments,James Wu,2025-04-02,2026-05-21 11:00:00,In-Person,NYC Office - 30th Floor,Deep dive on Fund VII. Alan indicated potentia...,Tentative,2025-03-21 15:00:00+00:00

In [17]:
df_crm.shape

(20, 12)

In [19]:
df_crm.isna()

,crm_id,subject,client_name,client_company,relationship_owner,meeting_date,meeting_time,meeting_type,location,notes,status,created_at
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,True,True,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,True,False,True,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,True,True,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,True,True,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,True,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,True,False,False,False
18,False,False,True,True,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False

In [10]:
import os

os.getcwd()

'c:\\Users\\Admin\\Downloads\\mle_code_assessment\\mle_code_assessment\\scripts'

In [16]:
df_cal = pd.read_json('c:\\Users\\Admin\\Downloads\\mle_code_assessment\\mle_code_assessment\\data\\calendar_events.json')
df_cal

,event_id,title,organizer,attendees,start_time,end_time,location,description,is_recurring,status,created_at
0,CAL-A1,Q1 Portfolio Review - Meridian Capital,sarah.chen@firma.com,"[sarah.chen@firma.com, david.park@meridiancap....",2025-03-10T14:00:00,2025-03-10T15:30:00,Conference Room B,Quarterly review of portfolio allocation and p...,False,confirmed,2025-02-27 10:00:00+00:00
1,CAL-A2,Summit Advisors - Portfolio Discussion,sarah.chen@firma.com,"[sarah.chen@firma.com, mark.johnson@summitadv....",2025-03-12T10:00:00,2025-03-12T11:00:00,Zoom - https://zoom.us/j/98765432100,Portfolio walkthrough with Summit team.,False,confirmed,2025-02-28 15:45:00+00:00
2,CAL-A3,Weekly Team Sync,sarah.chen@firma.com,"[sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-11T09:00:00,2025-03-11T09:30:00,Virtual - Microsoft Teams,Standing weekly sync.,True,confirmed,2025-01-06 08:00:00+00:00
3,CAL-A4,Crestview Holdings - DD Meeting,sarah.chen@firma.com,"[sarah.chen@firma.com, patricia.langley@crestv...",2025-03-13T19:00:00Z,2025-03-13T20:30:00Z,DC Office - Main Conference Room,Due diligence deep-dive. Fund VII materials pr...,False,confirmed,2025-03-04 12:00:00+00:00
4,CAL-A5,Investor Update - Pinnacle,james.wu@firma.com,"[james.wu@firma.com, kevin.obrien@pinnaclegp.com]",2025-03-17T11:00:00,2025-03-17T12:00:00,Boston Office - Room 301,Quarterly investor update for Pinnacle Group.,False,confirmed,2025-03-02 14:30:00+00:00
5,CAL-A6,Pinnacle Group - Q1 Update,james.wu@firma.com,"[james.wu@firma.com, kevin.obrien@pinnaclegp.c...",2025-03-17T11:30:00,2025-03-17T12:30:00,Boston Office,Q1 update with Pinnacle Group. Sandra Mills (C...,False,confirmed,2025-03-10 09:15:00+00:00
6,CAL-A7,Internal Pipeline Review,sarah.chen@firma.com,"[sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-14T16:00:00,2025-03-14T17:00:00,HQ - Room 4A,Review active pipeline and upcoming client mee...,True,confirmed,2025-01-15 10:05:00+00:00
7,CAL-A8,Meridian Capital - Follow-up,sarah.chen@firma.com,"[sarah.chen@firma.com, david.park@meridiancap....",2025-03-18T15:00:00,2025-03-18T15:30:00,Zoom,Follow-up re: fee schedule and allocation chan...,False,confirmed,2025-03-11 09:45:00+00:00
8,CAL-A9,Atlas Ventures Lunch,james.wu@firma.com,"[james.wu@firma.com, lisa.tran@atlasvc.com]",2025-03-15T12:00:00,2025-03-15T13:30:00,The Capital Grille - Georgetown,Lunch with Lisa Tran. Exploring infrastructure...,False,confirmed,2025-03-07 16:00:00+00:00
9,CAL-A10,Board Prep - Q1 Materials Review,sarah.chen@firma.com,"[sarah.chen@firma.com, james.wu@firma.com, mic...",2025-03-19T09:00:00,2025-03-19T10:30:00,HQ - Boardroom,Review and finalize Q1 board presentation mate...,False,confirmed,2025-02-28 11:00:00+00:00
10,CAL-A11,Client Reception,priya.sharma@firma.com,[],2025-03-14T18:00:00,2025-03-14T20:00,NaN,NaN,False,tentative,2025-03-13 22:10:00+00:00
11,CAL-A12,Horizon Wealth - Year-End Review,james.wu@firma.com,"[james.wu@firma.com, elena.marcos@horizonwp.com]",2025-03-21T09:00:00,2025-03-21T10:30:00,NYC Office - 12th Floor,Annual review of allocation strategy and alter...,False,confirmed,2025-03-06 14:20:00+00:00
12,CAL-A13,Granite Point - Co-Invest Discussion,sarah.chen@firma.com,"[sarah.chen@firma.com, thomas.grant@granitepoi...",2025-03-21T14:00:00,2025-03-21T15:00:00,Zoom - https://zoom.us/j/11223344,Co-investment opportunity walkthrough for Fund...,False,confirmed,2025-03-11 16:30:00+00:00
13,CAL-A14,LPAC Prep Working Session,priya.sharma@firma.com,"[sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-24T10:00:00,2025-03-24T12:00:00,HQ - Boardroom,Prep session for LP Advisory Committee meeting...,False,confirmed,2025-03-14 11:00:00+00:00
14,CAL-A15,Michael Reeves - Quick Sync,james.wu@firma.com,"[james.wu@firma.com, michael.reeves@evergreenc...",2025-03-25T08:30:00,2025-03-25T08:45:00,NaN,Capital call timing discussion.,False,confirmed,2025-03-19 17:00:00+00:00
15,CAL-A16,Atlas Ventures - Infrastructure Deep Dive,james.wu@firma.com,"[james.wu@firma.com, lisa.tran@atlasvc.com, ra...",2025-03-26T10:00:00,2025-03-26T11:30:00,Conference Room A,Formal infrastructure fund presentation. Raj P...,False,confirmed,2025-03-15 10:00:00+00:00
16,CAL-A17,ESG + Compliance Review,sarah.chen@firma.com,"[sarah.chen@firma.com, karen.white@redwoodinst...",2025-03-27T15:00:00,2025-03-27T16:00:00,Microsoft Teams,Walk through ESG reporting framework and compl...,False,confirmed,2025-03-20 08:30:00+00:00
17,CAL-A18,Weekly Team Sync,sarah.chen@firma.com,"[sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-18T09:00:00,2025-03-18T09:30:00,Virtual - Microsoft Teams,Standing weekly sync.,True,confirmed,2025-01-06 08:00:00+00:00
18,CAL-A19,Fund VII Roadshow Prep,sarah.chen@firma.com,"[sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-28T14:00:00,2025-03-28T16:00:00,HQ - Room 4A,Finalize roadshow materials and talking points...,False,confirmed,2025-03-20 12:00:00+00:00
19,CAL-A20,Fund VII Closing Dinner,james.wu@firma.com,"[james.wu@firma.com, sarah.chen@firma.com, kev...",2025-03-28T19:00:00,2025-03-28T21:30:00,The Palm Restaurant,Celebratory dinner for Fund VII final close.,False,confirmed,2025-03-09 11:00:00+00:00
20,CAL-A21,Crestview Follow-up Call,sarah.chen@firma.com,"[sarah.chen@firma.com, patricia.langley@crestv...",2025-03-25T16:30:00,2025-03-25T17:00:00,Zoom,Follow-up on due diligence questions. Side let...,False,confirmed,2025-03-16 14:45:00+00:00
21,CAL-A22,QBR - Q1 Wrap,sarah.chen@firma.com,"[sarah.chen@firma.com, james.wu@firma.com, pri...",2025-04-01T14:00:00,2025-04-01T16:00:00,HQ - Large Conference Room,"Q1 quarterly business review. Pipeline, AUM, r...",False,confirmed,2025-03-04 09:30:00+00:00

In [18]:
df_cal.shape

(22, 11)

In [20]:
df_cal.isna()

,event_id,title,organizer,attendees,start_time,end_time,location,description,is_recurring,status,created_at
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,True,True,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,True,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False

In [21]:
df_cal.dropna(subset=['description'],inplace=True)
df_cal

,event_id,title,organizer,attendees,start_time,end_time,location,description,is_recurring,status,created_at
0,CAL-A1,Q1 Portfolio Review - Meridian Capital,sarah.chen@firma.com,"[sarah.chen@firma.com, david.park@meridiancap....",2025-03-10T14:00:00,2025-03-10T15:30:00,Conference Room B,Quarterly review of portfolio allocation and p...,False,confirmed,2025-02-27 10:00:00+00:00
1,CAL-A2,Summit Advisors - Portfolio Discussion,sarah.chen@firma.com,"[sarah.chen@firma.com, mark.johnson@summitadv....",2025-03-12T10:00:00,2025-03-12T11:00:00,Zoom - https://zoom.us/j/98765432100,Portfolio walkthrough with Summit team.,False,confirmed,2025-02-28 15:45:00+00:00
2,CAL-A3,Weekly Team Sync,sarah.chen@firma.com,"[sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-11T09:00:00,2025-03-11T09:30:00,Virtual - Microsoft Teams,Standing weekly sync.,True,confirmed,2025-01-06 08:00:00+00:00
3,CAL-A4,Crestview Holdings - DD Meeting,sarah.chen@firma.com,"[sarah.chen@firma.com, patricia.langley@crestv...",2025-03-13T19:00:00Z,2025-03-13T20:30:00Z,DC Office - Main Conference Room,Due diligence deep-dive. Fund VII materials pr...,False,confirmed,2025-03-04 12:00:00+00:00
4,CAL-A5,Investor Update - Pinnacle,james.wu@firma.com,"[james.wu@firma.com, kevin.obrien@pinnaclegp.com]",2025-03-17T11:00:00,2025-03-17T12:00:00,Boston Office - Room 301,Quarterly investor update for Pinnacle Group.,False,confirmed,2025-03-02 14:30:00+00:00
5,CAL-A6,Pinnacle Group - Q1 Update,james.wu@firma.com,"[james.wu@firma.com, kevin.obrien@pinnaclegp.c...",2025-03-17T11:30:00,2025-03-17T12:30:00,Boston Office,Q1 update with Pinnacle Group. Sandra Mills (C...,False,confirmed,2025-03-10 09:15:00+00:00
6,CAL-A7,Internal Pipeline Review,sarah.chen@firma.com,"[sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-14T16:00:00,2025-03-14T17:00:00,HQ - Room 4A,Review active pipeline and upcoming client mee...,True,confirmed,2025-01-15 10:05:00+00:00
7,CAL-A8,Meridian Capital - Follow-up,sarah.chen@firma.com,"[sarah.chen@firma.com, david.park@meridiancap....",2025-03-18T15:00:00,2025-03-18T15:30:00,Zoom,Follow-up re: fee schedule and allocation chan...,False,confirmed,2025-03-11 09:45:00+00:00
8,CAL-A9,Atlas Ventures Lunch,james.wu@firma.com,"[james.wu@firma.com, lisa.tran@atlasvc.com]",2025-03-15T12:00:00,2025-03-15T13:30:00,The Capital Grille - Georgetown,Lunch with Lisa Tran. Exploring infrastructure...,False,confirmed,2025-03-07 16:00:00+00:00
9,CAL-A10,Board Prep - Q1 Materials Review,sarah.chen@firma.com,"[sarah.chen@firma.com, james.wu@firma.com, mic...",2025-03-19T09:00:00,2025-03-19T10:30:00,HQ - Boardroom,Review and finalize Q1 board presentation mate...,False,confirmed,2025-02-28 11:00:00+00:00
11,CAL-A12,Horizon Wealth - Year-End Review,james.wu@firma.com,"[james.wu@firma.com, elena.marcos@horizonwp.com]",2025-03-21T09:00:00,2025-03-21T10:30:00,NYC Office - 12th Floor,Annual review of allocation strategy and alter...,False,confirmed,2025-03-06 14:20:00+00:00
12,CAL-A13,Granite Point - Co-Invest Discussion,sarah.chen@firma.com,"[sarah.chen@firma.com, thomas.grant@granitepoi...",2025-03-21T14:00:00,2025-03-21T15:00:00,Zoom - https://zoom.us/j/11223344,Co-investment opportunity walkthrough for Fund...,False,confirmed,2025-03-11 16:30:00+00:00
13,CAL-A14,LPAC Prep Working Session,priya.sharma@firma.com,"[sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-24T10:00:00,2025-03-24T12:00:00,HQ - Boardroom,Prep session for LP Advisory Committee meeting...,False,confirmed,2025-03-14 11:00:00+00:00
14,CAL-A15,Michael Reeves - Quick Sync,james.wu@firma.com,"[james.wu@firma.com, michael.reeves@evergreenc...",2025-03-25T08:30:00,2025-03-25T08:45:00,NaN,Capital call timing discussion.,False,confirmed,2025-03-19 17:00:00+00:00
15,CAL-A16,Atlas Ventures - Infrastructure Deep Dive,james.wu@firma.com,"[james.wu@firma.com, lisa.tran@atlasvc.com, ra...",2025-03-26T10:00:00,2025-03-26T11:30:00,Conference Room A,Formal infrastructure fund presentation. Raj P...,False,confirmed,2025-03-15 10:00:00+00:00
16,CAL-A17,ESG + Compliance Review,sarah.chen@firma.com,"[sarah.chen@firma.com, karen.white@redwoodinst...",2025-03-27T15:00:00,2025-03-27T16:00:00,Microsoft Teams,Walk through ESG reporting framework and compl...,False,confirmed,2025-03-20 08:30:00+00:00
17,CAL-A18,Weekly Team Sync,sarah.chen@firma.com,"[sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-18T09:00:00,2025-03-18T09:30:00,Virtual - Microsoft Teams,Standing weekly sync.,True,confirmed,2025-01-06 08:00:00+00:00
18,CAL-A19,Fund VII Roadshow Prep,sarah.chen@firma.com,"[sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-28T14:00:00,2025-03-28T16:00:00,HQ - Room 4A,Finalize roadshow materials and talking points...,False,confirmed,2025-03-20 12:00:00+00:00
19,CAL-A20,Fund VII Closing Dinner,james.wu@firma.com,"[james.wu@firma.com, sarah.chen@firma.com, kev...",2025-03-28T19:00:00,2025-03-28T21:30:00,The Palm Restaurant,Celebratory dinner for Fund VII final close.,False,confirmed,2025-03-09 11:00:00+00:00
20,CAL-A21,Crestview Follow-up Call,sarah.chen@firma.com,"[sarah.chen@firma.com, patricia.langley@crestv...",2025-03-25T16:30:00,2025-03-25T17:00:00,Zoom,Follow-up on due diligence questions. Side let...,False,confirmed,2025-03-16 14:45:00+00:00
21,CAL-A22,QBR - Q1 Wrap,sarah.chen@firma.com,"[sarah.chen@firma.com, james.wu@firma.com, pri...",2025-04-01T14:00:00,2025-04-01T16:00:00,HQ - Large Conference Room,"Q1 quarterly business review. Pipeline, AUM, r...",False,confirmed,2025-03-04 09:30:00+00:00

In [39]:
df_cal[df_cal['description']=='Standing weekly sync.']

,event_id,title,organizer,attendees,start_time,end_time,location,description,is_recurring,status,created_at
2,CAL-A3,Weekly Team Sync,sarah.chen@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-11T09:00:00,2025-03-11T09:30:00,Virtual - Microsoft Teams,Standing weekly sync.,True,confirmed,2025-01-06 08:00:00+00:00
17,CAL-A18,Weekly Team Sync,sarah.chen@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-18T09:00:00,2025-03-18T09:30:00,Virtual - Microsoft Teams,Standing weekly sync.,True,confirmed,2025-01-06 08:00:00+00:00

In [24]:
df_cal.columns

Index(['event_id', 'title', 'organizer', 'attendees', 'start_time', 'end_time',
       'location', 'description', 'is_recurring', 'status', 'created_at'],
      dtype='str')

In [27]:
duplicates = df_cal[df_cal.duplicated(subset=['title', 'organizer', 'start_time', 'end_time',
       'location', 'description', 'is_recurring', 'status'])]

In [28]:
duplicates

Empty DataFrame
Columns: [event_id, title, organizer, attendees, start_time, end_time, location, description, is_recurring, status, created_at]
Index: []

In [ ]:
from rapidfuzz import fuzz

In [ ]:
df_final= pd.DataFrame()

In [ ]:
df_final['tital_smilarity'] = fuzz.ratio(crm_subject, cal_title)

In [37]:
df_cal.drop_duplicates(subset=['title', 'organizer', 'attendees', 'start_time', 'end_time',
       'location', 'description', 'is_recurring', 'status', 'created_at'],keep='last',inplace=True)
df_cal

,event_id,title,organizer,attendees,start_time,end_time,location,description,is_recurring,status,created_at
0,CAL-A1,Q1 Portfolio Review - Meridian Capital,sarah.chen@firma.com,"(sarah.chen@firma.com, david.park@meridiancap....",2025-03-10T14:00:00,2025-03-10T15:30:00,Conference Room B,Quarterly review of portfolio allocation and p...,False,confirmed,2025-02-27 10:00:00+00:00
1,CAL-A2,Summit Advisors - Portfolio Discussion,sarah.chen@firma.com,"(sarah.chen@firma.com, mark.johnson@summitadv....",2025-03-12T10:00:00,2025-03-12T11:00:00,Zoom - https://zoom.us/j/98765432100,Portfolio walkthrough with Summit team.,False,confirmed,2025-02-28 15:45:00+00:00
2,CAL-A3,Weekly Team Sync,sarah.chen@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-11T09:00:00,2025-03-11T09:30:00,Virtual - Microsoft Teams,Standing weekly sync.,True,confirmed,2025-01-06 08:00:00+00:00
3,CAL-A4,Crestview Holdings - DD Meeting,sarah.chen@firma.com,"(sarah.chen@firma.com, patricia.langley@crestv...",2025-03-13T19:00:00Z,2025-03-13T20:30:00Z,DC Office - Main Conference Room,Due diligence deep-dive. Fund VII materials pr...,False,confirmed,2025-03-04 12:00:00+00:00
4,CAL-A5,Investor Update - Pinnacle,james.wu@firma.com,"(james.wu@firma.com, kevin.obrien@pinnaclegp.com)",2025-03-17T11:00:00,2025-03-17T12:00:00,Boston Office - Room 301,Quarterly investor update for Pinnacle Group.,False,confirmed,2025-03-02 14:30:00+00:00
5,CAL-A6,Pinnacle Group - Q1 Update,james.wu@firma.com,"(james.wu@firma.com, kevin.obrien@pinnaclegp.c...",2025-03-17T11:30:00,2025-03-17T12:30:00,Boston Office,Q1 update with Pinnacle Group. Sandra Mills (C...,False,confirmed,2025-03-10 09:15:00+00:00
6,CAL-A7,Internal Pipeline Review,sarah.chen@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-14T16:00:00,2025-03-14T17:00:00,HQ - Room 4A,Review active pipeline and upcoming client mee...,True,confirmed,2025-01-15 10:05:00+00:00
7,CAL-A8,Meridian Capital - Follow-up,sarah.chen@firma.com,"(sarah.chen@firma.com, david.park@meridiancap....",2025-03-18T15:00:00,2025-03-18T15:30:00,Zoom,Follow-up re: fee schedule and allocation chan...,False,confirmed,2025-03-11 09:45:00+00:00
8,CAL-A9,Atlas Ventures Lunch,james.wu@firma.com,"(james.wu@firma.com, lisa.tran@atlasvc.com)",2025-03-15T12:00:00,2025-03-15T13:30:00,The Capital Grille - Georgetown,Lunch with Lisa Tran. Exploring infrastructure...,False,confirmed,2025-03-07 16:00:00+00:00
9,CAL-A10,Board Prep - Q1 Materials Review,sarah.chen@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, mic...",2025-03-19T09:00:00,2025-03-19T10:30:00,HQ - Boardroom,Review and finalize Q1 board presentation mate...,False,confirmed,2025-02-28 11:00:00+00:00
11,CAL-A12,Horizon Wealth - Year-End Review,james.wu@firma.com,"(james.wu@firma.com, elena.marcos@horizonwp.com)",2025-03-21T09:00:00,2025-03-21T10:30:00,NYC Office - 12th Floor,Annual review of allocation strategy and alter...,False,confirmed,2025-03-06 14:20:00+00:00
12,CAL-A13,Granite Point - Co-Invest Discussion,sarah.chen@firma.com,"(sarah.chen@firma.com, thomas.grant@granitepoi...",2025-03-21T14:00:00,2025-03-21T15:00:00,Zoom - https://zoom.us/j/11223344,Co-investment opportunity walkthrough for Fund...,False,confirmed,2025-03-11 16:30:00+00:00
13,CAL-A14,LPAC Prep Working Session,priya.sharma@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-24T10:00:00,2025-03-24T12:00:00,HQ - Boardroom,Prep session for LP Advisory Committee meeting...,False,confirmed,2025-03-14 11:00:00+00:00
14,CAL-A15,Michael Reeves - Quick Sync,james.wu@firma.com,"(james.wu@firma.com, michael.reeves@evergreenc...",2025-03-25T08:30:00,2025-03-25T08:45:00,NaN,Capital call timing discussion.,False,confirmed,2025-03-19 17:00:00+00:00
15,CAL-A16,Atlas Ventures - Infrastructure Deep Dive,james.wu@firma.com,"(james.wu@firma.com, lisa.tran@atlasvc.com, ra...",2025-03-26T10:00:00,2025-03-26T11:30:00,Conference Room A,Formal infrastructure fund presentation. Raj P...,False,confirmed,2025-03-15 10:00:00+00:00
16,CAL-A17,ESG + Compliance Review,sarah.chen@firma.com,"(sarah.chen@firma.com, karen.white@redwoodinst...",2025-03-27T15:00:00,2025-03-27T16:00:00,Microsoft Teams,Walk through ESG reporting framework and compl...,False,confirmed,2025-03-20 08:30:00+00:00
17,CAL-A18,Weekly Team Sync,sarah.chen@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-18T09:00:00,2025-03-18T09:30:00,Virtual - Microsoft Teams,Standing weekly sync.,True,confirmed,2025-01-06 08:00:00+00:00
18,CAL-A19,Fund VII Roadshow Prep,sarah.chen@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-28T14:00:00,2025-03-28T16:00:00,HQ - Room 4A,Finalize roadshow materials and talking points...,False,confirmed,2025-03-20 12:00:00+00:00
19,CAL-A20,Fund VII Closing Dinner,james.wu@firma.com,"(james.wu@firma.com, sarah.chen@firma.com, kev...",2025-03-28T19:00:00,2025-03-28T21:30:00,The Palm Restaurant,Celebratory dinner for Fund VII final close.,False,confirmed,2025-03-09 11:00:00+00:00
20,CAL-A21,Crestview Follow-up Call,sarah.chen@firma.com,"(sarah.chen@firma.com, patricia.langley@crestv...",2025-03-25T16:30:00,2025-03-25T17:00:00,Zoom,Follow-up on due diligence questions. Side let...,False,confirmed,2025-03-16 14:45:00+00:00
21,CAL-A22,QBR - Q1 Wrap,sarah.chen@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, pri...",2025-04-01T14:00:00,2025-04-01T16:00:00,HQ - Large Conference Room,"Q1 quarterly business review. Pipeline, AUM, r...",False,confirmed,2025-03-04 09:30:00+00:00

In [36]:
df_cal['attendees']=df_cal['attendees'].apply(tuple)
df_cal

,event_id,title,organizer,attendees,start_time,end_time,location,description,is_recurring,status,created_at
0,CAL-A1,Q1 Portfolio Review - Meridian Capital,sarah.chen@firma.com,"(sarah.chen@firma.com, david.park@meridiancap....",2025-03-10T14:00:00,2025-03-10T15:30:00,Conference Room B,Quarterly review of portfolio allocation and p...,False,confirmed,2025-02-27 10:00:00+00:00
1,CAL-A2,Summit Advisors - Portfolio Discussion,sarah.chen@firma.com,"(sarah.chen@firma.com, mark.johnson@summitadv....",2025-03-12T10:00:00,2025-03-12T11:00:00,Zoom - https://zoom.us/j/98765432100,Portfolio walkthrough with Summit team.,False,confirmed,2025-02-28 15:45:00+00:00
2,CAL-A3,Weekly Team Sync,sarah.chen@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-11T09:00:00,2025-03-11T09:30:00,Virtual - Microsoft Teams,Standing weekly sync.,True,confirmed,2025-01-06 08:00:00+00:00
3,CAL-A4,Crestview Holdings - DD Meeting,sarah.chen@firma.com,"(sarah.chen@firma.com, patricia.langley@crestv...",2025-03-13T19:00:00Z,2025-03-13T20:30:00Z,DC Office - Main Conference Room,Due diligence deep-dive. Fund VII materials pr...,False,confirmed,2025-03-04 12:00:00+00:00
4,CAL-A5,Investor Update - Pinnacle,james.wu@firma.com,"(james.wu@firma.com, kevin.obrien@pinnaclegp.com)",2025-03-17T11:00:00,2025-03-17T12:00:00,Boston Office - Room 301,Quarterly investor update for Pinnacle Group.,False,confirmed,2025-03-02 14:30:00+00:00
5,CAL-A6,Pinnacle Group - Q1 Update,james.wu@firma.com,"(james.wu@firma.com, kevin.obrien@pinnaclegp.c...",2025-03-17T11:30:00,2025-03-17T12:30:00,Boston Office,Q1 update with Pinnacle Group. Sandra Mills (C...,False,confirmed,2025-03-10 09:15:00+00:00
6,CAL-A7,Internal Pipeline Review,sarah.chen@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-14T16:00:00,2025-03-14T17:00:00,HQ - Room 4A,Review active pipeline and upcoming client mee...,True,confirmed,2025-01-15 10:05:00+00:00
7,CAL-A8,Meridian Capital - Follow-up,sarah.chen@firma.com,"(sarah.chen@firma.com, david.park@meridiancap....",2025-03-18T15:00:00,2025-03-18T15:30:00,Zoom,Follow-up re: fee schedule and allocation chan...,False,confirmed,2025-03-11 09:45:00+00:00
8,CAL-A9,Atlas Ventures Lunch,james.wu@firma.com,"(james.wu@firma.com, lisa.tran@atlasvc.com)",2025-03-15T12:00:00,2025-03-15T13:30:00,The Capital Grille - Georgetown,Lunch with Lisa Tran. Exploring infrastructure...,False,confirmed,2025-03-07 16:00:00+00:00
9,CAL-A10,Board Prep - Q1 Materials Review,sarah.chen@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, mic...",2025-03-19T09:00:00,2025-03-19T10:30:00,HQ - Boardroom,Review and finalize Q1 board presentation mate...,False,confirmed,2025-02-28 11:00:00+00:00
11,CAL-A12,Horizon Wealth - Year-End Review,james.wu@firma.com,"(james.wu@firma.com, elena.marcos@horizonwp.com)",2025-03-21T09:00:00,2025-03-21T10:30:00,NYC Office - 12th Floor,Annual review of allocation strategy and alter...,False,confirmed,2025-03-06 14:20:00+00:00
12,CAL-A13,Granite Point - Co-Invest Discussion,sarah.chen@firma.com,"(sarah.chen@firma.com, thomas.grant@granitepoi...",2025-03-21T14:00:00,2025-03-21T15:00:00,Zoom - https://zoom.us/j/11223344,Co-investment opportunity walkthrough for Fund...,False,confirmed,2025-03-11 16:30:00+00:00
13,CAL-A14,LPAC Prep Working Session,priya.sharma@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-24T10:00:00,2025-03-24T12:00:00,HQ - Boardroom,Prep session for LP Advisory Committee meeting...,False,confirmed,2025-03-14 11:00:00+00:00
14,CAL-A15,Michael Reeves - Quick Sync,james.wu@firma.com,"(james.wu@firma.com, michael.reeves@evergreenc...",2025-03-25T08:30:00,2025-03-25T08:45:00,NaN,Capital call timing discussion.,False,confirmed,2025-03-19 17:00:00+00:00
15,CAL-A16,Atlas Ventures - Infrastructure Deep Dive,james.wu@firma.com,"(james.wu@firma.com, lisa.tran@atlasvc.com, ra...",2025-03-26T10:00:00,2025-03-26T11:30:00,Conference Room A,Formal infrastructure fund presentation. Raj P...,False,confirmed,2025-03-15 10:00:00+00:00
16,CAL-A17,ESG + Compliance Review,sarah.chen@firma.com,"(sarah.chen@firma.com, karen.white@redwoodinst...",2025-03-27T15:00:00,2025-03-27T16:00:00,Microsoft Teams,Walk through ESG reporting framework and compl...,False,confirmed,2025-03-20 08:30:00+00:00
17,CAL-A18,Weekly Team Sync,sarah.chen@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-18T09:00:00,2025-03-18T09:30:00,Virtual - Microsoft Teams,Standing weekly sync.,True,confirmed,2025-01-06 08:00:00+00:00
18,CAL-A19,Fund VII Roadshow Prep,sarah.chen@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-28T14:00:00,2025-03-28T16:00:00,HQ - Room 4A,Finalize roadshow materials and talking points...,False,confirmed,2025-03-20 12:00:00+00:00
19,CAL-A20,Fund VII Closing Dinner,james.wu@firma.com,"(james.wu@firma.com, sarah.chen@firma.com, kev...",2025-03-28T19:00:00,2025-03-28T21:30:00,The Palm Restaurant,Celebratory dinner for Fund VII final close.,False,confirmed,2025-03-09 11:00:00+00:00
20,CAL-A21,Crestview Follow-up Call,sarah.chen@firma.com,"(sarah.chen@firma.com, patricia.langley@crestv...",2025-03-25T16:30:00,2025-03-25T17:00:00,Zoom,Follow-up on due diligence questions. Side let...,False,confirmed,2025-03-16 14:45:00+00:00
21,CAL-A22,QBR - Q1 Wrap,sarah.chen@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, pri...",2025-04-01T14:00:00,2025-04-01T16:00:00,HQ - Large Conference Room,"Q1 quarterly business review. Pipeline, AUM, r...",False,confirmed,2025-03-04 09:30:00+00:00

In [55]:
df_cal.dtypes

event_id                        str
title                           str
organizer                       str
attendees                    object
start_time                      str
end_time                        str
location                        str
description                     str
is_recurring                   bool
status                          str
created_at      datetime64[us, UTC]
dtype: object

In [60]:
df_cal['date']=pd.to_datetime(df_cal['start_time'],utc=True,format='ISO8601').dt.date
df_cal['date']

0     2025-03-10
1     2025-03-12
2     2025-03-11
3     2025-03-13
4     2025-03-17
5     2025-03-17
6     2025-03-14
7     2025-03-18
8     2025-03-15
9     2025-03-19
11    2025-03-21
12    2025-03-21
13    2025-03-24
14    2025-03-25
15    2025-03-26
16    2025-03-27
17    2025-03-18
18    2025-03-28
19    2025-03-28
20    2025-03-25
21    2025-04-01
Name: date, dtype: object

In [61]:
df_cal.columns

Index(['event_id', 'title', 'organizer', 'attendees', 'start_time', 'end_time',
       'location', 'description', 'is_recurring', 'status', 'created_at',
       'date'],
      dtype='str')

In [31]:
df_cal.shape

(21, 11)

In [38]:
df_cal.drop_duplicates(subset=['title', 'organizer', 'attendees', 'start_time', 'end_time',
       'location', 'description', 'is_recurring', 'status', 'created_at'],keep='last',inplace=True)
df_cal

,event_id,title,organizer,attendees,start_time,end_time,location,description,is_recurring,status,created_at
0,CAL-A1,Q1 Portfolio Review - Meridian Capital,sarah.chen@firma.com,"(sarah.chen@firma.com, david.park@meridiancap....",2025-03-10T14:00:00,2025-03-10T15:30:00,Conference Room B,Quarterly review of portfolio allocation and p...,False,confirmed,2025-02-27 10:00:00+00:00
1,CAL-A2,Summit Advisors - Portfolio Discussion,sarah.chen@firma.com,"(sarah.chen@firma.com, mark.johnson@summitadv....",2025-03-12T10:00:00,2025-03-12T11:00:00,Zoom - https://zoom.us/j/98765432100,Portfolio walkthrough with Summit team.,False,confirmed,2025-02-28 15:45:00+00:00
2,CAL-A3,Weekly Team Sync,sarah.chen@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-11T09:00:00,2025-03-11T09:30:00,Virtual - Microsoft Teams,Standing weekly sync.,True,confirmed,2025-01-06 08:00:00+00:00
3,CAL-A4,Crestview Holdings - DD Meeting,sarah.chen@firma.com,"(sarah.chen@firma.com, patricia.langley@crestv...",2025-03-13T19:00:00Z,2025-03-13T20:30:00Z,DC Office - Main Conference Room,Due diligence deep-dive. Fund VII materials pr...,False,confirmed,2025-03-04 12:00:00+00:00
4,CAL-A5,Investor Update - Pinnacle,james.wu@firma.com,"(james.wu@firma.com, kevin.obrien@pinnaclegp.com)",2025-03-17T11:00:00,2025-03-17T12:00:00,Boston Office - Room 301,Quarterly investor update for Pinnacle Group.,False,confirmed,2025-03-02 14:30:00+00:00
5,CAL-A6,Pinnacle Group - Q1 Update,james.wu@firma.com,"(james.wu@firma.com, kevin.obrien@pinnaclegp.c...",2025-03-17T11:30:00,2025-03-17T12:30:00,Boston Office,Q1 update with Pinnacle Group. Sandra Mills (C...,False,confirmed,2025-03-10 09:15:00+00:00
6,CAL-A7,Internal Pipeline Review,sarah.chen@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-14T16:00:00,2025-03-14T17:00:00,HQ - Room 4A,Review active pipeline and upcoming client mee...,True,confirmed,2025-01-15 10:05:00+00:00
7,CAL-A8,Meridian Capital - Follow-up,sarah.chen@firma.com,"(sarah.chen@firma.com, david.park@meridiancap....",2025-03-18T15:00:00,2025-03-18T15:30:00,Zoom,Follow-up re: fee schedule and allocation chan...,False,confirmed,2025-03-11 09:45:00+00:00
8,CAL-A9,Atlas Ventures Lunch,james.wu@firma.com,"(james.wu@firma.com, lisa.tran@atlasvc.com)",2025-03-15T12:00:00,2025-03-15T13:30:00,The Capital Grille - Georgetown,Lunch with Lisa Tran. Exploring infrastructure...,False,confirmed,2025-03-07 16:00:00+00:00
9,CAL-A10,Board Prep - Q1 Materials Review,sarah.chen@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, mic...",2025-03-19T09:00:00,2025-03-19T10:30:00,HQ - Boardroom,Review and finalize Q1 board presentation mate...,False,confirmed,2025-02-28 11:00:00+00:00
11,CAL-A12,Horizon Wealth - Year-End Review,james.wu@firma.com,"(james.wu@firma.com, elena.marcos@horizonwp.com)",2025-03-21T09:00:00,2025-03-21T10:30:00,NYC Office - 12th Floor,Annual review of allocation strategy and alter...,False,confirmed,2025-03-06 14:20:00+00:00
12,CAL-A13,Granite Point - Co-Invest Discussion,sarah.chen@firma.com,"(sarah.chen@firma.com, thomas.grant@granitepoi...",2025-03-21T14:00:00,2025-03-21T15:00:00,Zoom - https://zoom.us/j/11223344,Co-investment opportunity walkthrough for Fund...,False,confirmed,2025-03-11 16:30:00+00:00
13,CAL-A14,LPAC Prep Working Session,priya.sharma@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-24T10:00:00,2025-03-24T12:00:00,HQ - Boardroom,Prep session for LP Advisory Committee meeting...,False,confirmed,2025-03-14 11:00:00+00:00
14,CAL-A15,Michael Reeves - Quick Sync,james.wu@firma.com,"(james.wu@firma.com, michael.reeves@evergreenc...",2025-03-25T08:30:00,2025-03-25T08:45:00,NaN,Capital call timing discussion.,False,confirmed,2025-03-19 17:00:00+00:00
15,CAL-A16,Atlas Ventures - Infrastructure Deep Dive,james.wu@firma.com,"(james.wu@firma.com, lisa.tran@atlasvc.com, ra...",2025-03-26T10:00:00,2025-03-26T11:30:00,Conference Room A,Formal infrastructure fund presentation. Raj P...,False,confirmed,2025-03-15 10:00:00+00:00
16,CAL-A17,ESG + Compliance Review,sarah.chen@firma.com,"(sarah.chen@firma.com, karen.white@redwoodinst...",2025-03-27T15:00:00,2025-03-27T16:00:00,Microsoft Teams,Walk through ESG reporting framework and compl...,False,confirmed,2025-03-20 08:30:00+00:00
17,CAL-A18,Weekly Team Sync,sarah.chen@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-18T09:00:00,2025-03-18T09:30:00,Virtual - Microsoft Teams,Standing weekly sync.,True,confirmed,2025-01-06 08:00:00+00:00
18,CAL-A19,Fund VII Roadshow Prep,sarah.chen@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-28T14:00:00,2025-03-28T16:00:00,HQ - Room 4A,Finalize roadshow materials and talking points...,False,confirmed,2025-03-20 12:00:00+00:00
19,CAL-A20,Fund VII Closing Dinner,james.wu@firma.com,"(james.wu@firma.com, sarah.chen@firma.com, kev...",2025-03-28T19:00:00,2025-03-28T21:30:00,The Palm Restaurant,Celebratory dinner for Fund VII final close.,False,confirmed,2025-03-09 11:00:00+00:00
20,CAL-A21,Crestview Follow-up Call,sarah.chen@firma.com,"(sarah.chen@firma.com, patricia.langley@crestv...",2025-03-25T16:30:00,2025-03-25T17:00:00,Zoom,Follow-up on due diligence questions. Side let...,False,confirmed,2025-03-16 14:45:00+00:00
21,CAL-A22,QBR - Q1 Wrap,sarah.chen@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, pri...",2025-04-01T14:00:00,2025-04-01T16:00:00,HQ - Large Conference Room,"Q1 quarterly business review. Pipeline, AUM, r...",False,confirmed,2025-03-04 09:30:00+00:00

In [45]:
duplicates = df_cal[df_cal.duplicated(subset=['title', 'organizer', 'attendees', 'start_time', 'end_time',
       'location', 'description', 'is_recurring', 'status', 'created_at'])]

In [46]:
duplicates

Empty DataFrame
Columns: [event_id, title, organizer, attendees, start_time, end_time, location, description, is_recurring, status, created_at]
Index: []

In [44]:
df_cal[df_cal['description']=='Standing weekly sync.']

,event_id,title,organizer,attendees,start_time,end_time,location,description,is_recurring,status,created_at
2,CAL-A3,Weekly Team Sync,sarah.chen@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-11T09:00:00,2025-03-11T09:30:00,Virtual - Microsoft Teams,Standing weekly sync.,True,confirmed,2025-01-06 08:00:00+00:00
17,CAL-A18,Weekly Team Sync,sarah.chen@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, pri...",2025-03-18T09:00:00,2025-03-18T09:30:00,Virtual - Microsoft Teams,Standing weekly sync.,True,confirmed,2025-01-06 08:00:00+00:00

In [47]:
df_crm.columns

Index(['crm_id', 'subject', 'client_name', 'client_company',
       'relationship_owner', 'meeting_date', 'meeting_time', 'meeting_type',
       'location', 'notes', 'status', 'created_at'],
      dtype='str')

In [49]:
df_crm

,crm_id,subject,client_name,client_company,relationship_owner,meeting_date,meeting_time,meeting_type,location,notes,status,created_at
0,CRM-1001,Q1 Portfolio Review,David Park,Meridian Capital,Sarah Chen,2025-03-10,2026-05-21 14:00:00,In-Person,HQ - Conference Room B,Review Q1 allocation strategy. David requested...,Completed,2025-02-28 09:15:00+00:00
1,CRM-1002,Portfolio Walkthrough,Mark Johnson,Summit Advisors,Sarah Chen,2025-03-12,2026-05-21 10:00:00,In-Person,NYC Office - 30th Floor,Walk through current portfolio positioning and...,Confirmed,2025-03-01 11:30:00+00:00
2,CRM-1003,Introductory Call,Rachel Torres,Lakeshore Partners,James Wu,2025-03-14,2026-05-21 15:00:00,Virtual,NaN,First touch. Referred by Tom Nakamura at Bridg...,Scheduled,2025-03-10 14:00:00+00:00
3,CRM-1004,Due Diligence Review,Patricia Langley,Crestview Holdings,Sarah Chen,2025-03-13,2026-05-21 14:00:00,In-Person,DC Office - Main Conference Room,DD deep-dive on Fund VII. Legal team joining.,Confirmed,2025-03-05 08:45:00+00:00
4,CRM-1005,Investor Update,Kevin O'Brien,Pinnacle Group,James Wu,2025-03-17,2026-05-21 11:00:00,In-Person,Boston Office,Quarterly update. Kevin may bring CIO.,Confirmed,2025-03-03 16:20:00+00:00
5,CRM-1006,Pipeline Review,NaN,NaN,Sarah Chen,2025-03-14,2026-05-21 16:00:00,Internal,HQ - Room 4A,Weekly pipeline review with full team.,Confirmed,2025-01-15 10:00:00+00:00
6,CRM-1007,Follow-up Discussion,David Park,Meridian Capital,Sarah Chen,2025-03-18,NaT,Virtual,NaN,Follow up on fee schedule questions from Q1 re...,Scheduled,2025-03-11 09:30:00+00:00
7,CRM-1008,Lunch Meeting,Lisa Tran,Atlas Ventures,James Wu,03-15/2025,2026-05-21 12:00:00,In-Person,The Capital Grille - Georgetown,Relationship building. Lisa interested in infr...,Confirmed,2025-03-08 13:00:00+00:00
8,CRM-1009,Board Prep Session,NaN,NaN,Sarah Chen,2025-03-19,2026-05-21 09:00:00,Internal,HQ - Boardroom,Prep Q1 board materials. CANCELLED — reschedul...,Cancelled,2025-03-01 08:00:00+00:00
9,CRM-1010,Strategy Discussion,Alan Whitfield,Northwind Investments,James Wu,2025-03-20,2026-05-21 10:00:00,Virtual,Microsoft Teams,,Tentative,2025-03-14 17:30:00+00:00
10,CRM-1011,Annual Allocation Review,Elena Marcos,Horizon Wealth Partners,James Wu,2025-03-21,2026-05-21 09:00:00,In-Person,NYC Office,Full-year allocation review. Elena wants to di...,Confirmed,2025-03-07 10:15:00+00:00
11,CRM-1012,Co-Investment Opportunity,Thomas Grant,Granite Point Capital,Sarah Chen,2025-03-21,2026-05-21 14:00:00,Virtual,Zoom,Present co-invest opportunity in Fund VII deal...,Confirmed,2025-03-12 11:00:00+00:00
12,CRM-1013,LP Advisory Committee Prep,NaN,NaN,Sarah Chen,2025-03-24,2026-05-21 10:00:00,Internal,HQ - Boardroom,Prepare materials and talking points for upcom...,Confirmed,2025-03-15 09:00:00+00:00
13,CRM-1014,Quick Check-in,Michael Reeves,Evergreen Capital,James Wu,2025-03-25,2026-05-21 08:30:00,Virtual,NaN,Brief call re: capital call timing for Fund VI...,Confirmed,2025-03-20 14:00:00+00:00
14,CRM-1015,Infrastructure Fund Pitch,Lisa Tran,Atlas Ventures,James Wu,2025-03-26,2026-05-21 10:00:00,In-Person,HQ - Conference Room A,Formal pitch for Infra V. Follow-up from March...,Confirmed,2025-03-16 08:30:00+00:00
15,CRM-1016,ESG Compliance Discussion,Karen White,Redwood Institutional,Sarah Chen,2025-03-27,2026-05-21 13:00:00,Virtual,Microsoft Teams,Karen has ESG reporting requirements for their...,Confirmed,2025-03-18 09:45:00+00:00
16,CRM-1017,Closing Dinner,Multiple,Fund VII Investors,James Wu,2025-03-28,2026-05-21 19:00:00,In-Person,The Palm - DC,Celebratory dinner for Fund VII final close. 1...,Confirmed,2025-03-10 16:00:00+00:00
17,CRM-1018,Follow-up Call,Patricia Langley,Crestview Holdings,Sarah Chen,2025-03-25,2026-05-21 16:30:00,Virtual,NaN,Follow up on DD questions from 3/13 meeting. P...,Confirmed,2025-03-17 10:20:00+00:00
18,CRM-1019,Quarterly Business Review,NaN,NaN,Sarah Chen,2025-04-01,2026-05-21 14:00:00,Internal,HQ - Large Conference Room,"Q1 wrap. Review pipeline, AUM growth, client r...",Confirmed,2025-03-05 12:00:00+00:00
19,CRM-1020,Northwind - Fund VII Interest,Alan Whitfield,Northwind Investments,James Wu,2025-04-02,2026-05-21 11:00:00,In-Person,NYC Office - 30th Floor,Deep dive on Fund VII. Alan indicated potentia...,Tentative,2025-03-21 15:00:00+00:00

In [48]:
df_cal.columns

Index(['event_id', 'title', 'organizer', 'attendees', 'start_time', 'end_time',
       'location', 'description', 'is_recurring', 'status', 'created_at'],
      dtype='str')

In [62]:
df_cal_sub=df_cal[['event_id','title','organizer','attendees','description','date']]

In [63]:
df_cal_sub

,event_id,title,organizer,attendees,description,date
0,CAL-A1,Q1 Portfolio Review - Meridian Capital,sarah.chen@firma.com,"(sarah.chen@firma.com, david.park@meridiancap....",Quarterly review of portfolio allocation and p...,2025-03-10
1,CAL-A2,Summit Advisors - Portfolio Discussion,sarah.chen@firma.com,"(sarah.chen@firma.com, mark.johnson@summitadv....",Portfolio walkthrough with Summit team.,2025-03-12
2,CAL-A3,Weekly Team Sync,sarah.chen@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, pri...",Standing weekly sync.,2025-03-11
3,CAL-A4,Crestview Holdings - DD Meeting,sarah.chen@firma.com,"(sarah.chen@firma.com, patricia.langley@crestv...",Due diligence deep-dive. Fund VII materials pr...,2025-03-13
4,CAL-A5,Investor Update - Pinnacle,james.wu@firma.com,"(james.wu@firma.com, kevin.obrien@pinnaclegp.com)",Quarterly investor update for Pinnacle Group.,2025-03-17
5,CAL-A6,Pinnacle Group - Q1 Update,james.wu@firma.com,"(james.wu@firma.com, kevin.obrien@pinnaclegp.c...",Q1 update with Pinnacle Group. Sandra Mills (C...,2025-03-17
6,CAL-A7,Internal Pipeline Review,sarah.chen@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, pri...",Review active pipeline and upcoming client mee...,2025-03-14
7,CAL-A8,Meridian Capital - Follow-up,sarah.chen@firma.com,"(sarah.chen@firma.com, david.park@meridiancap....",Follow-up re: fee schedule and allocation chan...,2025-03-18
8,CAL-A9,Atlas Ventures Lunch,james.wu@firma.com,"(james.wu@firma.com, lisa.tran@atlasvc.com)",Lunch with Lisa Tran. Exploring infrastructure...,2025-03-15
9,CAL-A10,Board Prep - Q1 Materials Review,sarah.chen@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, mic...",Review and finalize Q1 board presentation mate...,2025-03-19
11,CAL-A12,Horizon Wealth - Year-End Review,james.wu@firma.com,"(james.wu@firma.com, elena.marcos@horizonwp.com)",Annual review of allocation strategy and alter...,2025-03-21
12,CAL-A13,Granite Point - Co-Invest Discussion,sarah.chen@firma.com,"(sarah.chen@firma.com, thomas.grant@granitepoi...",Co-investment opportunity walkthrough for Fund...,2025-03-21
13,CAL-A14,LPAC Prep Working Session,priya.sharma@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, pri...",Prep session for LP Advisory Committee meeting...,2025-03-24
14,CAL-A15,Michael Reeves - Quick Sync,james.wu@firma.com,"(james.wu@firma.com, michael.reeves@evergreenc...",Capital call timing discussion.,2025-03-25
15,CAL-A16,Atlas Ventures - Infrastructure Deep Dive,james.wu@firma.com,"(james.wu@firma.com, lisa.tran@atlasvc.com, ra...",Formal infrastructure fund presentation. Raj P...,2025-03-26
16,CAL-A17,ESG + Compliance Review,sarah.chen@firma.com,"(sarah.chen@firma.com, karen.white@redwoodinst...",Walk through ESG reporting framework and compl...,2025-03-27
17,CAL-A18,Weekly Team Sync,sarah.chen@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, pri...",Standing weekly sync.,2025-03-18
18,CAL-A19,Fund VII Roadshow Prep,sarah.chen@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, pri...",Finalize roadshow materials and talking points...,2025-03-28
19,CAL-A20,Fund VII Closing Dinner,james.wu@firma.com,"(james.wu@firma.com, sarah.chen@firma.com, kev...",Celebratory dinner for Fund VII final close.,2025-03-28
20,CAL-A21,Crestview Follow-up Call,sarah.chen@firma.com,"(sarah.chen@firma.com, patricia.langley@crestv...",Follow-up on due diligence questions. Side let...,2025-03-25
21,CAL-A22,QBR - Q1 Wrap,sarah.chen@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, pri...","Q1 quarterly business review. Pipeline, AUM, r...",2025-04-01

In [68]:
df_crm

,crm_id,subject,client_name,client_company,relationship_owner,meeting_date,meeting_time,meeting_type,location,notes,status,created_at
0,CRM-1001,Q1 Portfolio Review,David Park,Meridian Capital,Sarah Chen,2025-03-10,2026-05-21 14:00:00,In-Person,HQ - Conference Room B,Review Q1 allocation strategy. David requested...,Completed,2025-02-28 09:15:00+00:00
1,CRM-1002,Portfolio Walkthrough,Mark Johnson,Summit Advisors,Sarah Chen,2025-03-12,2026-05-21 10:00:00,In-Person,NYC Office - 30th Floor,Walk through current portfolio positioning and...,Confirmed,2025-03-01 11:30:00+00:00
2,CRM-1003,Introductory Call,Rachel Torres,Lakeshore Partners,James Wu,2025-03-14,2026-05-21 15:00:00,Virtual,NaN,First touch. Referred by Tom Nakamura at Bridg...,Scheduled,2025-03-10 14:00:00+00:00
3,CRM-1004,Due Diligence Review,Patricia Langley,Crestview Holdings,Sarah Chen,2025-03-13,2026-05-21 14:00:00,In-Person,DC Office - Main Conference Room,DD deep-dive on Fund VII. Legal team joining.,Confirmed,2025-03-05 08:45:00+00:00
4,CRM-1005,Investor Update,Kevin O'Brien,Pinnacle Group,James Wu,2025-03-17,2026-05-21 11:00:00,In-Person,Boston Office,Quarterly update. Kevin may bring CIO.,Confirmed,2025-03-03 16:20:00+00:00
5,CRM-1006,Pipeline Review,NaN,NaN,Sarah Chen,2025-03-14,2026-05-21 16:00:00,Internal,HQ - Room 4A,Weekly pipeline review with full team.,Confirmed,2025-01-15 10:00:00+00:00
6,CRM-1007,Follow-up Discussion,David Park,Meridian Capital,Sarah Chen,2025-03-18,NaT,Virtual,NaN,Follow up on fee schedule questions from Q1 re...,Scheduled,2025-03-11 09:30:00+00:00
7,CRM-1008,Lunch Meeting,Lisa Tran,Atlas Ventures,James Wu,03-15/2025,2026-05-21 12:00:00,In-Person,The Capital Grille - Georgetown,Relationship building. Lisa interested in infr...,Confirmed,2025-03-08 13:00:00+00:00
8,CRM-1009,Board Prep Session,NaN,NaN,Sarah Chen,2025-03-19,2026-05-21 09:00:00,Internal,HQ - Boardroom,Prep Q1 board materials. CANCELLED — reschedul...,Cancelled,2025-03-01 08:00:00+00:00
9,CRM-1010,Strategy Discussion,Alan Whitfield,Northwind Investments,James Wu,2025-03-20,2026-05-21 10:00:00,Virtual,Microsoft Teams,,Tentative,2025-03-14 17:30:00+00:00
10,CRM-1011,Annual Allocation Review,Elena Marcos,Horizon Wealth Partners,James Wu,2025-03-21,2026-05-21 09:00:00,In-Person,NYC Office,Full-year allocation review. Elena wants to di...,Confirmed,2025-03-07 10:15:00+00:00
11,CRM-1012,Co-Investment Opportunity,Thomas Grant,Granite Point Capital,Sarah Chen,2025-03-21,2026-05-21 14:00:00,Virtual,Zoom,Present co-invest opportunity in Fund VII deal...,Confirmed,2025-03-12 11:00:00+00:00
12,CRM-1013,LP Advisory Committee Prep,NaN,NaN,Sarah Chen,2025-03-24,2026-05-21 10:00:00,Internal,HQ - Boardroom,Prepare materials and talking points for upcom...,Confirmed,2025-03-15 09:00:00+00:00
13,CRM-1014,Quick Check-in,Michael Reeves,Evergreen Capital,James Wu,2025-03-25,2026-05-21 08:30:00,Virtual,NaN,Brief call re: capital call timing for Fund VI...,Confirmed,2025-03-20 14:00:00+00:00
14,CRM-1015,Infrastructure Fund Pitch,Lisa Tran,Atlas Ventures,James Wu,2025-03-26,2026-05-21 10:00:00,In-Person,HQ - Conference Room A,Formal pitch for Infra V. Follow-up from March...,Confirmed,2025-03-16 08:30:00+00:00
15,CRM-1016,ESG Compliance Discussion,Karen White,Redwood Institutional,Sarah Chen,2025-03-27,2026-05-21 13:00:00,Virtual,Microsoft Teams,Karen has ESG reporting requirements for their...,Confirmed,2025-03-18 09:45:00+00:00
16,CRM-1017,Closing Dinner,Multiple,Fund VII Investors,James Wu,2025-03-28,2026-05-21 19:00:00,In-Person,The Palm - DC,Celebratory dinner for Fund VII final close. 1...,Confirmed,2025-03-10 16:00:00+00:00
17,CRM-1018,Follow-up Call,Patricia Langley,Crestview Holdings,Sarah Chen,2025-03-25,2026-05-21 16:30:00,Virtual,NaN,Follow up on DD questions from 3/13 meeting. P...,Confirmed,2025-03-17 10:20:00+00:00
18,CRM-1019,Quarterly Business Review,NaN,NaN,Sarah Chen,2025-04-01,2026-05-21 14:00:00,Internal,HQ - Large Conference Room,"Q1 wrap. Review pipeline, AUM growth, client r...",Confirmed,2025-03-05 12:00:00+00:00
19,CRM-1020,Northwind - Fund VII Interest,Alan Whitfield,Northwind Investments,James Wu,2025-04-02,2026-05-21 11:00:00,In-Person,NYC Office - 30th Floor,Deep dive on Fund VII. Alan indicated potentia...,Tentative,2025-03-21 15:00:00+00:00

In [50]:
df_crm.columns

Index(['crm_id', 'subject', 'client_name', 'client_company',
       'relationship_owner', 'meeting_date', 'meeting_time', 'meeting_type',
       'location', 'notes', 'status', 'created_at'],
      dtype='str')

In [64]:
df_crm_sub=df_crm[['crm_id','subject','notes','client_name','relationship_owner','meeting_date']]
df_crm_sub

,crm_id,subject,notes,client_name,relationship_owner,meeting_date
0,CRM-1001,Q1 Portfolio Review,Review Q1 allocation strategy. David requested...,David Park,Sarah Chen,2025-03-10
1,CRM-1002,Portfolio Walkthrough,Walk through current portfolio positioning and...,Mark Johnson,Sarah Chen,2025-03-12
2,CRM-1003,Introductory Call,First touch. Referred by Tom Nakamura at Bridg...,Rachel Torres,James Wu,2025-03-14
3,CRM-1004,Due Diligence Review,DD deep-dive on Fund VII. Legal team joining.,Patricia Langley,Sarah Chen,2025-03-13
4,CRM-1005,Investor Update,Quarterly update. Kevin may bring CIO.,Kevin O'Brien,James Wu,2025-03-17
5,CRM-1006,Pipeline Review,Weekly pipeline review with full team.,NaN,Sarah Chen,2025-03-14
6,CRM-1007,Follow-up Discussion,Follow up on fee schedule questions from Q1 re...,David Park,Sarah Chen,2025-03-18
7,CRM-1008,Lunch Meeting,Relationship building. Lisa interested in infr...,Lisa Tran,James Wu,03-15/2025
8,CRM-1009,Board Prep Session,Prep Q1 board materials. CANCELLED — reschedul...,NaN,Sarah Chen,2025-03-19
9,CRM-1010,Strategy Discussion,,Alan Whitfield,James Wu,2025-03-20
10,CRM-1011,Annual Allocation Review,Full-year allocation review. Elena wants to di...,Elena Marcos,James Wu,2025-03-21
11,CRM-1012,Co-Investment Opportunity,Present co-invest opportunity in Fund VII deal...,Thomas Grant,Sarah Chen,2025-03-21
12,CRM-1013,LP Advisory Committee Prep,Prepare materials and talking points for upcom...,NaN,Sarah Chen,2025-03-24
13,CRM-1014,Quick Check-in,Brief call re: capital call timing for Fund VI...,Michael Reeves,James Wu,2025-03-25
14,CRM-1015,Infrastructure Fund Pitch,Formal pitch for Infra V. Follow-up from March...,Lisa Tran,James Wu,2025-03-26
15,CRM-1016,ESG Compliance Discussion,Karen has ESG reporting requirements for their...,Karen White,Sarah Chen,2025-03-27
16,CRM-1017,Closing Dinner,Celebratory dinner for Fund VII final close. 1...,Multiple,James Wu,2025-03-28
17,CRM-1018,Follow-up Call,Follow up on DD questions from 3/13 meeting. P...,Patricia Langley,Sarah Chen,2025-03-25
18,CRM-1019,Quarterly Business Review,"Q1 wrap. Review pipeline, AUM growth, client r...",NaN,Sarah Chen,2025-04-01
19,CRM-1020,Northwind - Fund VII Interest,Deep dive on Fund VII. Alan indicated potentia...,Alan Whitfield,James Wu,2025-04-02

In [67]:
df_crm_sub['meeting_date']=df_crm_sub['meeting_date'] = df_crm_sub['meeting_date'].apply(
    lambda x: x.replace('//', '-') if '//' in x else x
)

In [69]:
df_crm_sub

,crm_id,subject,notes,client_name,relationship_owner,meeting_date
0,CRM-1001,Q1 Portfolio Review,Review Q1 allocation strategy. David requested...,David Park,Sarah Chen,2025-03-10
1,CRM-1002,Portfolio Walkthrough,Walk through current portfolio positioning and...,Mark Johnson,Sarah Chen,2025-03-12
2,CRM-1003,Introductory Call,First touch. Referred by Tom Nakamura at Bridg...,Rachel Torres,James Wu,2025-03-14
3,CRM-1004,Due Diligence Review,DD deep-dive on Fund VII. Legal team joining.,Patricia Langley,Sarah Chen,2025-03-13
4,CRM-1005,Investor Update,Quarterly update. Kevin may bring CIO.,Kevin O'Brien,James Wu,2025-03-17
5,CRM-1006,Pipeline Review,Weekly pipeline review with full team.,NaN,Sarah Chen,2025-03-14
6,CRM-1007,Follow-up Discussion,Follow up on fee schedule questions from Q1 re...,David Park,Sarah Chen,2025-03-18
7,CRM-1008,Lunch Meeting,Relationship building. Lisa interested in infr...,Lisa Tran,James Wu,03-15/2025
8,CRM-1009,Board Prep Session,Prep Q1 board materials. CANCELLED — reschedul...,NaN,Sarah Chen,2025-03-19
9,CRM-1010,Strategy Discussion,,Alan Whitfield,James Wu,2025-03-20
10,CRM-1011,Annual Allocation Review,Full-year allocation review. Elena wants to di...,Elena Marcos,James Wu,2025-03-21
11,CRM-1012,Co-Investment Opportunity,Present co-invest opportunity in Fund VII deal...,Thomas Grant,Sarah Chen,2025-03-21
12,CRM-1013,LP Advisory Committee Prep,Prepare materials and talking points for upcom...,NaN,Sarah Chen,2025-03-24
13,CRM-1014,Quick Check-in,Brief call re: capital call timing for Fund VI...,Michael Reeves,James Wu,2025-03-25
14,CRM-1015,Infrastructure Fund Pitch,Formal pitch for Infra V. Follow-up from March...,Lisa Tran,James Wu,2025-03-26
15,CRM-1016,ESG Compliance Discussion,Karen has ESG reporting requirements for their...,Karen White,Sarah Chen,2025-03-27
16,CRM-1017,Closing Dinner,Celebratory dinner for Fund VII final close. 1...,Multiple,James Wu,2025-03-28
17,CRM-1018,Follow-up Call,Follow up on DD questions from 3/13 meeting. P...,Patricia Langley,Sarah Chen,2025-03-25
18,CRM-1019,Quarterly Business Review,"Q1 wrap. Review pipeline, AUM growth, client r...",NaN,Sarah Chen,2025-04-01
19,CRM-1020,Northwind - Fund VII Interest,Deep dive on Fund VII. Alan indicated potentia...,Alan Whitfield,James Wu,2025-04-02

In [70]:
df_cal_sub

,event_id,title,organizer,attendees,description,date
0,CAL-A1,Q1 Portfolio Review - Meridian Capital,sarah.chen@firma.com,"(sarah.chen@firma.com, david.park@meridiancap....",Quarterly review of portfolio allocation and p...,2025-03-10
1,CAL-A2,Summit Advisors - Portfolio Discussion,sarah.chen@firma.com,"(sarah.chen@firma.com, mark.johnson@summitadv....",Portfolio walkthrough with Summit team.,2025-03-12
2,CAL-A3,Weekly Team Sync,sarah.chen@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, pri...",Standing weekly sync.,2025-03-11
3,CAL-A4,Crestview Holdings - DD Meeting,sarah.chen@firma.com,"(sarah.chen@firma.com, patricia.langley@crestv...",Due diligence deep-dive. Fund VII materials pr...,2025-03-13
4,CAL-A5,Investor Update - Pinnacle,james.wu@firma.com,"(james.wu@firma.com, kevin.obrien@pinnaclegp.com)",Quarterly investor update for Pinnacle Group.,2025-03-17
5,CAL-A6,Pinnacle Group - Q1 Update,james.wu@firma.com,"(james.wu@firma.com, kevin.obrien@pinnaclegp.c...",Q1 update with Pinnacle Group. Sandra Mills (C...,2025-03-17
6,CAL-A7,Internal Pipeline Review,sarah.chen@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, pri...",Review active pipeline and upcoming client mee...,2025-03-14
7,CAL-A8,Meridian Capital - Follow-up,sarah.chen@firma.com,"(sarah.chen@firma.com, david.park@meridiancap....",Follow-up re: fee schedule and allocation chan...,2025-03-18
8,CAL-A9,Atlas Ventures Lunch,james.wu@firma.com,"(james.wu@firma.com, lisa.tran@atlasvc.com)",Lunch with Lisa Tran. Exploring infrastructure...,2025-03-15
9,CAL-A10,Board Prep - Q1 Materials Review,sarah.chen@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, mic...",Review and finalize Q1 board presentation mate...,2025-03-19
11,CAL-A12,Horizon Wealth - Year-End Review,james.wu@firma.com,"(james.wu@firma.com, elena.marcos@horizonwp.com)",Annual review of allocation strategy and alter...,2025-03-21
12,CAL-A13,Granite Point - Co-Invest Discussion,sarah.chen@firma.com,"(sarah.chen@firma.com, thomas.grant@granitepoi...",Co-investment opportunity walkthrough for Fund...,2025-03-21
13,CAL-A14,LPAC Prep Working Session,priya.sharma@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, pri...",Prep session for LP Advisory Committee meeting...,2025-03-24
14,CAL-A15,Michael Reeves - Quick Sync,james.wu@firma.com,"(james.wu@firma.com, michael.reeves@evergreenc...",Capital call timing discussion.,2025-03-25
15,CAL-A16,Atlas Ventures - Infrastructure Deep Dive,james.wu@firma.com,"(james.wu@firma.com, lisa.tran@atlasvc.com, ra...",Formal infrastructure fund presentation. Raj P...,2025-03-26
16,CAL-A17,ESG + Compliance Review,sarah.chen@firma.com,"(sarah.chen@firma.com, karen.white@redwoodinst...",Walk through ESG reporting framework and compl...,2025-03-27
17,CAL-A18,Weekly Team Sync,sarah.chen@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, pri...",Standing weekly sync.,2025-03-18
18,CAL-A19,Fund VII Roadshow Prep,sarah.chen@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, pri...",Finalize roadshow materials and talking points...,2025-03-28
19,CAL-A20,Fund VII Closing Dinner,james.wu@firma.com,"(james.wu@firma.com, sarah.chen@firma.com, kev...",Celebratory dinner for Fund VII final close.,2025-03-28
20,CAL-A21,Crestview Follow-up Call,sarah.chen@firma.com,"(sarah.chen@firma.com, patricia.langley@crestv...",Follow-up on due diligence questions. Side let...,2025-03-25
21,CAL-A22,QBR - Q1 Wrap,sarah.chen@firma.com,"(sarah.chen@firma.com, james.wu@firma.com, pri...","Q1 quarterly business review. Pipeline, AUM, r...",2025-04-01

In [72]:
df_cal_sub['organizer'] = df_cal_sub["organizer"].apply(lambda x : x.split("@")[0])
df_cal_sub['organizer'] = df_cal_sub['organizer'] .apply(lambda x: x.replace(".", " "))